USE [Odin]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

DROP PROCEDURE [dbo].[ClearDatabase]
GO

CREATE PROCEDURE [dbo].[ClearDatabase] 
AS
BEGIN

	SET NOCOUNT ON;
	
	TRUNCATE TABLE [Odin].[dbo].[PS_AMAZON_ITEM_ATTRIBUTES]
	TRUNCATE TABLE [Odin].[dbo].[PS_ASSET_ITEM_ATTR]
	TRUNCATE TABLE [Odin].[dbo].[PS_BU_ITEMS_CONFIG]
	TRUNCATE TABLE [Odin].[dbo].[PS_BU_ITEMS_INV]
	TRUNCATE TABLE [Odin].[dbo].[PS_BU_ITEM_UTIL_CD]
	TRUNCATE TABLE [Odin].[dbo].[PS_CM_GROUP_DEFN]
	TRUNCATE TABLE [Odin].[dbo].[PS_CM_ITEM_METHOD]
	TRUNCATE TABLE [Odin].[dbo].[PS_COUNTRY_TBL]
	TRUNCATE TABLE [Odin].[dbo].[PS_CUSTOMER_PRODUCT_ATTRIBUTES]
	TRUNCATE TABLE [Odin].[dbo].[PS_DEFAULT_LOC_INV]
	TRUNCATE TABLE [Odin].[dbo].[PS_EN_BOM_COMPS]
	TRUNCATE TABLE [Odin].[dbo].[PS_EN_BOM_HEADER]
	TRUNCATE TABLE [Odin].[dbo].[PS_FXD_BIN_LOC_INV]
	TRUNCATE TABLE [Odin].[dbo].[PS_HRMN_TARIFF_CD]
	TRUNCATE TABLE [Odin].[dbo].[PS_ITM_CAT_TBL]
	TRUNCATE TABLE [Odin].[dbo].[PS_INV_ITEM_FAM]
	TRUNCATE TABLE [Odin].[dbo].[PS_INV_ITEM_GROUP]
	TRUNCATE TABLE [Odin].[dbo].[PS_INV_ITEM_UOM]
	TRUNCATE TABLE [Odin].[dbo].[PS_INV_ITEMS]
	TRUNCATE TABLE [Odin].[dbo].[PS_ITEM_ATTRIB_EX]
	TRUNCATE TABLE [Odin].[dbo].[PS_ITEM_COMPLIANCE]
	TRUNCATE TABLE [Odin].[dbo].[PS_ITEM_LANGUAGE]
	TRUNCATE TABLE [Odin].[dbo].[PS_ITEM_MFG]
	TRUNCATE TABLE [Odin].[dbo].[PS_ITEM_TERRITORY]
	TRUNCATE TABLE [Odin].[dbo].[PS_ITEM_WEB_INFO]
	TRUNCATE TABLE [Odin].[dbo].[PS_MASTER_ITEM_TBL]
	/* TRUNCATE TABLE [Odin].[dbo].[ODIN_CUSTOMER_CONVERSION] */
	TRUNCATE TABLE [Odin].[dbo].[ODIN_EXCEL_LAYOUT_DATA]
	TRUNCATE TABLE [Odin].[dbo].[ODIN_EXCEL_LAYOUT_IDS]
	TRUNCATE TABLE [Odin].[dbo].[ODIN_FIELD_VALUES]
	TRUNCATE TABLE [Odin].[dbo].[ODIN_ITEM_TEMPLATES]
	TRUNCATE TABLE [Odin].[dbo].[ODIN_ITEM_UPDATE_RECORDS]
	TRUNCATE TABLE [Odin].[dbo].[ODIN_LANGUAGES]
	TRUNCATE TABLE [Odin].[dbo].[Odin_MetaDescription]	
	TRUNCATE TABLE [Odin].[dbo].[Odin_NewWebCategories]	
	TRUNCATE TABLE [Odin].[dbo].[ODIN_OPTIONS_TABLE]
	TRUNCATE TABLE [Odin].[dbo].[Odin_RequestComments]
	TRUNCATE TABLE [Odin].[dbo].[Odin_RolePermissions]
	TRUNCATE TABLE [Odin].[dbo].[ODIN_SPECIAL_CHARS]
	TRUNCATE TABLE [Odin].[dbo].[ODIN_TERRITORIES]
	TRUNCATE TABLE [Odin].[dbo].[ODIN_TOOL_TIPS]
	TRUNCATE TABLE [Odin].[dbo].[Odin_UserRoles]
	TRUNCATE TABLE [Odin].[dbo].[Odin_Web_Languages]
	TRUNCATE TABLE [Odin].[dbo].[Odin_Web_License]
	TRUNCATE TABLE [Odin].[dbo].[Odin_WebsiteItemRequests]
	TRUNCATE TABLE [Odin].[dbo].[Odin_Web_Territories]
	TRUNCATE TABLE [Odin].[dbo].[PS_PL_ITEM_ATTRIB]
	TRUNCATE TABLE [Odin].[dbo].[PS_PROD_CATGRY_TBL]
	TRUNCATE TABLE [Odin].[dbo].[PS_PROD_GROUP_TBL]
	TRUNCATE TABLE [Odin].[dbo].[PS_PROD_ITEM]
	TRUNCATE TABLE [Odin].[dbo].[PS_PROD_PGRP_LNK]
	TRUNCATE TABLE [Odin].[dbo].[PS_PROD_PRICE]
	TRUNCATE TABLE [Odin].[dbo].[PS_PROD_PRICE_BU]
	TRUNCATE TABLE [Odin].[dbo].[PS_PRODUCT_FORMATS]
	TRUNCATE TABLE [Odin].[dbo].[PS_PRODUCT_GROUPS]
	TRUNCATE TABLE [Odin].[dbo].[PS_PRODUCT_LINES]
	TRUNCATE TABLE [Odin].[dbo].[PS_PROD_UOM]
	TRUNCATE TABLE [Odin].[dbo].[PS_PURCH_ITEM_ATTR]
	TRUNCATE TABLE [Odin].[dbo].[PS_PURCH_ITEM_BU]
	TRUNCATE TABLE [Odin].[dbo].[PS_PV_ITM_CATEGORY]
	TRUNCATE TABLE [Odin].[dbo].[PS_UOM_TYPE_INV]
	
END
