/*
SELECT * FROM PS_ASSET_ITEM_ATTR
*/
DROP PROCEDURE Odin_InsertAssetItemAttr
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE Odin_InsertAssetItemAttr
	@itemId VARCHAR(18)=''
AS
BEGIN

	SET NOCOUNT ON;
	IF NOT EXISTS (SELECT * FROM PS_ASSET_ITEM_ATTR 
                   WHERE INV_ITEM_ID = @itemId
				   )
		   BEGIN
	INSERT INTO PS_ASSET_ITEM_ATTR(
		SETID,
		INV_ITEM_ID,
		PROFILE_ID)
	VALUES(
		'SHARE',	--SETID
		@itemId,	--INV_ITEM_ID
		'')			--PROFILE_ID

		END
END
GO

GRANT EXECUTE ON Odin_InsertAssetItemAttr TO Odin