
DROP PROCEDURE Odin_InsertPurchItemAttr
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE Odin_InsertPurchItemAttr
	@itemId varchar(18)='',
	@description varchar(254)='',
	@desc30 varchar(30)='',
	@desc10 varchar(10)='',
	@stndrdCost decimal(15,5)=''
	

AS
BEGIN

	SET NOCOUNT ON;
	
	IF NOT EXISTS (SELECT * FROM PS_PURCH_ITEM_ATTR 
                   WHERE INV_ITEM_ID = @itemId
				   )
		   BEGIN
			   INSERT INTO PS_PURCH_ITEM_ATTR(
	SETID,
	INV_ITEM_ID,
	PO_AVAIL_DT,
	PO_UNAVAIL_DT,
	DESCR,
	DESCRSHORT,
	ACCOUNT,
	ALTACCT,
	DEPTID,
	OPERATING_UNIT,
	PRODUCT,
	FUND_CODE,
	CLASS_FLD,
	PROGRAM_CODE,
	BUDGET_REF,
	AFFILIATE,
	AFFILIATE_INTRA1,
	AFFILIATE_INTRA2,
	CHARTFIELD1,
	CHARTFIELD2,
	CHARTFIELD3,
	PROJECT_ID,
	PRICE_LIST,
	TAXABLE_CD,
	AUTO_SOURCE,
	STD_LEAD,
	UNIT_PRC_TOL,
	EXT_PRC_TOL,
	PCT_UNIT_PRC_TOL,
	PCT_EXT_PRC_TOL,
	INSPECT_CD,
	INSPECT_UOM_TYPE,
	ROUTING_ID,
	RECV_REQ,
	QTY_RECV_TOL_PCT,
	RJCT_OVER_TOL_FLAG,
	RFQ_REQ_FLAG,
	REJECT_DAYS,
	PRIMARY_BUYER,
	MODEL,
	ACCEPT_ALL_VENDOR,
	ACCEPT_ALL_SHIPTO,
	CONTRACT_REQ,
	DESCR254_MIXED,
	FILENAME,
	FILE_EXTENSION,
	RECV_PARTIAL_FLG,
	CURRENCY_CD,
	PCT_UNDER_QTY,
	STOCKLESS_FLG,
	INSPECT_SAMPLE_PER,
	VAT_SVC_PERFRM_FLG,
	LAST_PO_PRICE_PAID,
	SRC_METHOD,
	LEAD_TIME_IMP,
	PRICE_IMP,
	SHIPTO_PR_IMP,
	VNDR_PR_IMP,
	USE_CAT_SRC_CNTL,
	UNIT_PRC_TOL_L,
	PCT_UNIT_PRC_TOL_L,
	EXT_PRC_TOL_L,
	PCT_EXT_PRC_TOL_L,
	PACKING_VOLUME,
	PACKING_WEIGHT,
	UNIT_MEASURE_VOL,
	UNIT_MEASURE_WT,
	SHIP_LATE_DAYS,
	SHIP_TYPE_ID,
	KB_PAST_DUE_PO,
	KB_OVR_RECV_TOL,
	ULTIMATE_USE_CD,
	WF_PCT_PRC_TOL_OVR,
	WF_PCT_PRC_TOL_UND,
	WF_PRC_TOL_OVR,
	WF_PRC_TOL_UND,
	AVAIL_ALL_RGNS,
	OPRID_MODIFIED_BY,
	LAST_DTTM_UPDATE
			)
	VALUES(
	'SHARE',							--SETID
	@itemId,							--INV_ITEM_ID
	CONVERT(CHAR(10), GETDATE(), 121),	--PO_AVAIL_DT
	'2999-12-31',								--PO_UNAVAIL_DT
	@desc30,							--DESCR
	@desc10,							--DESCRSHORT
	23000,						--ACCOUNT
	'',							--ALTACCT
	'',							--DEPTID
	'',							--OPERATING_UNIT
	'',							--PRODUCT
	'',							--FUND_CODE
	'',							--CLASS_FLD
	'',							--PROGRAM_CODE
	'',							--BUDGET_REF
	'',							--AFFILIATE
	'',							--AFFILIATE_INTRA1
	'',							--AFFILIATE_INTRA2
	'',							--CHARTFIELD1
	'',							--CHARTFIELD2
	'',							--CHARTFIELD3
	'',							--PROJECT_ID
	@stndrdCost,				--PRICE_LIST
	'Y',						--TAXABLE_CD
	'Y',						--AUTO_SOURCE
	0,							--STD_LEAD
	999999.00000,				--UNIT_PRC_TOL
	50.00000,					--EXT_PRC_TOL
	5.00,						--PCT_UNIT_PRC_TOL
	100.00,						--PCT_EXT_PRC_TOL
	'N',						--INSPECT_CD
	'S',						--INSPECT_UOM_TYPE
	'',							--ROUTING_ID
	'Y',						--RECV_REQ
	0.00,						--QTY_RECV_TOL_PCT
	'N',						--RJCT_OVER_TOL_FLAG
	'N',						--RFQ_REQ_FLAG
	0,							--REJECT_DAYS
	'',							--PRIMARY_BUYER
	'',							--MODEL
	'Y',						--ACCEPT_ALL_VENDOR
	'Y',						--ACCEPT_ALL_SHIPTO
	'N',						--CONTRACT_REQ
	@description,				--DESCR254_MIXED
	'',							--FILENAME
	'',							--FILE_EXTENSION
	1,							--RECV_PARTIAL_FLG
	'USD',						--CURRENCY_CD
	0,							--PCT_UNDER_QTY
	'N',						--STOCKLESS_FLG
	0.00,						--INSPECT_SAMPLE_PER
	'',							--VAT_SVC_PERFRM_FLG
	0.00,							--LAST_PO_PRICE_PAID
	'B',						--SRC_METHOD
	0.00,						--LEAD_TIME_IMP
	0.00,						--PRICE_IMP
	0.00,						--SHIPTO_PR_IMP
	0.00,						--VNDR_PR_IMP
	'N',						--USE_CAT_SRC_CNTL
	999999.00000,				--UNIT_PRC_TOL_L
	100.00,						--PCT_UNIT_PRC_TOL_L
	999999.00000,				--EXT_PRC_TOL_L
	100.00,						--PCT_EXT_PRC_TOL_L
	0.0000,						--PACKING_VOLUME
	0.0000,						--PACKING_WEIGHT
	'',							--UNIT_MEASURE_VOL
	'',							--UNIT_MEASURE_WT
	0,							--SHIP_LATE_DAYS
	'',							--SHIP_TYPE_ID
	'N',						--KB_PAST_DUE_PO
	0.00,						--KB_OVR_RECV_TOL
	'',							--ULTIMATE_USE_CD
	999.00,						--WF_PCT_PRC_TOL_OVR
	999.00,						--WF_PCT_PRC_TOL_UND
	99999999.00000,				--WF_PRC_TOL_OVR
	99999999.00000,				--WF_PRC_TOL_UND
	'Y',						--AVAIL_ALL_RGNS
	'',							--OPRID_MODIFIED_BY
	NULL						--LAST_DTTM_UPDATE
	)		
		   END
	
	UPDATE PS_PURCH_ITEM_ATTR
	SET 
		DESCR = @desc30,
		DESCRSHORT = @desc10,
		PRICE_LIST = @stndrdCost,
		DESCR254_MIXED = @description,
		LAST_DTTM_UPDATE = GETDATE()
	WHERE 
		INV_ITEM_ID = @itemId
		AND SETID='SHARE'

END
GO

GRANT EXECUTE ON Odin_InsertPurchItemAttr TO Odin
GO
/*
SELECT * FROM PS_PURCH_ITEM_ATTR
sp_help PS_PURCH_ITEM_ATTR
*/
