
DROP PROCEDURE Odin_RetrieveItemRecords
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE Odin_RetrieveItemRecords
AS
BEGIN

	SET NOCOUNT ON;
	
	SELECT INV_ITEM_ID, 
		ITEM_INPUT_STATUS, 
		USERNAME,
		MAX(INPUT_DATE) AS INPUT_DATE
	FROM ODIN_ITEM_UPDATE_RECORDS 
	GROUP BY INV_ITEM_ID, USERNAME, ITEM_INPUT_STATUS
	ORDER BY INV_ITEM_ID
		 
END
GO

GRANT EXECUTE ON Odin_RetrieveItemRecords TO Odin
GO
