/*
SELECT * FROM PS_BU_ITEM_UTIL_CD ORDER BY INV_ITEM_ID
sp_help PS_BU_ITEM_UTIL_CD
*/
DROP PROCEDURE Odin_InsertBuItemUtilCd


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE Odin_InsertBuItemUtilCd
	@itemId VARCHAR(18)='',
	@busUnit VARCHAR(5)
AS
BEGIN

	SET NOCOUNT ON;
	IF NOT EXISTS (SELECT * FROM PS_BU_ITEM_UTIL_CD 
                   WHERE INV_ITEM_ID = @itemId
                   AND BUSINESS_UNIT = @busUnit
				   )
		   BEGIN
	INSERT INTO PS_BU_ITEM_UTIL_CD(
	BUSINESS_UNIT,
	INV_ITEM_ID,
	UTILIZ_GROUP,
	UTILIZ_CD,
	PLANNING_FLG
	)
	VALUES(
	@busUnit,			--BUSINESS_UNIT
	@itemId,			--INV_ITEM_ID
	'MC',				--UTILIZ_GROUP
	'',					--UTILIZ_CD
	'N'					--PLANNING_FLG
	)				

	END
END
GO

GRANT EXECUTE ON Odin_InsertBuItemUtilCd TO Odin
GO