
DROP PROCEDURE Odin_RetrieveExcelLayoutData
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE Odin_RetrieveExcelLayoutData
	@layoutName VARCHAR(255)
AS
BEGIN

	SET NOCOUNT ON;

	SELECT 
		EXCEL_LAYOUT_IDS.LAYOUT_NAME,
		EXCEL_LAYOUT_DATA.LAYOUT_ID,
		EXCEL_LAYOUT_DATA.COLUMN_NUMBER,
		EXCEL_LAYOUT_DATA.FIELD,
		EXCEL_LAYOUT_DATA.[OPTION],
		EXCEL_LAYOUT_DATA.CUSTOMER
	FROM ODIN_EXCEL_LAYOUT_DATA EXCEL_LAYOUT_DATA
	INNER JOIN ODIN_EXCEL_LAYOUT_IDS EXCEL_LAYOUT_IDS
		ON EXCEL_LAYOUT_IDS.LAYOUT_ID = EXCEL_LAYOUT_DATA.LAYOUT_ID
	WHERE EXCEL_LAYOUT_IDS.LAYOUT_NAME = @layoutName	
	ORDER BY EXCEL_LAYOUT_DATA.COLUMN_NUMBER ASC 

END
GO

GRANT EXECUTE ON Odin_RetrieveExcelLayoutData TO Odin
GO
