
DROP PROCEDURE Odin_RetrieveActiveEcommerceItems
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE Odin_RetrieveActiveEcommerceItems(
	@startDate PSDATE,
	@endDate PSDATE,
	@productGroup Varchar(30) = '',
	@customerId varchar(15) = ''
	)
AS
BEGIN

	SET NOCOUNT ON;

	SELECT DISTINCT
			     AMAZON_ITEM_ATTRIBUTES.ASIN,
			     AMAZON_ITEM_ATTRIBUTES.INV_ITEM_ID,
			     AMAZON_ITEM_ATTRIBUTES.ITEM_NAME,
				 AMAZON_ITEM_ATTRIBUTES.MODEL_NAME,
				 AMAZON_ITEM_ATTRIBUTES.PRODUCT_CATEGORY,
				 AMAZON_ITEM_ATTRIBUTES.PRODUCT_SUBCATEGORY,
				 AMAZON_ITEM_ATTRIBUTES.BULLET_1,
				 AMAZON_ITEM_ATTRIBUTES.BULLET_2,
				 AMAZON_ITEM_ATTRIBUTES.BULLET_3,
				 AMAZON_ITEM_ATTRIBUTES.BULLET_4,
				 AMAZON_ITEM_ATTRIBUTES.BULLET_5,
				 AMAZON_ITEM_ATTRIBUTES.FULL_DESCRIPTION,
				 AMAZON_ITEM_ATTRIBUTES.EXTERNAL_ID_TYPE,
				 AMAZON_ITEM_ATTRIBUTES.EXTERNAL_ID,
				 AMAZON_ITEM_ATTRIBUTES.SEARCH_TERMS,
				 AMAZON_ITEM_ATTRIBUTES.IMAGE_URL_1,
				 AMAZON_ITEM_ATTRIBUTES.IMAGE_URL_2,
				 AMAZON_ITEM_ATTRIBUTES.IMAGE_URL_3,
				 AMAZON_ITEM_ATTRIBUTES.IMAGE_URL_4,
				 AMAZON_ITEM_ATTRIBUTES.IMAGE_URL_5,
				 AMAZON_ITEM_ATTRIBUTES.SIZE,
				 AMAZON_ITEM_ATTRIBUTES.COST,
				 AMAZON_ITEM_ATTRIBUTES.MSRP,
				 AMAZON_ITEM_ATTRIBUTES.MANUFACTURER_NAME,
				 AMAZON_ITEM_ATTRIBUTES.LENGTH,
				 AMAZON_ITEM_ATTRIBUTES.HEIGHT,
				 AMAZON_ITEM_ATTRIBUTES.WIDTH,
				 AMAZON_ITEM_ATTRIBUTES.WEIGHT,
				 AMAZON_ITEM_ATTRIBUTES.PACKAGE_LENGTH,
				 AMAZON_ITEM_ATTRIBUTES.PACKAGE_HEIGHT,
				 AMAZON_ITEM_ATTRIBUTES.PACKAGE_WIDTH,
				 AMAZON_ITEM_ATTRIBUTES.PACKAGE_WEIGHT,
				 AMAZON_ITEM_ATTRIBUTES.PAGE_COUNT,
				 AMAZON_ITEM_ATTRIBUTES.COMPONENTS,
				 AMAZON_ITEM_ATTRIBUTES.UPC_OVERRIDE,
				 BU_ITEMS_INV_CAD.DFLT_ACTUAL_COST AS DACCAD,
				 BU_ITEMS_INV_USD.COUNTRY_IST_ORIGIN AS COUNTRY_OF_ORIGIN,
				 BU_ITEMS_INV_USD.DFLT_ACTUAL_COST AS DACUSD,
				 BU_ITEMS_INV_USD.SOURCE_CODE AS MFG_SOURCE,
				 ITEM_WEB_INFO.CATEGORY,
				 ITEM_WEB_INFO.COPYRIGHT,
				 ITEM_WEB_INFO.IMAGE_PATH,
				 ITEM_WEB_INFO.IN_STOCK_DATE,
				 ITEM_WEB_INFO.ITEM_KEYWORDS,
				 ITEM_WEB_INFO.LICENSE,
				 ITEM_WEB_INFO.META_DESCRIPTION,
				 ITEM_WEB_INFO.PROD_QTY,
				 ITEM_WEB_INFO.PROPERTY,
				 ITEM_WEB_INFO.TITLE
	FROM PS_AMAZON_ITEM_ATTRIBUTES AMAZON_ITEM_ATTRIBUTES
		JOIN PS_ITEM_ATTRIB_EX ITEM_ATTRIB_EX
			ON ITEM_ATTRIB_EX.SETID = 'SHARE'
			AND ITEM_ATTRIB_EX.INV_ITEM_ID = AMAZON_ITEM_ATTRIBUTES.INV_ITEM_ID
		JOIN PS_BU_ITEMS_INV BU_ITEMS_INV_USD
			ON BU_ITEMS_INV_USD.INV_ITEM_ID = AMAZON_ITEM_ATTRIBUTES.INV_ITEM_ID
			AND BU_ITEMS_INV_USD.BUSINESS_UNIT = 'TRUS1'
		JOIN PS_BU_ITEMS_INV BU_ITEMS_INV_CAD
			ON BU_ITEMS_INV_CAD.INV_ITEM_ID = AMAZON_ITEM_ATTRIBUTES.INV_ITEM_ID
			AND BU_ITEMS_INV_CAD.BUSINESS_UNIT = 'TRCN1'
		JOIN PS_ITEM_WEB_INFO ITEM_WEB_INFO
			ON ITEM_WEB_INFO.INV_ITEM_ID = AMAZON_ITEM_ATTRIBUTES.INV_ITEM_ID
		JOIN PS_MASTER_ITEM_TBL MASTER_ITEM_TBL
			ON MASTER_ITEM_TBL.SETID = 'SHARE'
			AND MASTER_ITEM_TBL.INV_ITEM_ID = AMAZON_ITEM_ATTRIBUTES.INV_ITEM_ID
		JOIN PS_CUSTOMER_PRODUCT_ATTRIBUTES CUSTOMER_PRODUCT_ATTRIBUTES
			ON CUSTOMER_PRODUCT_ATTRIBUTES.SETID = 'SHARE'
			AND CUSTOMER_PRODUCT_ATTRIBUTES.CUST_ID = @customerId
		JOIN PS_INV_ITEMS INV_ITEMS
			ON  INV_ITEMS.SETID = 'SHARE'
			AND INV_ITEMS.INV_ITEM_ID = MASTER_ITEM_TBL.INV_ITEM_ID
			AND EFFDT = (SELECT MAX(EFFDT)
						 FROM PS_INV_ITEMS
						 WHERE SETID = 'SHARE'
						   AND INV_ITEM_ID = MASTER_ITEM_TBL.INV_ITEM_ID
						   AND EFFDT <= GETDATE())
	WHERE CUSTOMER_PRODUCT_ATTRIBUTES.SEND_INVENTORY = 'Y'
		AND MASTER_ITEM_TBL.DATE_ADDED BETWEEN @startDate AND @endDate
		AND ITEM_ATTRIB_EX.PROD_GROUP = @productGroup
	ORDER BY AMAZON_ITEM_ATTRIBUTES.INV_ITEM_ID ASC	 

END
GO

GRANT EXECUTE ON Odin_RetrieveActiveEcommerceItems TO Odin
GO
/*
SELECT * FROM PS_AMAZON_ITEM_ATTRIBUTES WHERE INV_ITEM_ID = 'ST5525'
SELECT * FROM PS_MASTER_ITEM_TBL WHERE INV_ITEM_ID = 'ST5525'
sp_help PS_MASTER_ITEM_TBL
*/