/*
SELECT * FROM PS_PURCH_ITEM_BU
*/
DROP PROCEDURE Odin_InsertPurchItemBu


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE Odin_InsertPurchItemBu(
	@itemId varchar(18)
	)
AS
BEGIN

	SET NOCOUNT ON;

	INSERT INTO PS_PURCH_ITEM_BU(
	SETID,
	INV_ITEM_ID,
	BUSINESS_UNIT,
	ACCOUNT,
	ALTACCT,
	DEPTID,
	OPERATING_UNIT,
	PRODUCT,
	FUND_CODE,
	CLASS_FLD,
	PROGRAM_CODE,
	BUDGET_REF,
	AFFILIATE,
	AFFILIATE_INTRA1,
	AFFILIATE_INTRA2,
	CHARTFIELD1,
	CHARTFIELD2,
	CHARTFIELD3,
	PROJECT_ID,
	PRICE_LIST,
	TAXABLE_CD,
	AUTO_SOURCE,
	STD_LEAD,
	UNIT_PRC_TOL,
	EXT_PRC_TOL,
	PCT_UNIT_PRC_TOL,
	PCT_EXT_PRC_TOL,
	INSPECT_CD,
	INSPECT_UOM_TYPE,
	ROUTING_ID,
	RECV_REQ,
	QTY_RECV_TOL_PCT,
	RJCT_OVER_TOL_FLAG,
	RFQ_REQ_FLAG,
	REJECT_DAYS,
	PRIMARY_BUYER,
	ACCEPT_ALL_VENDOR,
	ACCEPT_ALL_SHIPTO,
	CONTRACT_REQ,
	RECV_PARTIAL_FLG,
	CURRENCY_CD,
	PCT_UNDER_QTY,
	STOCKLESS_FLG,
	INSPECT_SAMPLE_PER,
	VAT_SVC_PERFRM_FLG,
	LAST_PO_PRICE_PAID,
	UNIT_PRC_TOL_L,
	PCT_UNIT_PRC_TOL_L,
	EXT_PRC_TOL_L,
	PCT_EXT_PRC_TOL_L,
	PACKING_VOLUME,
	PACKING_WEIGHT,
	UNIT_MEASURE_VOL,
	UNIT_MEASURE_WT,
	SHIP_LATE_DAYS,
	SHIP_TYPE_ID,
	KB_PAST_DUE_PO,
	KB_OVR_RECV_TOL,
	ULTIMATE_USE_CD,
	BU_UPD_PRICE,
	OPRID_MODIFIED_BY,
	LAST_DTTM_UPDATE
			)
	VALUES(
	'SHARE',				--SETID
	@itemId,		--INV_ITEM_ID
	'',				--BUSINESS_UNIT
	'',				--ACCOUNT
	'',				--ALTACCT
	'',				--DEPTID
	'',				--OPERATING_UNIT
	'',				--PRODUCT
	'',				--FUND_CODE
	'',				--CLASS_FLD
	'',				--PROGRAM_CODE
	'',				--BUDGET_REF
	'',				--AFFILIATE
	'',				--AFFILIATE_INTRA1
	'',				--AFFILIATE_INTRA2
	'',				--CHARTFIELD1
	'',				--CHARTFIELD2
	'',				--CHARTFIELD3
	'',				--PROJECT_ID
	0.0000,				--PRICE_LIST
	'',				--TAXABLE_CD
	'',				--AUTO_SOURCE
	0,				--STD_LEAD
	0.0000,				--UNIT_PRC_TOL
	0.0000,				--EXT_PRC_TOL
	0.0000,				--PCT_UNIT_PRC_TOL
	0.0000,				--PCT_EXT_PRC_TOL
	'',				--INSPECT_CD
	'',				--INSPECT_UOM_TYPE
	'',				--ROUTING_ID
	'',				--RECV_REQ
	0.0000,				--QTY_RECV_TOL_PCT
	'',				--RJCT_OVER_TOL_FLAG
	'',				--RFQ_REQ_FLAG
	0,				--REJECT_DAYS
	'',				--PRIMARY_BUYER
	'',				--ACCEPT_ALL_VENDOR
	'',				--ACCEPT_ALL_SHIPTO
	'',				--CONTRACT_REQ
	'',				--RECV_PARTIAL_FLG
	'',				--CURRENCY_CD
	0,				--PCT_UNDER_QTY
	'',				--STOCKLESS_FLG
	0.0000,				--INSPECT_SAMPLE_PER
	'',				--VAT_SVC_PERFRM_FLG
	0.0000,				--LAST_PO_PRICE_PAID
	0.0000,				--UNIT_PRC_TOL_L
	0.0000,				--PCT_UNIT_PRC_TOL_L
	0.0000,				--EXT_PRC_TOL_L
	0.0000,				--PCT_EXT_PRC_TOL_L
	0.0000,				--PACKING_VOLUME
	0.0000,				--PACKING_WEIGHT
	'',				--UNIT_MEASURE_VOL
	'',				--UNIT_MEASURE_WT
	0,				--SHIP_LATE_DAYS
	'',				--SHIP_TYPE_ID
	'',				--KB_PAST_DUE_PO
	0.0000,				--KB_OVR_RECV_TOL
	'',				--ULTIMATE_USE_CD
	'',				--BU_UPD_PRICE
	'',				--OPRID_MODIFIED_BY
	GETDATE()				--LAST_DTTM_UPDATE
	)				


END
GO

GRANT EXECUTE ON Odin_InsertPurchItemBu TO Odin