
/*
SELECT * FROM PS_ITEM_TERRITORY
*/

DROP PROCEDURE Odin_InsertTerritory
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/* 
SELECT * FROM PS_ITEM_TERRITORY
sp_help PS_ITEM_TERRITORY
*/
CREATE PROCEDURE Odin_InsertTerritory
	@itemId CHAR(18)='',
	@territory VARCHAR(25) =''
AS
BEGIN

	SET NOCOUNT ON;

	DELETE FROM PS_ITEM_TERRITORY WHERE INV_ITEM_ID = @itemId AND SETID = 'SHARE'
	
	INSERT INTO PS_ITEM_TERRITORY(SETID, INV_ITEM_ID, TERRITORY) SELECT 'SHARE', @itemId, Value FROM Odin_ListToTable(@territory,'/')


END
GO

GRANT EXECUTE ON Odin_InsertTerritory TO Odin
GO
