/*
sp_help ODIN_ITEM_TEMPLATES
ALTER TABLE ODIN_ITEM_TEMPLATES ADD SAT_CODE VARCHAR(20)
ALTER TABLE ODIN_ITEM_TEMPLATES ADD ACTIVE VARCHAR(1)
UPDATE ODIN_ITEM_TEMPLATES SET ACTIVE = 'Y'
*/
DROP PROCEDURE Odin_InsertTemplate
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE Odin_InsertTemplate

	@templateId	varchar	(255) = '',
	@username varchar(18) = '',
	@accountingGroup varchar(10) = '',
	@casepackHeight varchar(6) = '',
	@casepackLength	varchar(6) = '',
	@casepackQty varchar(2) = '',
	@casepackUpc varchar(12) = '',
	@casepackWidth varchar(6) = '',
	@casepackWeight varchar(6) = '',
	@category varchar(MAX) = '',
	@category2	varchar(MAX) = '',
	@category3	varchar(MAX) = '',
	@copyright	varchar(MAX) = '',
	@costProfileGroup varchar(18) = '',
	@defaultActualCostUsd varchar(12) = '',
	@defaultActualCostCad varchar(12) = '',
	@duty varchar(30) = '',
	@gpc varchar(10) = '',
	@height	varchar(12) = '',
	@innerpackHeight varchar(6) = '',
	@innerpackLength varchar(6) = '',
	@innerpackQty varchar(2) = '',
	@innerpackUpc varchar(12) = '',
	@innerpackWidth varchar(6) = '',
	@innerpackWeight varchar(6) = '',
	@itemCategory varchar(60) = '',
	@itemFamily varchar(10) = '',
	@itemGroup varchar(15) = '',
	@itemKeywords varchar(MAX) = '',
	@length	varchar(12) = '',
	@license varchar(255) = '',
	@listPriceCad varchar(16) = '',
	@listPriceUsd varchar(16) = '',
	@listPriceMxn varchar(16) = '',
	@metaDescription varchar(255) = '',
	@mfgSource varchar(2) = '',
	@msrp varchar(10) = '',
	@msrpCad varchar(15) = '',
	@msrpMxn varchar(15) = '',
	@printOnDemand varchar(1) = '',
	@productFormat varchar(60) = '',
	@productGroup varchar(30) = '',
	@productLine varchar(30) = '',
	@productQty varchar(266) = '',
	@pricingGroup varchar(10) = '',
	@psStatus varchar(2) = '',
	@satCode varchar(20) = '',
	@size	varchar(266) = '',
	@standardCost	varchar(15) = '',
	@tariffCode varchar(14) = '',
	@udex varchar(30) = '',
	@weight varchar(12) = '',
	@width varchar(12) = '',
	@ecommerceBullet1 varchar(254) = '',
	@ecommerceBullet2 varchar(254) = '',
	@ecommerceBullet3 varchar(254) = '',
	@ecommerceBullet4 varchar(254) = '',
	@ecommerceBullet5 varchar(254) = '',
	@ecommerceComponents varchar(100) = '',
	@ecommerceCost varchar(12) = '',
	@ecommerceExternalIdType varchar(30) = '',
	@ecommerceItemHeight varchar(12) = '',
	@ecommerceItemLength varchar(12) = '',
	@ecommerceItemWeight varchar(12) = '',
	@ecommerceItemWidth	varchar(12) = '',
	@ecommerceModelName	varchar(50) = '',
	@ecommercePackageLength varchar(12) = '',
	@ecommercePackageHeight	varchar(12) = '',
	@ecommercePackageWidth varchar(12) = '',
	@ecommercePackageWeight varchar(12) = '',
	@ecommerceProductCategory varchar(50) = '',
	@ecommerceProductDescription varchar(8000) = '',
	@ecommerceProductSubcategory varchar(50) = '',
	@ecommerceManufacturerName varchar(100) = '',
	@ecommerceMsrp varchar(12) = '',
	@ecommerceSize varchar(254) = '',
	@active varchar(1)='Y'
AS
BEGIN

	SET NOCOUNT ON;
	IF NOT EXISTS (SELECT * FROM ODIN_ITEM_TEMPLATES 
                   WHERE TEMPLATE_ID = @templateId
				   AND ACTIVE = 'Y')
					   BEGIN
						   INSERT INTO ODIN_ITEM_TEMPLATES(
								TEMPLATE_ID,
								INPUT_DATE,
								USERNAME,
								ACCOUNTING_GROUP,
								CASEPACK_HEIGHT,
								CASEPACK_LENGTH,
								CASEPACK_QTY,
								CASEPACK_UPC,
								CASEPACK_WIDTH,
								CASEPACK_WEIGHT,
								CATEGORY,
								CATEGORY2,
								CATEGORY3,
								COPYRIGHT,
								COST_PROFILE_GROUP,
								DEFAULT_ACTUAL_COST_USD,
								DEFAULT_ACTUAL_COST_CAD,
								DUTY,
								GPC,
								HEIGHT,	
								INNERPACK_HEIGHT,
								INNERPACK_LENGTH,
								INNERPACK_QTY,
								INNERPACK_UPC,
								INNERPACK_WIDTH,
								INNERPACK_WEIGHT,
								ITEM_CATEGORY,
								ITEM_FAMILY,
								ITEM_GROUP,
								ITEM_KEYWORDS,
								[LENGTH],
								LICENSE,
								LIST_PRICE_CAD,
								LIST_PRICE_USD,
								LIST_PRICE_MXN,
								META_DESCRIPTION,
								MFG_SOURCE,
								MSRP,
								MSRP_CAD,
								MSRP_MXN,
								PRINT_ON_DEMAND,
								PRODUCT_FORMAT,
								PRODUCT_GROUP,
								PRODUCT_LINE,
								PROD_QTY,
								PRICING_GROUP,
								PS_STATUS,
								SAT_CODE,
								SIZE,
								STANDARD_COST,
								TARIFF_CODE,
								UDEX,
								[WEIGHT],
								WIDTH,
								ECOMMERCE_BULLET_1,
								ECOMMERCE_BULLET_2,
								ECOMMERCE_BULLET_3,
								ECOMMERCE_BULLET_4,
								ECOMMERCE_BULLET_5,
								ECOMMERCE_COMPONENTS,
								ECOMMERCE_COST,
								ECOMMERCE_EXTERNAL_ID_TYPE,
								ECOMMERCE_ITEM_HEIGHT,
								ECOMMERCE_ITEM_LENGTH,
								ECOMMERCE_ITEM_WEIGHT,
								ECOMMERCE_ITEM_WIDTH,
								ECOMMERCE_MODEL_NAME,
								ECOMMERCE_PACKAGE_LENGTH,
								ECOMMERCE_PACKAGE_HEIGHT,
								ECOMMERCE_PACKAGE_WIDTH,
								ECOMMERCE_PACKAGE_WEIGHT,
								ECOMMERCE_PRODUCT_CATEGORY,
								ECOMMERCE_PRODUCT_DESCRIPTION,
								ECOMMERCE_PRODUCT_SUBCATEGORY,
								ECOMMERCE_MANUFACTURER_NAME,
								ECOMMERCE_MSRP,
								ECOMMERCE_SIZE,
								ACTIVE
								)
						VALUES(
							@templateId,
							GETDATE(),
							@username,
							@accountingGroup,
							@casepackHeight,
							@casepackLength,
							@casepackQty,
							@casepackUpc,
							@casepackWidth,
							@casepackWeight,
							@category,
							@category2,
							@category3,
							@copyright,
							@costProfileGroup,
							@defaultActualCostUsd,
							@defaultActualCostCad,
							@duty,
							@gpc,
							@height,
							@innerpackHeight,
							@innerpackLength,
							@innerpackQty,
							@innerpackUpc,
							@innerpackWidth,
							@innerpackWeight,
							@itemCategory,
							@itemFamily,
							@itemGroup,
							@itemKeywords,
							@length,
							@license,
							@listPriceCad,
							@listPriceUsd,
							@listPriceMxn,
							@metaDescription,
							@mfgSource,
							@msrp,
							@msrpCad,
							@msrpMxn,
							@printOnDemand,
							@productFormat,
							@productGroup,
							@productLine,
							@productQty,
							@pricingGroup,
							@psStatus,
							@satCode,
							@size,
							@standardCost,
							@tariffCode,
							@udex,
							@weight,
							@width,
							@ecommerceBullet1,
							@ecommerceBullet2,
							@ecommerceBullet3,
							@ecommerceBullet4,
							@ecommerceBullet5,
							@ecommerceComponents,
							@ecommerceCost,
							@ecommerceExternalIdType,
							@ecommerceItemHeight,
							@ecommerceItemLength,
							@ecommerceItemWeight,
							@ecommerceItemWidth,
							@ecommerceModelName,
							@ecommercePackageLength,
							@ecommercePackageHeight,
							@ecommercePackageWidth,
							@ecommercePackageWeight,
							@ecommerceProductCategory,
							@ecommerceProductDescription,
							@ecommerceProductSubcategory,
							@ecommerceManufacturerName,
							@ecommerceMsrp,
							@ecommerceSize,
							@active
								)	
					   END

END
GO

GRANT EXECUTE ON Odin_InsertTemplate TO Odin

/*
SELECT * FROM ODIN_ITEM_TEMPLATES
*/