
DROP PROCEDURE Odin_SelectWebsiteItem
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE Odin_SelectWebsiteItem
	@itemId VARCHAR(18)
AS
BEGIN

	SET NOCOUNT ON;

	SELECT
		   ITEM_WEB_INFO.ITEM_KEYWORDS,
		   ITEM_WEB_INFO.CATEGORY,
		   ITEM_WEB_INFO.COPYRIGHT,
		   ITEM_WEB_INFO.TITLE,
		   ITEM_WEB_INFO.LICENSE,
		   ITEM_WEB_INFO.SHORT_DESC,
		   ITEM_WEB_INFO.META_DESCRIPTION,
		   ITEM_WEB_INFO.NEW_DATE,
		   ITEM_WEB_INFO.PROPERTY,
		   ITEM_WEB_INFO.ON_SITE,
		   dbo.Odin_RetrieveItemLanguages(@itemId) AS [LANGUAGE],
		   dbo.Odin_RetrieveItemTerritories(@itemId) AS TERRITORY,
		   ITEM_WEB_INFO.ATTRIBUTE_SET,
		   ITEM_WEB_INFO.IN_STOCK_DATE,
		   ITEM_WEB_INFO.SIZE,
		   ITEM_WEB_INFO.ACTIVE,
		   ITEM_WEB_INFO.PROD_QTY,
		   INV_ITEMS.INV_ITEM_HEIGHT,
		   INV_ITEMS.INV_ITEM_LENGTH,
		   INV_ITEMS.INV_ITEM_WEIGHT,
		   INV_ITEMS.DESCR254,
		   INV_ITEMS.INV_ITEM_WIDTH,
		   ITEM_ATTR.LICENSE_BEGIN_DATE,
		   ITEM_ATTR.PROD_LINE,
		   INV_ITEMS.UPC_ID,
		   (SELECT MFG_SUG_RTL_PRC FROM PS_PROD_PRICE WHERE PRODUCT_ID=@itemId AND BUSINESS_UNIT_IN='TRUS1' AND CURRENCY_CD='USD') AS MSRP1,
		   (SELECT MFG_SUG_RTL_PRC FROM PS_PROD_PRICE WHERE PRODUCT_ID=@itemId AND BUSINESS_UNIT_IN='TRUS1' AND CURRENCY_CD='CAD') AS MSRP2,
		   (SELECT LIST_PRICE FROM PS_PROD_PRICE WHERE PRODUCT_ID=@itemId AND BUSINESS_UNIT_IN='TRCN1' AND CURRENCY_CD='CAD') AS LISTCN,
		   (SELECT LIST_PRICE FROM PS_PROD_PRICE WHERE PRODUCT_ID=@itemId AND BUSINESS_UNIT_IN='TRUS1' AND CURRENCY_CD='USD') AS LISTUS
	FROM PS_ITEM_WEB_INFO ITEM_WEB_INFO
		INNER JOIN	PS_INV_ITEMS INV_ITEMS
			ON INV_ITEMS.INV_ITEM_ID = ITEM_WEB_INFO.INV_ITEM_ID
			AND INV_ITEMS.SETID = 'SHARE'
		INNER JOIN	PS_ITEM_ATTRIB_EX ITEM_ATTR
			ON ITEM_ATTR.INV_ITEM_ID = ITEM_WEB_INFO.INV_ITEM_ID
			AND ITEM_ATTR.SETID = 'SHARE'
	WHERE ITEM_WEB_INFO.INV_ITEM_ID = @itemId
	 

END
GO

GRANT EXECUTE ON Odin_SelectWebsiteItem TO Odin
GO