/*
SELECT * FROM PS_PL_ITEM_ATTRIB ORDER BY INV_ITEM_ID ASC
sp_help PS_PL_ITEM_ATTRIB
*/
DROP PROCEDURE Odin_InsertPlItemAttrib


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE Odin_InsertPlItemAttrib(
	@businessUnit varchar(5),
	@itemId varchar(18)
	)
AS
BEGIN

	SET NOCOUNT ON;
	IF NOT EXISTS (SELECT * FROM PS_PL_ITEM_ATTRIB 
                   WHERE INV_ITEM_ID = @itemId
                   AND BUSINESS_UNIT = @businessUnit
				   )
		   BEGIN
	INSERT INTO PS_PL_ITEM_ATTRIB(
			BUSINESS_UNIT,
			INV_ITEM_ID,
			RESCH_OUT_FACTOR,
			RESCH_IN_FACTOR,
			DEMAND_FENCE_OF,
			PLAN_FENCE_OFF,
			PLAN_HORIZON,
			TRANSFER_MIN_ORDER,
			TRANSFER_MAX_ORDER,
			TRANS_ORD_MULTIPLE,
			TRANSFER_ORD_MOD,
			PUR_MIN_ORDER,
			PUR_MAX_ORDER,
			PUR_ORDER_MULTIPLE,
			PUR_ORDER_MOD,
			MFG_MOD_UNIT,
			MFG_MIN_ORDER,
			MFG_MAX_ORDER,
			MFG_ORDER_MULTIPLE,
			MFG_ORDER_MOD,
			MFG_LEAD_TIME_FLAG,
			SAFETY_LEVEL,
			EXCESS_LEVEL,
			AUTO_APPROVE_MSG,
			PLANNER_CD,
			PURCHASE_YIELD,
			TRANSFER_YIELD,
			SALES_CONSUMP,
			PROD_CONSUMP,
			TRANS_CONSUMP,
			MSR_CONSUMP,
			EXTRA_CONSUMP,
			PL_AGG_DMD_FLAG,
			RELEASED_ORDER,
			FIRMED_ORDER,
			PL_PRIO_FAMILY,
			USE_SHIPTO_LOC,
			PL_FIXED_PERIOD,
			PL_ITEM_EXPL,
			PL_PROJ_USE_DT,
			PLANNED_BY,
			CAP_FENCE_OFF,
			FCST_FULFILL_SIZE,
			FCST_ADJ_ACTION,
			EARLY_FENCE,
			GBL_EARLY_FENCE,
			PL_SEARCH_DEPTH,
			SPOT_BUY_FLG
			)
	VALUES(
	@businessUnit,	--BUSINESS_UNIT,
	@itemId,		--INV_ITEM_ID
	0.00,			--RESCH_OUT_FACTOR
	0.00,			--RESCH_IN_FACTOR
	0.00,			--DEMAND_FENCE_OF
	0.00,			--PLAN_FENCE_OFF
	999.00,			--PLAN_HORIZON
	0.0000,			--TRANSFER_MIN_ORDER
	0.0000,			--TRANSFER_MAX_ORDER
	1.0000,			--TRANS_ORD_MULTIPLE
	'N',			--TRANSFER_ORD_MOD
	0.0000,			--PUR_MIN_ORDER
	0.0000,			--PUR_MAX_ORDER
	1.0000,			--PUR_ORDER_MULTIPLE
	'N',			--PUR_ORDER_MOD
	'',				--MFG_MOD_UNIT
	0.0000,			--MFG_MIN_ORDER
	0.0000,			--MFG_MAX_ORDER
	1.0000,			--MFG_ORDER_MULTIPLE
	'N',			--MFG_ORDER_MOD
	'N',			--MFG_LEAD_TIME_FLAG
	0.0000,			--SAFETY_LEVEL
	0.0000,			--EXCESS_LEVEL
	'',				--AUTO_APPROVE_MSG
	'',				--PLANNER_CD
	100.0,			--PURCHASE_YIELD
	100.0,			--TRANSFER_YIELD
	'N',			--SALES_CONSUMP
	'N',			--PROD_CONSUMP
	'N',			--TRANS_CONSUMP
	'N',			--MSR_CONSUMP
	'N',			--EXTRA_CONSUMP
	'N',			--PL_AGG_DMD_FLAG
	999,			--RELEASED_ORDER
	0,				--FIRMED_ORDER
	'',				--PL_PRIO_FAMILY
	'N',			--USE_SHIPTO_LOC
	0,				--PL_FIXED_PERIOD
	'N',			--PL_ITEM_EXPL
	NULL,			--PL_PROJ_USE_DT
	4,				--PLANNED_BY
	0,				--CAP_FENCE_OFF
	0.0000,			--FCST_FULFILL_SIZE
	1,				--FCST_ADJ_ACTION
	0,				--EARLY_FENCE
	'Y',			--GBL_EARLY_FENCE
	1,				--PL_SEARCH_DEPTH
	'N'				--SPOT_BUY_FLG
	)				

	END
END
GO

GRANT EXECUTE ON Odin_InsertPlItemAttrib TO Odin
GO
