
DROP PROCEDURE Odin_RemoveTestItem
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE Odin_RemoveTestItem
	@itemId varchar(18)=''

AS
BEGIN

	SET NOCOUNT ON;
	
	DELETE FROM Odin.dbo.PS_UOM_TYPE_INV WHERE INV_ITEM_ID = @itemId;
	DELETE FROM Odin.dbo.PS_PV_ITM_CATEGORY WHERE INV_ITEM_ID = @itemId;
	DELETE FROM Odin.dbo.PS_PURCH_ITEM_ATTR WHERE INV_ITEM_ID = @itemId;
	DELETE FROM Odin.dbo.PS_PROD_UOM WHERE PRODUCT_ID = @itemId;
	DELETE FROM Odin.dbo.PS_PROD_PRICE WHERE PRODUCT_ID = @itemId;
	DELETE FROM Odin.dbo.PS_PROD_PRICE_BU WHERE PRODUCT_ID = @itemId;
	DELETE FROM Odin.dbo.PS_PROD_ITEM WHERE PRODUCT_ID = @itemId;
	DELETE FROM Odin.dbo.PS_PROD_PGRP_LNK WHERE PRODUCT_ID = @itemId;
	DELETE FROM Odin.dbo.PS_PL_ITEM_ATTRIB WHERE INV_ITEM_ID = @itemId;
	DELETE FROM Odin.dbo.PS_MASTER_ITEM_TBL WHERE INV_ITEM_ID = @itemId;
	DELETE FROM Odin.dbo.PS_ITEM_WEB_INFO WHERE INV_ITEM_ID = @itemId;
	DELETE FROM Odin.dbo.PS_ITEM_MFG WHERE INV_ITEM_ID = @itemId;
	DELETE FROM Odin.dbo.PS_ITEM_TERRITORY WHERE INV_ITEM_ID = @itemId;
	DELETE FROM Odin.dbo.PS_ITEM_ATTRIB_EX WHERE INV_ITEM_ID = @itemId;
	DELETE FROM Odin.dbo.PS_INV_ITEM_UOM WHERE INV_ITEM_ID = @itemId;
	DELETE FROM Odin.dbo.PS_INV_ITEMS WHERE INV_ITEM_ID = @itemId;
	DELETE FROM Odin.dbo.PS_FXD_BIN_LOC_INV WHERE INV_ITEM_ID = @itemId;
	DELETE FROM Odin.dbo.PS_DEFAULT_LOC_INV WHERE INV_ITEM_ID = @itemId;
	DELETE FROM Odin.dbo.PS_CM_ITEM_METHOD WHERE INV_ITEM_ID = @itemId;
	DELETE FROM Odin.dbo.PS_BU_ITEM_UTIL_CD WHERE INV_ITEM_ID = @itemId;
	DELETE FROM Odin.dbo.PS_BU_ITEMS_INV WHERE INV_ITEM_ID = @itemId;
	DELETE FROM Odin.dbo.PS_BU_ITEMS_CONFIG WHERE INV_ITEM_ID = @itemId;
	DELETE FROM Odin.dbo.PS_ASSET_ITEM_ATTR WHERE INV_ITEM_ID = @itemId;
	DELETE FROM Odin.dbo.PS_AMAZON_ITEM_ATTRIBUTES WHERE INV_ITEM_ID = @itemId;
	DELETE FROM Odin.dbo.ODIN_ITEM_UPDATE_RECORDS WHERE INV_ITEM_ID = @itemId;
	DELETE FROM Odin.dbo.PS_EN_BOM_COMPS WHERE INV_ITEM_ID = @itemId;
	DELETE FROM Odin.dbo.PS_SF_PRDN_AREA_IT WHERE INV_ITEM_ID = @itemId;

END
GO

