
DROP PROCEDURE Odin_SelectItem
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE Odin_SelectItem
	@itemId VARCHAR(18)
AS
BEGIN

	SET NOCOUNT ON;

	SELECT
		   CASEPACK_HEIGHT,
		   CASEPACK_LENGTH,
		   CASEPACK_QTY,
		   CASEPACK_WIDTH,
		   CASEPACK_WEIGHT,
		   CM_GROUP,
		   COUNTRY_IST_ORIGIN,
		   (SELECT CURRENT_COST FROM PS_BU_ITEMS_INV WHERE INV_ITEM_ID=@itemId AND BUSINESS_UNIT='TRCN1') AS DACCAD,
		   (SELECT CURRENT_COST FROM PS_BU_ITEMS_INV WHERE INV_ITEM_ID=@itemId AND BUSINESS_UNIT='TRUS1') AS DACUSD,
		   DESCR60,
		   DIRECT_IMPORT,
		   DUTY,
		   HARMONIZED_CD,
		   INNERPACK_HEIGHT,
		   INNERPACK_LENGTH,
		   INNERPACK_QTY,
		   INNERPACK_WIDTH,
		   INNERPACK_WEIGHT,
		   INV_ITEM_COLOR,
		   INV_ITEM_GROUP,
		   INV_ITEM_HEIGHT,
		   INV_ITEM_LENGTH,
		   INV_ITEM_WEIGHT,
		   INV_ITEM_WIDTH,
		   INV_PROD_FAM_CD,
		   (SELECT ITEM_FIELD_C2 FROM PS_MASTER_ITEM_TBL WHERE INV_ITEM_ID=@itemId) AS PSSTATUS,
		   LICENSE_BEGIN_DATE,
		   (SELECT LIST_PRICE FROM PS_PROD_PRICE WHERE PRODUCT_ID=@itemId AND BUSINESS_UNIT_IN='TRCN1' AND CURRENCY_CD='CAD') AS LISTCN,
		   (SELECT LIST_PRICE FROM PS_PROD_PRICE WHERE PRODUCT_ID=@itemId AND BUSINESS_UNIT_IN='TRUS1' AND CURRENCY_CD='USD') AS LISTUS,
		   (SELECT LIST_PRICE FROM PS_PROD_PRICE WHERE PRODUCT_ID=@itemId AND BUSINESS_UNIT_IN='TRUS1' AND CURRENCY_CD='MXN') AS LISTMX,
		   PROD_FIELD_C10_A,
		   PROD_FIELD_C10_C,
		   PROD_FIELD_C30_A,
		   PROD_FIELD_C30_B,
		   PROD_FIELD_C30_C,
		   PROD_CATEGORY,
		   PROD_FORMAT,
		   PROD_GROUP,
		   (SELECT STOR_LEVEL_1 FROM PS_FXD_BIN_LOC_INV WHERE INV_ITEM_ID=@itemId AND BUSINESS_UNIT='TRCN1') AS FPLCANL1,
		   (SELECT STOR_LEVEL_1 FROM PS_FXD_BIN_LOC_INV WHERE INV_ITEM_ID=@itemId AND BUSINESS_UNIT='TRUS1') AS FPLUSL1,
		   (SELECT PRODUCT_GROUP FROM PS_PROD_PGRP_LNK WHERE PRODUCT_ID = @itemId AND PROD_GRP_TYPE='ACCT') AS ACCT_GRP,
		   (SELECT PRODUCT_GROUP FROM PS_PROD_PGRP_LNK WHERE PRODUCT_ID = @itemId AND PROD_GRP_TYPE='PRC') AS PRC_GRP,
		   PROD_LINE,
		   PRICE_LIST,
		   (SELECT SOURCE_CODE FROM PS_BU_ITEMS_INV WHERE INV_ITEM_ID=@itemId AND BUSINESS_UNIT='TRUS1') AS MFG_SOURCE,
		   UPC_ID,
		   LANGUAGE,
		   IN_STOCK_DATE,
		   ITEM_KEYWORDS,
		   TERRITORY,
		   COPYRIGHT,
		   NEWCATEGORY,
		   CATEGORY,
		   NEW_DATE,
		   LICENSE,
		   RELATED_PRODUCTS,
		   ATTRIBUTE_SET,
		   SHORT_DESC,
		   ACTIVE = 0,
		   (SELECT MFG_SUG_RTL_PRC FROM PS_PROD_PRICE WHERE PRODUCT_ID=@itemId AND BUSINESS_UNIT_IN='TRUS1' AND CURRENCY_CD='USD') AS MSRP1,
		   (SELECT MFG_SUG_RTL_PRC FROM PS_PROD_PRICE WHERE PRODUCT_ID=@itemId AND BUSINESS_UNIT_IN='TRUS1' AND CURRENCY_CD='CAD') AS MSRP2,
		   (SELECT MFG_SUG_RTL_PRC FROM PS_PROD_PRICE WHERE PRODUCT_ID=@itemId AND BUSINESS_UNIT_IN='TRUS1' AND CURRENCY_CD='MXN') AS MSRP3,
		   TITLE,
		   META_DESCRIPTION,
		   PROD_QTY

	FROM PS_MASTER_ITEM_TBL MASTER_ITEM_TBL
		 INNER JOIN	PS_INV_ITEMS INV_ITEMS
			ON  INV_ITEMS.SETID = MASTER_ITEM_TBL.SETID
			AND INV_ITEMS.INV_ITEM_ID = MASTER_ITEM_TBL.INV_ITEM_ID
			AND EFFDT = (SELECT MAX(EFFDT)
						 FROM PS_INV_ITEMS
						 WHERE SETID = INV_ITEMS.SETID
						   AND INV_ITEM_ID = INV_ITEMS.INV_ITEM_ID
						   AND EFFDT <= GETDATE())
		 LEFT OUTER JOIN PS_ITEM_ATTRIB_EX ITEM_ATTRIB_EX
			ON  ITEM_ATTRIB_EX.SETID = MASTER_ITEM_TBL.SETID
			AND ITEM_ATTRIB_EX.INV_ITEM_ID = MASTER_ITEM_TBL.INV_ITEM_ID
		 INNER JOIN PS_PROD_ITEM PROD_ITEM
			ON PROD_ITEM.INV_ITEM_ID = MASTER_ITEM_TBL.INV_ITEM_ID
		 INNER JOIN PS_BU_ITEMS_INV BU_ITEMS_INV
			ON BU_ITEMS_INV.INV_ITEM_ID = MASTER_ITEM_TBL.INV_ITEM_ID
		 LEFT JOIN PS_ITEM_WEB_INFO ITEM_WEB_INFO
			ON ITEM_WEB_INFO.INV_ITEM_ID = MASTER_ITEM_TBL.INV_ITEM_ID
		 LEFT JOIN PS_PROD_PGRP_LNK PROD_PGRP_LNK
			ON PROD_PGRP_LNK.PRODUCT_ID = MASTER_ITEM_TBL.INV_ITEM_ID
		 LEFT JOIN PS_PURCH_ITEM_ATTR PURCH_ITEM_ATTR
			ON PURCH_ITEM_ATTR.INV_ITEM_ID = MASTER_ITEM_TBL.INV_ITEM_ID
		 LEFT JOIN PS_FXD_BIN_LOC_INV FXD_BIN_LOC_INV
			ON FXD_BIN_LOC_INV.INV_ITEM_ID = MASTER_ITEM_TBL.INV_ITEM_ID


	WHERE MASTER_ITEM_TBL.SETID = 'SHARE'
	  AND MASTER_ITEM_TBL.INV_ITEM_ID = @itemId
	 

END
GO

GRANT EXECUTE ON Odin_SelectItem TO Odin
GO