/*
SELECT * FROM ODIN_ITEM_UPDATE_RECORDS
ALTER TABLE ODIN_ITEM_UPDATE_RECORDS ADD SELL_ON_WEB VARCHAR(1)
ALTER TABLE ODIN_ITEM_UPDATE_RECORDS ADD SELL_ON_TARGET VARCHAR(1)
ALTER TABLE ODIN_ITEM_UPDATE_RECORDS ADD SELL_ON_HAYNEEDLE VARCHAR(1)
ALTER TABLE ODIN_ITEM_UPDATE_RECORDS ADD SAT_CODE VARCHAR(20)
sp_help ODIN_ITEM_UPDATE_RECORDS
*/
DROP PROCEDURE Odin_InsertOdinUpdateRecords


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE Odin_InsertOdinUpdateRecords(
    @itemId VARCHAR(18) = '',
    @itemInputStatus VARCHAR(18) = '',
    @userName VARCHAR(18) = '',
    @accountingGroup VARCHAR(10) = '',
	@altImageFile1 VARCHAR(254) = '',
	@altImageFile2 VARCHAR(254) = '',
	@altImageFile3 VARCHAR(254) = '',
	@altImageFile4 VARCHAR(254) = '',
    @casepackHeight VARCHAR(6) = '',
    @casepackLength VARCHAR(6) = '',
    @casepackQty VARCHAR(2) = '',
	@casepackUpc VARCHAR(12) = '',
    @casepackWidth VARCHAR(6) = '',
    @casepackWeight VARCHAR(6) = '',
    @category VARCHAR(MAX)  = '',
    @category2 VARCHAR(MAX)  = '',
    @category3 VARCHAR(MAX)  = '',
    @color VARCHAR(10) = '',
    @copyright VARCHAR(MAX) = '',
    @countryOfOrigin VARCHAR(3) = '',
    @costProfileGroup VARCHAR(18) = '',
    @dacusd VARCHAR(10) = '',
    @daccad VARCHAR(10) = '',
    @description VARCHAR(MAX) = '',
    @directImport VARCHAR(1) = '',
    @duty VARCHAR(30) = '',
    @ean VARCHAR(30) = '',
    @fplcanl1 VARCHAR(4) = '',
    @fplusl1 VARCHAR(4) = '',
	@gpc VARCHAR(10) = '',
	@height VARCHAR(12) = '',	
	@imagePath VARCHAR (255) = '',
    @innerpackHeight VARCHAR(6) = '',
    @innerpackLength VARCHAR(6) = '',
    @innerpackQty VARCHAR(2) = '',
	@innerpackUpc VARCHAR(12) = '',
    @innerpackWidth VARCHAR(6) = '',
    @innerpackWeight VARCHAR(6) = '',
    @inStockDate VARCHAR(30) = '',
    @isbn VARCHAR(10) = '',
    @itemCategory VARCHAR(60) = '',
    @itemFamily VARCHAR(10) = '',
	@itemGroup VARCHAR(15) = '',
    @itemKeywords VARCHAR(MAX) = '',
    @language VARCHAR(18) = '',
	@length VARCHAR(12) = '',
    @license VARCHAR(255) = '',
    @licenseBeginDate VARCHAR(30) = '',
    @listPriceCad VARCHAR(16) = '',
    @listPriceUsd VARCHAR(16) = '',
    @listPriceMxn VARCHAR(16) = '',
    @metaDescription VARCHAR(255) = '',
    @mfgSource VARCHAR(2) = '',
    @msrp VARCHAR(10) = '',
    @msrpCad VARCHAR(15) = '',
    @msrpMxn VARCHAR(15) = '',
    @productFormat VARCHAR(60) = '',
    @productGroup VARCHAR(30) = '',
    @productIdTranslation VARCHAR(100) = '',
    @productLine VARCHAR(30) = '',
    @productQty VARCHAR(266) = '',
    @pricingGroup VARCHAR(10) = '',
    @printOnDemand VARCHAR(1) = '',
	@psStatus VARCHAR(2) = '',
	@property VARCHAR(MAX) = '',	
	@satCode VARCHAR(20) = '',	
    @sellOnFanatics VARCHAR(1) = '',
    @sellOnHayneedle VARCHAR(1) = '',
    @sellOnJet VARCHAR(1) = '',
    @sellOnTarget VARCHAR(1) = '',
    @sellOnWeb VARCHAR(1) = '',
    @sellOnWalmart VARCHAR(1) = '',
    @sellOnWayfair VARCHAR(1) = '',
    @shortDesc VARCHAR(MAX) = '',
    @size VARCHAR(266) = '',
    @standardCost VARCHAR(15) = '',
    @statsCode VARCHAR(30) = '',
    @tariffCode VARCHAR(14) = '',
    @territory VARCHAR(18) = '',
    @title VARCHAR(266) = '',
    @udex VARCHAR(30) = '',
    @upc VARCHAR(18) = '',
	@weight VARCHAR(12) = '',
	@width VARCHAR(12) = '',
    @a_AmazonActive VARCHAR(1) = '',
	@a_Asin VARCHAR(10) = '',
	@a_Bullet1 VARCHAR(254) = '',
	@a_Bullet2 VARCHAR(254) = '',
	@a_Bullet3 VARCHAR(254) = '',
	@a_Bullet4 VARCHAR(254) = '',
	@a_Bullet5 VARCHAR(254) = '',
	@a_Components VARCHAR(100) = '',
	@a_Cost VARCHAR(10) = '',
	@a_ExternalIdType VARCHAR(20) = '',
	@a_ExternalId VARCHAR(20) = '',
	@a_ImageUrl1 VARCHAR(254) = '',
	@a_ImageUrl2 VARCHAR(254) = '',
	@a_ImageUrl3 VARCHAR(254) = '',
	@a_ImageUrl4 VARCHAR(254) = '',
	@a_ImageUrl5 VARCHAR(254) = '',
	@a_ItemHeight VARCHAR(12) = '',
	@a_ItemLength VARCHAR(12) = '',
	@a_ItemName VARCHAR(254) = '',
	@a_ItemWeight VARCHAR(12) = '',
	@a_ItemWidth VARCHAR(12) = '',
	@a_ModelName VARCHAR(50) = '',
	@a_PackageLength VARCHAR(12) = '',
	@a_PackageHeight VARCHAR(12) = '',
	@a_PackageWidth VARCHAR(12) = '',
	@a_PackageWeight VARCHAR(12) = '',
	@a_PageQty VARCHAR(4) = '',
	@a_ProductCategory VARCHAR(50) = '',
	@a_ProductDescription VARCHAR(8000) = '',
	@a_ProductSubcategory VARCHAR(50) = '',
	@a_ManufacturerName VARCHAR(100) = '',
	@a_Msrp VARCHAR(10) = '',
	@a_SearchTerms VARCHAR(500) = '',
	@a_Size VARCHAR(254) = '',
	@a_Upc VARCHAR(12) = ''
	)
AS
BEGIN

	SET NOCOUNT ON;
	INSERT INTO ODIN_ITEM_UPDATE_RECORDS(
    INV_ITEM_ID,
    ITEM_INPUT_STATUS,
    INPUT_DATE,
    USERNAME,
    ACCOUNTING_GROUP,
	ALT_IMAGE_FILE_1,
	ALT_IMAGE_FILE_2,
	ALT_IMAGE_FILE_3,
	ALT_IMAGE_FILE_4,
    CASEPACK_HEIGHT,
    CASEPACK_LENGTH,
    CASEPACK_QTY,
    CASEPACK_UPC,
    CASEPACK_WIDTH,
    CASEPACK_WEIGHT,
    CATEGORY,
    CATEGORY2,
    CATEGORY3,
    COLOR,
    COPYRIGHT,
    COUNTRY_OF_ORIGIN,
    COST_PROFILE_GROUP,
    DEFAULT_ACTUAL_COST_USD,
    DEFAULT_ACTUAL_COST_CAD,
    [DESCRIPTION],
    DIRECT_IMPORT,
    DUTY,
    EAN,
    FPLCANL1,
    FPLUSL1,
    GPC,
    HEIGHT, 
	IMAGE_PATH,
    INNERPACK_HEIGHT,
    INNERPACK_LENGTH,
    INNERPACK_QTY,
    INNERPACK_UPC,
    INNERPACK_WIDTH,
    INNERPACK_WEIGHT,
    IN_STOCK_DATE,
    ISBN,
    ITEM_CATEGORY,
    ITEM_FAMILY,
    ITEM_GROUP,
    ITEM_KEYWORDS,
    [LANGUAGE],
    [LENGTH],
    LICENSE,
    LICENSE_BEGIN_DATE,
    LIST_PRICE_CAD,
    LIST_PRICE_USD,
    LIST_PRICE_MXN,
    META_DESCRIPTION,
    MFG_SOURCE,
    MSRP,
    MSRP_CAD,
    MSRP_MXN,
    PRODUCT_FORMAT,
    PRODUCT_GROUP,
	PRODUCT_ID_TRANSLATION,
    PRODUCT_LINE,
    PROD_QTY,
    PRICING_GROUP,
    PRINT_ON_DEMAND,
    PS_STATUS,
    PROPERTY,
	SAT_CODE,
	SELL_ON_FANATICS,
	SELL_ON_HAYNEEDLE,
	SELL_ON_JET,
	SELL_ON_TARGET,
	SELL_ON_WEB,
	SELL_ON_WALMART,
	SELL_ON_WAYFAIR,
    SHORT_DESC,
    SIZE,
    STANDARD_COST,
    STATS_CODE,
    TARIFF_CODE,
    TERRITORY,
    TITLE,
    UDEX,
    UPC,
    [WEIGHT],
    WIDTH,
    A_AMAZON_ACTIVE,
	A_ASIN,
    A_BULLET_1,
    A_BULLET_2,
    A_BULLET_3,
    A_BULLET_4,
    A_BULLET_5,
    A_COMPONENTS,
    A_COST,
    A_EXTERNAL_ID_TYPE,
    A_EXTERNAL_ID,
    A_IMAGE_URL_1,
    A_IMAGE_URL_2,
    A_IMAGE_URL_3,
    A_IMAGE_URL_4,
    A_IMAGE_URL_5,
    A_ITEM_HEIGHT,
    A_ITEM_LENGTH,
    A_ITEM_NAME,
    A_ITEM_WEIGHT,
    A_ITEM_WIDTH,
    A_MODEL_NAME,
    A_PACKAGE_LENGTH,
    A_PACKAGE_HEIGHT,
    A_PACKAGE_WIDTH,
    A_PACKAGE_WEIGHT,
    PAGE_COUNT,
    A_PRODUCT_CATEGORY,
    A_PRODUCT_DESCRIPTION,
    A_PRODUCT_SUBCATEGORY,
    A_MANUFACTURER_NAME,
    A_MSRP,
    A_SEARCH_TERMS,
    A_SIZE,
	A_UPC
			)
	VALUES(
    @itemId,
    @itemInputStatus,
	GETDATE(),
    @userName,
    @accountingGroup,
	@altImageFile1,
	@altImageFile2,
	@altImageFile3,
	@altImageFile4,
    @casepackHeight,
    @casepackLength,
    @casepackQty,
	@casepackUpc,
    @casepackWidth,
    @casepackWeight,
    @category,
    @category2,
    @category3,
    @color,
    @copyright,
    @countryOfOrigin,
    @costProfileGroup,
    @dacusd,
    @daccad,
    @description,
    @directImport,
    @duty,
    @ean,
    @fplcanl1,
    @fplusl1,
	@gpc,
	@height,	
	@imagePath,
    @innerpackHeight,
    @innerpackLength,
    @innerpackQty,
	@innerpackUpc,
    @innerpackWidth,
    @innerpackWeight,
    @inStockDate ,
    @isbn,
    @itemCategory,
    @itemFamily,
	@itemGroup,
    @itemKeywords,
    @language,
	@length,
    @license,
    @licenseBeginDate ,
    @listPriceCad,
    @listPriceUsd,
    @listPriceMxn,
    @metaDescription,
    @mfgSource,
    @msrp,
    @msrpCad,
    @msrpMxn,
    @productFormat,
    @productGroup,
	@productIdTranslation,
    @productLine,
    @productQty,
    @pricingGroup,
    @printOnDemand,
	@psStatus,
	@property,
	@satCode,
	@sellOnFanatics,
	@sellOnHayneedle,
	@sellOnJet,
	@sellOnTarget,
	@sellOnWeb,
	@sellOnWalmart,
	@sellOnWayfair,
    @shortDesc,
    @size,
    @standardCost,
    @statsCode,
    @tariffCode,
    @territory,
    @title,
    @udex,
    @upc,
	@weight,
	@width,
	@a_AmazonActive,
	@a_Asin,
	@a_Bullet1,
	@a_Bullet2,
	@a_Bullet3,
	@a_Bullet4,
	@a_Bullet5,
	@a_Components,
	@a_Cost,
	@a_ExternalIdType,
	@a_ExternalId,
	@a_ImageUrl1,
	@a_ImageUrl2,
	@a_ImageUrl3,
	@a_ImageUrl4,
	@a_ImageUrl5,
	@a_ItemHeight,
	@a_ItemLength,
	@a_ItemName,
	@a_ItemWeight,
	@a_ItemWidth,
	@a_ModelName,
	@a_PackageLength,
	@a_PackageHeight,
	@a_PackageWidth,
	@a_PackageWeight,
	@a_PageQty,
	@a_ProductCategory,
	@a_ProductDescription,
	@a_ProductSubcategory,
	@a_ManufacturerName,
	@a_Msrp,
	@a_SearchTerms,
	@a_Size,
	@a_Upc
	)				
END
GO

GRANT EXECUTE ON Odin_InsertOdinUpdateRecords TO Odin
GO

