GRANT SELECT, INSERT, UPDATE ON PS_AMAZON_ITEM_ATTRIBUTES TO Odin
GRANT SELECT, INSERT, UPDATE ON PS_ASSET_ITEM_ATTR TO Odin
GRANT SELECT, INSERT, UPDATE ON PS_BU_ITEMS_CONFIG TO Odin
GRANT SELECT, INSERT, UPDATE ON PS_BU_ITEMS_INV TO Odin
GRANT SELECT, INSERT, UPDATE ON PS_BU_ITEM_UTIL_CD TO Odin
GRANT SELECT, INSERT, UPDATE ON PS_CM_GROUP_DEFN TO Odin
GRANT SELECT, INSERT, UPDATE ON PS_CM_ITEM_METHOD TO Odin
GRANT SELECT, INSERT, UPDATE ON PS_COUNTRY_TBL TO Odin
GRANT SELECT, INSERT, UPDATE ON PS_CUSTOMER_PRODUCT_ATTRIBUTES TO Odin
GRANT SELECT, INSERT, UPDATE ON PS_DEFAULT_LOC_INV TO Odin
GRANT SELECT, INSERT, UPDATE, DELETE ON PS_EN_BOM_COMPS TO Odin
GRANT SELECT, INSERT, UPDATE ON PS_EN_BOM_HEADER TO Odin
GRANT SELECT, INSERT, UPDATE, DELETE ON PS_FXD_BIN_LOC_INV TO Odin
GRANT SELECT, INSERT, UPDATE ON PS_HRMN_TARIFF_CD TO Odin
GRANT SELECT, INSERT, UPDATE ON PS_INV_ITEM_FAM TO Odin
GRANT SELECT, INSERT, UPDATE ON PS_INV_ITEM_GROUP TO Odin
GRANT SELECT, INSERT, UPDATE ON PS_INV_ITEM_UOM TO Odin
GRANT SELECT, INSERT, UPDATE ON PS_INV_ITEMS TO Odin
GRANT SELECT, INSERT, UPDATE ON PS_ITEM_ATTRIB_EX TO Odin
GRANT SELECT, INSERT, UPDATE ON PS_ITEM_COMPLIANCE TO Odin
GRANT SELECT, INSERT, UPDATE, DELETE ON PS_ITEM_LANGUAGE TO Odin
GRANT SELECT, INSERT, UPDATE ON PS_ITEM_MFG TO Odin
GRANT SELECT ON PS_ITEM_STATUS_TBL TO Odin
GRANT SELECT, INSERT, UPDATE, DELETE ON PS_ITEM_TERRITORY TO Odin
GRANT SELECT, INSERT, UPDATE ON PS_ITEM_WEB_INFO TO Odin
GRANT SELECT, INSERT, UPDATE ON PS_ITM_CAT_TBL TO Odin
GRANT SELECT, INSERT, UPDATE ON PS_LANGUAGE_TBL TO Odin
GRANT SELECT, INSERT, UPDATE, DELETE ON PS_MARKETPLACE_PRODUCT_TRANSLATIONS TO Odin

GRANT SELECT, INSERT, UPDATE ON PS_MASTER_ITEM_TBL TO Odin
GRANT SELECT, INSERT, UPDATE ON PS_PL_ITEM_ATTRIB TO Odin
GRANT SELECT, INSERT, UPDATE ON PS_PROD_CATGRY_TBL TO Odin
GRANT SELECT, INSERT, UPDATE ON PS_PROD_GROUP_TBL TO Odin
GRANT SELECT, INSERT, UPDATE ON PS_PROD_ITEM TO Odin
GRANT SELECT, INSERT, UPDATE, DELETE ON PS_PROD_PGRP_LNK TO Odin
GRANT SELECT, INSERT, UPDATE ON PS_PROD_PRICE TO Odin
GRANT SELECT, INSERT, UPDATE ON PS_PROD_PRICE_BU TO Odin
GRANT SELECT, INSERT, UPDATE ON PS_PRODUCT_FORMATS TO Odin
GRANT SELECT, INSERT, UPDATE ON PS_PRODUCT_GROUPS TO Odin
GRANT SELECT, INSERT, UPDATE ON PS_PRODUCT_LINES TO Odin
GRANT SELECT, INSERT, UPDATE ON PS_PROD_UOM TO Odin
GRANT SELECT, INSERT, UPDATE ON PS_PURCH_ITEM_ATTR TO Odin
GRANT SELECT, INSERT, UPDATE ON PS_PURCH_ITEM_BU TO Odin
GRANT SELECT, INSERT, UPDATE, DELETE ON PS_PV_ITM_CATEGORY TO Odin
GRANT SELECT, INSERT, UPDATE, DELETE ON PS_SF_PRDN_AREA_IT TO Odin
GRANT SELECT, INSERT, UPDATE, DELETE ON PS_UOM_TYPE_INV TO Odin
GRANT SELECT, INSERT, UPDATE, DELETE ON PS_MARKETPLACE_PRODUCT_TRANSLATIONS TO Odin
GRANT SELECT, INSERT, UPDATE ON ODIN_CUSTOMER_CONVERSION TO Odin
GRANT SELECT, INSERT, UPDATE, DELETE ON Odin_GlobalKeys TO Odin
GRANT SELECT, INSERT, UPDATE, DELETE ON ODIN_EXCEL_LAYOUT_DATA TO Odin
GRANT SELECT, INSERT, UPDATE, DELETE ON ODIN_EXCEL_LAYOUT_IDS TO Odin
GRANT SELECT, INSERT, UPDATE, DELETE ON ODIN_FIELD_VALUES TO Odin
GRANT SELECT, INSERT, UPDATE, DELETE ON ODIN_ITEM_TEMPLATES TO Odin
GRANT SELECT, INSERT, UPDATE, DELETE ON ODIN_EXCEL_LAYOUT_IDS TO Odin
GRANT SELECT, INSERT ON ODIN_ITEM_UPDATE_RECORDS TO Odin
GRANT SELECT, INSERT, UPDATE ON ODIN_LANGUAGES TO Odin
GRANT SELECT, INSERT, UPDATE, DELETE ON Odin_MetaDescription TO Odin 
GRANT SELECT, INSERT, UPDATE, DELETE ON Odin_NewWebCategories TO Odin   
GRANT SELECT ON ODIN_NOTIFICATIONS TO Odin
GRANT SELECT, INSERT, UPDATE, DELETE ON ODIN_OPTIONS_TABLE TO Odin
GRANT SELECT, INSERT, UPDATE ON Odin_RequestComments TO Odin
GRANT SELECT, INSERT, UPDATE ON Odin_RolePermissions TO Odin
GRANT SELECT, INSERT, UPDATE ON ODIN_SPECIAL_CHARS TO Odin
GRANT SELECT, INSERT, UPDATE ON ODIN_TERRITORIES TO Odin
GRANT SELECT, INSERT, UPDATE ON ODIN_TOOL_TIPS TO Odin
GRANT SELECT, INSERT, UPDATE ON Odin_UserRoles TO Odin
GRANT SELECT, INSERT, UPDATE, DELETE ON Odin_LicenseStats TO Odin
GRANT SELECT, INSERT, UPDATE, DELETE ON Odin_Web_License TO Odin
GRANT SELECT, INSERT, UPDATE ON Odin_WebsiteItemRequests TO Odin
GRANT SELECT, INSERT, UPDATE, DELETE ON Odin_WebCategories TO Odin
GRANT SELECT, INSERT, UPDATE ON Odin_Web_Languages TO Odin
GRANT SELECT, INSERT, UPDATE, DELETE ON Odin_Web_Territories TO Odin
GRANT SELECT, INSERT, UPDATE ON Odin_Item_Exceptions TO Odin
GRANT SELECT, INSERT, UPDATE ON ODIN_USER_ROLES TO Odin
GRANT SELECT, INSERT, UPDATE ON ODIN_ROLE_PERMISSIONS TO Odin
GRANT SELECT ON ODIN_ITEM_VW TO Odin
GRANT SELECT ON PS_ORD_LINE TO Odin
GRANT SELECT, INSERT, UPDATE, DELETE ON Odin_AutoNumberControlTable TO Odin