SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ODIN_ITEMID_SUFFIXES]
(  
    [FIELD_VALUE] VARCHAR(12),
	[DESC] VARCHAR(250)
)
GO

SET ANSI_PADDING OFF
GO

/*
SELECT * FROM ODIN_ITEMID_SUFFIXES
INSERT INTO [ODIN_ITEMID_SUFFIXES] VALUES ('WM', 'Walmart')
INSERT INTO [ODIN_ITEMID_SUFFIXES] VALUES ('MI', 'Michaels')
INSERT INTO [ODIN_ITEMID_SUFFIXES] VALUES ('TG', 'Target')
INSERT INTO [ODIN_ITEMID_SUFFIXES] VALUES ('DI', 'Direct Import')
INSERT INTO [ODIN_ITEMID_SUFFIXES] VALUES ('DG', 'Dollar General')
*/
