/* SELECT * FROM Odin_MetaDescription */
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Odin_MetaDescription](
	[ID] INT IDENTITY(1,1),
	[META_DESCRIPTION] [varchar](255) NOT NULL
)

GO

SET ANSI_PADDING OFF
GO

INSERT INTO [Odin_MetaDescription](META_DESCRIPTION)
Values
('Stationery Display'),
('Premier Bookmarks'),
('NoteMarks'),
('Standard Bookmarks'),
('ShapeMarks'),
('Page Clips'),
('3-D Bookmark'),
('Collector''s Beaded Bookmark'),
('Art Calendar'),
('Collector''s Edition'),
('Day-at-a-Time Box'),
('Deluxe'),
('Engagement Planner'),
('Family Calendar'),
('Message Board'),
('Mini'),
('Oversized'),
('Pocket Planner'),
('Pocket Planner & Pen'),
('Standee'),
('Sticker Wall'),
('Wall'),
('Weekly Calendar & Pen'),
('Displays'),
('Coloring Book 8" x 10"'),
('Coloring Pad 11" x 17"'),
('Mini Coloring Pad 6" x 12"'),
('Coloring Poster 18" x 24"'),
('Gift Bags'),
('Gift Wrap'),
('3-D Prints'),
('Accessories'),
('Mounted Prints'),
('Poster Books'),
('24" x 36" Prints'),
('Black Light'),
('Collectors Edition'),
('Door-Sized'),
('Murals'),
('Wall Posters'),
('Pre-Packs'),
('SceneMaker'),
('4 Color Decals'),
('6" x 14.25" Decals'),
('Poster Decals - 24" x 36"'),
('One Color Decals'),
('RoomScapes Poster Decal - 18" x 24"'),
('Badges - 6 Sheet'),
('Designer Labels'),
('Iron-On Labels'),
('Mega Stickerland Reward Pad'),
('Peel & Stick Labels'),
('Reward Pads - 12 Page'),
('Reward Stickers'),
('Bitty Bits'),
('Dimensional'),
('Foldover'),
('Grab and Go'),
('Grab and Go Delux'),
('Mini Foldover'),
('My Bands - Sticker Bracelets'),
('My Big Box of Stickers'),
('My Sticker Activity Kit'),
('Pop Up Stickers - 2 Sheet'),
('Slim Stickers'),
('Standard Sticker - 4 Sheet'),
('Standard Value Dimensional'),
('Sticker Boxes - 8pk'),
('Sticker Flip Packs'),
('Sticker Party Pack'),
('Sticker Play Pack'),
('Sticker Travel Book'),
('Stickerland Pads'),
('Stickers by the Roll'),
('1/2" DieCut Tape'),
('1/2" Glitter Tape'),
('1/2" Foil Tape'),
('1/2" Lace Tape'),
('1/2" Washi Tape'),
('3" Accent Tape'),
('1" Marking Tape'),
('3 Pack Paper Tape'),
('Glitter Tattoos'),
('Henna Tattoos'),
('Metallic + 4c Tattoos - 55ct'),
('Metallic Tattoos - 55ct'),
('Mini Tattoo Bag - 25ct'),
('Standard Tattoo Bag - 75ct'),
('Tattoo Kit'),
('Ballpoint Pen + Notepad Pack'),
('Colored Gel Pens - 5 pk'),
('Colored Mechanical Pencils 5pk'),
('Gel Pen - 2pk'),
('Gel Pen + Bookmark Packs'),
('Mini Gel Pens - 3pk'),
('Premium Ballpoint Pen'),
('Projector Pen'),
('Stick Pens - 4pk'),
('Stylus Pen - 1pk'),
('12" x 12" Albums'),
('Page Protectors'),
('8" x 8" Scrapbook Album'),
('Borders'),
('Chipboard Medley'),
('Decoration Medley'),
('Stickers'),
('Craft Sticker Flip Packs'),
('Scrapbook Sticker Multi Pack'),
('Tall Stickers'),
('Tall Dimensional Stickers'),
('Papers'),
('12" x 12" Papers'),
('Mega Paper Pad'),
('Page Kits'),
('Paper Packs'),
('Theme Packs')
