
/****** Object:  Table [dbo].[Odin_Item_Exceptions]    Script Date: 11/25/2013 2:16:58 PM ******/
/*
DROP TABLE Odin_Item_Exceptions
SELECT * FROM Odin_Item_Exceptions
*/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE Odin_Item_Exceptions(
	FIELD varchar(MAX) NULL,
	EXCEPTION_TRIGGER varchar(MAX) NULL,
	EXCEPTION_VALUE varchar(MAX) NULL,
	EXCEPTION_RESULT varchar (MAX) NULL
)
INSERT INTO Odin_Item_Exceptions(FIELD, EXCEPTION_TRIGGER, EXCEPTION_VALUE, EXCEPTION_RESULT) 
VALUES ('UPC','PRODUCT_FORMAT','Black Light SP','EMPTY UPC'),
		('UPC','PRODUCT_FORMAT','Collector''s Edition SP','EMPTY UPC'),
		('UPC','PRODUCT_FORMAT','Door SP','EMPTY UPC'),
		('UPC','PRODUCT_FORMAT','Mural SP','EMPTY UPC'),
		('UPC','PRODUCT_FORMAT','Purchased SP','EMPTY UPC'),
		('UPC','PRODUCT_FORMAT','Wall SP','EMPTY UPC'),
		('UPC','PRODUCT_FORMAT','16x20 100#','EMPTY UPC'),
		('UPC','PRODUCT_FORMAT','Custom','EMPTY UPC'),
		('UPC','PRODUCT_FORMAT','18x24 NO BC','EMPTY UPC')
GO

SET ANSI_PADDING OFF
GO