
/****** Object:  Table [dbo].[PS_INV_ITEMS]    Script Date: 11/25/2013 2:16:58 PM ******/
/*
DROP TABLE Odin_Web_License
SELECT * FROM Odin_Web_License
*/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE Odin_Web_License(
	LICENSE varchar(MAX) NULL,
	PROPERTY varchar(MAX) NULL
)
INSERT INTO Odin_Web_License(LICENSE, PROPERTY) 
VALUES 
('Angry Birds',	'Angry Birds'),
('Angry Birds',	'Angry Birds Space'),
('Angry Birds',	'The Angry Birds Movie'),
('Call of Duty',	'Call of Duty: Advanced Warfare'),
('Call of Duty',	'Call of Duty: Black Ops 3'),
('DC Comics',	'Batgirl'),
('DC Comics',	'Batman'),
('DC Comics',	'Batman v Superman: Dawn of Justice'),
('DC Comics',	'DC Comics'),
('DC Comics',	'DC Superhero Girls'),
('DC Comics',	'Gotham'),
('DC Comics',	'Harley Quinn'),
('DC Comics',	'Nightwing'),
('DC Comics',	'Suicide Squad'),
('DC Comics',	'Supergirl'),
('DC Comics',	'Superman'),
('DC Comics',	'Teen Titans'),
('DC Comics',	'The Flash'),
('DC Comics',	'The Green Arrow'),
('DC Comics',	'The Green Lantern'),
('DC Comics',	'The Joker'),
('DC Comics',	'The Justice League'),
('DC Comics',	'Wonder Woman'),
('Despicable Me',	'Despicable Me'),
('Despicable Me',	'Despicable Me 2'),
('Despicable Me',	'Minions'),
('Disney',	'Alice in Wonderland'),
('Disney',	'Alice Through the Looking Glass'),
('Disney',	'Big Hero 6'),
('Disney',	'Cars'),
('Disney',	'Descendants'),
('Disney',	'Disney Fairies'),
('Disney',	'Disney Planes'),
('Disney',	'Disney Princess'),
('Disney',	'Disney Tsum Tsum'),
('Disney',	'Disney Villains'),
('Disney',	'Doc McStuffins'),
('Disney',	'Finding Nemo'),
('Disney',	'Frozen'),
('Disney',	'Gravity Falls'),
('Disney',	'Hannah Montana'),
('Disney',	'Inside Out'),
('Disney',	'Jake & the Neverland Pirates'),
('Disney',	'Mickey Mouse'),
('Disney',	'Miles From Tomorrowland'),
('Disney',	'Minnie Mouse'),
('Disney',	'Monsters University'),
('Disney',	'Palace Pets'),
('Disney',	'Peter Pan'),
('Disney',	'Phineas & Ferb'),
('Disney',	'Pinocchio'),
('Disney',	'Princess & the Frog'),
('Disney',	'Sheriff Callie'),
('Disney',	'Snow White'),
('Disney',	'Sofia the First'),
('Disney',	'Star Darlings'),
('Disney',	'Teen Beach Movie 2'),
('Disney',	'The Aristocats'),
('Disney',	'The Good Dinosaur'),
('Disney',	'The Jungle Book'),
('Disney',	'The Lion King'),
('Disney',	'The Muppets'),
('Disney',	'The Nightmare Before Christmas'),
('Disney',	'Tinker Bell'),
('Disney',	'Toy Story'),
('Disney',	'Winnie The Pooh'),
('Disney',	'Zootopia'),
('Dragon Ball Z',	'Resurrection F'),
('Fall Out',	'Fall Out'),
('Fall Out',	'Fall Out 4'),
('Halo',	'Halo '),
('Halo',	'Halo 5'),
('Marvel',	'Ant-Man'),
('Marvel',	'Captain America'),
('Marvel',	'Captain America: Civil War'),
('Marvel',	'Captain Marvel'),
('Marvel',	'Daredevil'),
('Marvel',	'Deadpool'),
('Marvel',	'Dr. Strange'),
('Marvel',	'Gaurdians of the Galaxy'),
('Marvel',	'Iron Man'),
('Marvel',	'Marvel Universe'),
('Marvel',	'Spider-Gwen'),
('Marvel',	'Spider-Man'),
('Marvel',	'The Avengers'),
('Marvel',	'The Avengers: Age of Ultron'),
('Marvel',	'The Hulk'),
('Marvel',	'The Punisher'),
('Marvel',	'Thor'),
('Marvel',	'Wolverine'),
('Marvel',	'X-Men'),
('MLB',	'Arizona Diamondbacks®'),
('MLB',	'Atlanta Braves™'),
('MLB',	'Baltimore Orioles®'),
('MLB',	'Boston Red Sox®'),
('MLB',	'Chicago Cubs®'),
('MLB',	'Chicago White Sox®'),
('MLB',	'Cincinnati Reds™'),
('MLB',	'Cleveland Indians®'),
('MLB',	'Colorado Rockies®'),
('MLB',	'Detroit Tigers®'),
('MLB',	'Houston Astros™'),
('MLB',	'Houston Astros™'),
('MLB',	'Kansas City Royals™'),
('MLB',	'Los Angeles Angels™'),
('MLB',	'Los Angeles Dodgers®'),
('MLB',	'Miami Marlins®'),
('MLB',	'Milwaukee Brewers®'),
('MLB',	'Minnesota Twins™'),
('MLB',	'MLB'),
('MLB',	'New York Mets®'),
('MLB',	'New York Yankees®'),
('MLB',	'Oakland Athletics™'),
('MLB',	'Philadelphia Phillies®'),
('MLB',	'Pittsburgh Pirates®'),
('MLB',	'San Francisco Giants®'),
('MLB',	'Seattle Mariners®'),
('MLB',	'St. Louis Cardinals®'),
('MLB',	'Tampa Bay Rays™'),
('MLB',	'Texas Rangers® '),
('MLB',	'Toronto Blue Jays®'),
('MLB',	'Washington Nationals®'),
('NBA',	'Atlanta Hawks'),
('NBA',	'Boston Celtics'),
('NBA',	'Brooklyn Nets'),
('NBA',	'Charlotte Hornets'),
('NBA',	'Chicago Bulls'),
('NBA',	'Cleveland Cavaliers'),
('NBA',	'Dallas Mavericks'),
('NBA',	'Denver Nuggets'),
('NBA',	'Detroit Pistons'),
('NBA',	'Golden State Warriors'),
('NBA',	'Houston Rockets'),
('NBA',	'Indiana Pacers'),
('NBA',	'Los Angeles Clippers'),
('NBA',	'Los Angeles Lakers'),
('NBA',	'Memphis Grizzlies'),
('NBA',	'Miami Heat'),
('NBA',	'Milwaukee Bucks'),
('NBA',	'Minnesota Timberwolves'),
('NBA',	'NBA'),
('NBA',	'Logos'),
('NBA',	'New Orleans Pelicans'),
('NBA',	'New York Knicks'),
('NBA',	'Oklahoma City Thunder'),
('NBA',	'Orlando Magic'),
('NBA',	'Philadelphia 76ers'),
('NBA',	'Phoenix Suns'),
('NBA',	'Portland Trail Blazers'),
('NBA',	'San Antonio Spurs'),
('NBA',	'Toronto Raptors'),
('NBA',	'Utah Jazz'),
('NBA',	'Washington Wizards'),
('NFL',	'Arizona Cardinals'),
('NFL',	'Atlanta Falcons'),
('NFL',	'Baltimore Ravens'),
('NFL',	'Buffalo Bills'),
('NFL',	'Carolina Panthers'),
('NFL',	'Chicago Bears'),
('NFL',	'Cincinnati Bengals'),
('NFL',	'Cleveland Browns'),
('NFL',	'Dallas Cowboys'),
('NFL',	'Denver Broncos'),
('NFL',	'Detroit Lions'),
('NFL',	'Green Bay Packers'),
('NFL',	'Houston Texans'),
('NFL',	'Indianapolis Colts'),
('NFL',	'Jacksonville Jaguars'),
('NFL',	'Kansas City Chiefs'),
('NFL',	'Los Angeles Rams'),
('NFL',	'Miami Dolphins'),
('NFL',	'Minnesota Vikings'),
('NFL',	'New England Patriots'),
('NFL',	'New Orleans Saints'),
('NFL',	'New York Giants'),
('NFL',	'New York Jets'),
('NFL',	'NFL'),
('NFL',	'Oakland Raiders'),
('NFL',	'Philadelphia Eagles'),
('NFL',	'Pittsburgh Steelers'),
('NFL',	'San Diego Chargers'),
('NFL',	'San Francisco 49ers'),
('NFL',	'Seattle Seahawks'),
('NFL',	'Tampa Bay Buccaneers'),
('NFL',	'Tennessee Titans'),
('NFL',	'Washington Redskins'),
('NHL',	'Anaheim Ducks®'),
('NHL',	'Arizona Coyotes®'),
('NHL',	'Boston Bruins®'),
('NHL',	'Buffalo Sabres®'),
('NHL',	'Calgary Flames®'),
('NHL',	'Carolina Hurricanes®'),
('NHL',	'Chicago Blackhawks®'),
('NHL',	'Colorado Avalanche®'),
('NHL',	'Columbus Blue Jackets®'),
('NHL',	'Dallas Stars™ '),
('NHL',	'Detroit Red Wings®'),
('NHL',	'Edmonton Oilers®'),
('NHL',	'Florida Panthers®'),
('NHL',	'Los Angeles Kings®'),
('NHL',	'Minnesota Wild®'),
('NHL',	'Montreal Canadiens®'),
('NHL',	'Nashville Predators®'),
('NHL',	'New Jersey Devils®'),
('NHL',	'New York Islanders®'),
('NHL',	'New York Rangers®'),
('NHL',	'NHL'),
('NHL',	'Ottawa Senators®'),
('NHL',	'Philadelphia Flyers®'),
('NHL',	'Pittsburgh Penguins®'),
('NHL',	'San Jose Sharks®'),
('NHL',	'Tampa Bay Lightning®'),
('NHL',	'Toronto Maple Leafs®'),
('NHL',	'Vancouver Canucks®'),
('NHL',	'Washington Capitals®'),
('NHL',	'Winnipeg Jets®'),
('Rolling Stone Magazine',	'5SOS'),
('Rolling Stone Magazine',	'Dr. Dre & Ice Cube'),
('Rolling Stone Magazine',	'Orange is the New Black'),
('Rolling Stone Magazine',	'Prince'),
('Rolling Stone Magazine',	'The Weeknd'),
('Skylanders',	'Skylanders'),
('Skylanders',	'Superchargers'),
('Star Wars',	'Rebels'),
('Star Wars',	'Saga'),
('Star Wars',	'The Force Awakens'),
('Teenage Mutant Ninja Turtles',	'Teenage Mutant Ninja Turtles'),
('Teenage Mutant Ninja Turtles',	'Out of the Shadows'),
('The Beatles',	'The Beatles'),
('The Beatles',	'Yellow Submarine'),
('The Walking Dead',	'Fear The Walking Dead'),
('The Walking Dead',	'The Walking Dead'),
('5SOS',' '),
('Alchemy',' '),
('All Time Low',' '),
('American Horror Story',' '),
('Amy Lee Weeks',' '),
('Andy Black',' '),
('Animal Club',' '),
('Ariana Grande',' '),
('Ash vs. Evil Dead',' '),
('Attack on Titan',' '),
('Avenged Sevenfold',' '),
('Barbara Boros',' '),
('Barbie',' '),
('Big Friendly Giant',' '),
('Black Veil Brides',' '),
('Bob Marley',' '),
('Bring Me the Horizon',' '),
('Bubble Guppies',' '),
('Candy Crush',' '),
('Christine Adolph',' '),
('Chuck Norris',' '),
('Cinnamon Joe',' '),
('Co-Edikit',' '),
('Cole Borders',' '),
('Cory Steffen',' '),
('Courtney Davis',' '),
('Destiny',' '),
('Diego',' '),
('Dinotrux',' '),
('Doom',' '),
('Dora the Explorer',' '),
('Elo Marc',' '),
('Eminem',' '),
('Escape the Fate',' '),
('Evelia',' '),
('Ever After High',' '),
('F is for Family',' '),
('Soccer', 'FC Barcelona'),
('Five Finger Death Punch',	' '),
('Five Nights at Freddy''s',' '),
('Gas Monkey Garage',' '),
('Godzilla',' '),
('Goosebumps',' '),
('Grumpy Cat',' '),
('Guns N'' Roses',' '),
('Harley-Davidson',' '),
('Harry Potter',' '),
('Helen Steiner Rice',' '),
('Hello Kitty',' '),
('Highlights',' '),
('Hockey Canada',' '),
('Hot Wheels',' '),
('It''s Happy Bunny',' '),
('iZombie',' '),
('Jessica Rose',' '),
('John Deere',' '),
('John Jude Palencar',' '),
('Jupiter Ascending',' '),
('Jurassic World',' '),
('Justin Bieber',' '),
('Keith Kimberlin',' '),
('Kiss',' '),
('Kung Fu Panda 3',' '),
('Lil Wayne',' '),
('Linda Woods',' '),
('Liquid Blue',' '),
('Lisa Wolk',' '),
('Little Charmers',' '),
('Littlest Pet Shop',' '),
('Looney Tunes',' '),
('Louise Carey',' '),
('Lynn Sanchelli',' '),
('M&M''s',' '),
('Maps',' '),
('Marilyn Monroe',' '),
('Maxim',' '),
('Michael Thompsett',' '),
('Minecraft',' '),
('Moises Levy',' '),
('Monster High',' '),
('Mortal Kombat',' '),
('Mustaches',' '),
('My Little Pony',' '),
('Nicki Minaj',' '),
('Once Upon A Time',' '),
('One Direction',' '),
('Orange is the New Black',' '),
('Paw Patrol',' '),
('Peppa Pig',' '),
('Rabbids',' '),
('Robert Creamer',' '),
('Rolling Stones',' '),
('Ruane Manning',' '),
('Sam Hunt',' '),
('Satio Photography',' '),
('Scarface',' '),
('Scooby Doo',' '),
('Sharon Turner',' '),
('Shawn Mendes',' '),
('Shopkins',' '),
('Sleeping with Sirens',' '),
('Slingshot Publishing',' '),
('Slipknot',' '),
('Smiley World',' '),
('Smurfs',' '),
('Snorg Tees',' '),
('SpongeBob',' '),
('Sports Illustrated',' '),
('Steve Haskamp',' '),
('Supernatural',' '),
('Teen Wolf',' '),
('Terraria',' '),
('The 100',' '),
('The Big Bang Theory',' '),
('The Blacklist',' '),
('The Exorcist',' '),
('The Hobbit',' '),
('The Lord of the Rings',' '),
('The Secret Life of Pets',' '),
('The Vamps',' '),
('The Wizard of Oz',' '),
('Thomas the Tank',' '),
('Tina Lavoie',' '),
('Transformers',' '),
('Tube Heroes',' '),
('Twisted Whiskers',' '),
('Valintina',' '),
('Warcraft',' '),
('Where''s Waldo',' '),
('Wiz Khalifa',' '),
('WWE',' ')



GO

SET ANSI_PADDING OFF
GO

/*
SELECT * FROM Odin_Web_License
*/
