SET ANSI_NULLS ON
GO

DROP TABLE Odin_NewWebCategories

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO
CREATE TABLE Odin_NewWebCategories(
	ID int IDENTITY(1,1) PRIMARY KEY,
	CATEGORY varchar(MAX) NOT NULL,
	OLD_ID INT,
)

GO

SET ANSI_PADDING OFF
GO

/*
SELECT * FROM Odin_NewWebCategories
*/
INSERT INTO Odin_NewWebCategories(CATEGORY, OLD_ID)
VALUES 
/*Begin Posters*/
('Bookmarks', '284'),
('Bookmarks: Bookmarks', '126'),
('Bookmarks: Bookmarks', '0'),
('Bookmarks: Bookmarks', '128'),
('Bookmarks: Bookmarks', '0'),
('Bookmarks: Bookmarks', '127'),
('Bookmarks: Displays', '133'),
('Bookmarks: Notemarks', '238'),
('Bookmarks: Page Clips', '129'),
('Bookmarks: Page Clips: Magnetic Page Clips', '231'),
('Bookmarks: Bookmarks', '130'),
('Bookmarks: Shapemarks', '131'),
('Calendars', '1'),
('Calendars: Box Calendars', '0'),
('Calendars: Box Calendars: Day at a Time Box Calendar', '5'),
('Calendars: Display', '9'),
('Calendars: Family Calendar', '11'),
('Calendars: Planners', '0'),
('Calendars: Engagement Planner', '8'),
('Calendars: Pocket Planners', '14'),
('Calendars: Pocket Planner + Pen', '15'),
('Calendars: Standee', '16'),
('Calendars: Wall Calendars', '17'),
('Calendars: Art Wall Calendars', '2'),
('Calendars: Collector''s Edition', '4'),
('Calendars: Deluxe Wall Calendars', '6'),
('Calendars: Mini Posters Calendars', '13'),
('Calendars: Mini Wall Calendars', '12'),
('Calendars: Weekly Calendars', '19'),
('Paper Craft', '280'),
('Paper Craft: Albums', '289'),
('Paper Craft: Albums: 12" x 12" Albums', '18'),
('Paper Craft: Albums: 8" x 8" Albums', '257'),
('Paper Craft: Albums: Boxed Kits', '26'),
('Paper Craft: Page Protectors', '27'),
('Paper Craft: Displays', '80'),
('Paper Craft: Medley', '0'),
('Paper Craft: Medley: Chipboard Medley', '23'),
('Paper Craft: Medley: Decoration Medley', '24'),
('Paper Craft: Papers', '301'),
('Paper Craft: Papers: 12" x 12" Papers', '300'),
('Paper Craft: Papers: Mega Paper Pad', '62'),
('Paper Craft: Papers: Page Kits', '64'),
('Paper Craft: Papers: Paper Packs', '63'),
('Paper Craft: Stickers', '299'),
('Paper Craft: Stickers: Essentials', '290'),
('Paper Craft: Stickers: Essentials: 4th of July', '25'),
('Paper Craft: Stickers: Essentials: Alphabets', '26'),
('Paper Craft: Stickers: Essentials: Animals', '27'),
('Paper Craft: Stickers: Essentials: Baby', '28'),
('Paper Craft: Stickers: Essentials', '29'),
('Paper Craft: Stickers: Essentials: Christmas', '30'),
('Paper Craft: Stickers: Essentials: Destinations', '31'),
('Paper Craft: Stickers: Essentials: Easter', '32'),
('Paper Craft: Stickers: Essentials: Expression', '33'),
('Paper Craft: Stickers: Essentials: Fall', '34'),
('Paper Craft: Stickers: Essentials: Family/Home', '35'),
('Paper Craft: Stickers: Essentials: Flowers', '36'),
('Paper Craft: Stickers: Essentials: Food', '37'),
('Paper Craft: Stickers: Essentials: Formal / Graduation', '38'),
('Paper Craft: Stickers: Essentials: Friends', '39'),
('Paper Craft: Stickers: Essentials: Halloween', '40'),
('Paper Craft: Stickers: Essentials: Hanukkah', '41'),
('Paper Craft: Stickers: Essentials: Inspirational', '42'),
('Paper Craft: Stickers: Essentials: Kids / Toddlers', '43'),
('Paper Craft: Stickers: Essentials: Licensed Collections', '44'),
('Paper Craft: Stickers: Essentials: Military', '45'),
('Paper Craft: Stickers: Essentials: Monogram', '46'),
('Paper Craft: Stickers: Essentials: New Year', '47'),
('Paper Craft: Stickers: Essentials: Religion', '48'),
('Paper Craft: Stickers: Essentials: School', '49'),
('Paper Craft: Stickers: Essentials: Sports / Hobbies', '50'),
('Paper Craft: Stickers: Essentials: St. Patricks Day', '51'),
('Paper Craft: Stickers: Essentials: Thanksgiving', '52'),
('Paper Craft: Stickers: Essentials: Travels', '53'),
('Paper Craft: Stickers: Essentials: Vacation', '54'),
('Paper Craft: Stickers: Essentials: Valentines / Love', '55'),
('Paper Craft: Stickers: Craft Sticker Flip Packs', '67'),
('Paper Craft: Stickers: Multi-Packs', '0'),
('Posters: Posters', '271'),
('Posters: Posters', '102'),
('Posters: 3D Prints', '87'),
('Posters: Accessories', '88'),
('Posters: Displays', '91'),
('Posters: Poster Books', '241'),
('Posters: Pre-Packs', '99'),
('Posters: SceneMakers', '299'),
('Posters: Posters: Wall Posters', '283'),
('Posters: Posters: Wall Posters', '92'),
('Posters: Posters: Wall Posters', '98'),
('Posters: Posters: Wall Posters: Animal', '103'),
('Posters: Posters: Wall Posters: Anime', '305'),
('Posters: Posters: Wall Posters: Art Trends', '104'),
('Posters: Posters: Wall Posters: Auto', '105'),
('Posters: Posters:  Black Light', '89'),
('Posters: Posters:  Collector''s Edition', '90'),
('Posters: Posters: Wall Posters: Comics', '122'),
('Posters: Posters: Wall Posters: Educational', '106'),
('Posters: Posters: Wall Posters: Humor', '107'),
('Posters: Posters: Wall Posters: Inspirational', '108'),
('Posters: Posters: Wall Posters: Kid''s Stuff', '109'),
('Posters: Posters: Wall Posters: Movies', '110'),
('Posters: Posters: Wall Posters: Movies: Age of Ultron', '0'),
('Posters: Posters: Wall Posters: Movies: Ant-Man', '0'),
('Posters: Posters: Wall Posters: Movies: Batman vs Superman', '0'),
('Posters: Posters: Wall Posters: Movies: Big Hero 6', '0'),
('Posters: Posters: Wall Posters: Movies: Cinderella', '0'),
('Posters: Posters: Wall Posters: Movies: Dark Knight', '0'),
('Posters: Posters: Wall Posters: Movies: Descendants', '0'),
('Posters: Posters: Wall Posters: Movies: Fault in Our Stars', '0'),
('Posters: Posters: Wall Posters: Movies: Frozen', '0'),
('Posters: Posters: Wall Posters: Movies: Guardians of the Galaxy', '0'),
('Posters: Posters: Wall Posters: Movies: Harry Potter', '0'),
('Posters: Posters: Wall Posters: Movies: Inside Out', '0'),
('Posters: Posters: Wall Posters: Movies: Jurassic World', '0'),
('Posters: Posters: Wall Posters: Movies: Minions', '0'),
('Posters: Posters: Wall Posters: Movies: Star Wars', '0'),
('Posters: Posters: Wall Posters: Music', '111'),
('Posters: Posters: Wall Posters: Music: 5 Seconds of Summer', '0'),
('Posters: Posters: Wall Posters: Music: Black Veil Brides', '0'),
('Posters: Posters: Wall Posters: Music: Bob Marley', '0'),
('Posters: Posters: Wall Posters: Music: One Direction', '0'),
('Posters: Posters: Wall Posters: Music: The Beatles', '0'),
('Posters: Posters: Wall Posters: Pinups', '113'),
('Posters: Posters: Wall Posters: Rolling Stone', '114'),
('Posters: Posters: Wall Posters: Sports', '298'),
('Posters: Posters: Wall Posters: Sports: MLB', '116'),
('Posters: Posters: Wall Posters: Sports: NBA', '117'),
('Posters: Posters: Wall Posters: Sports: NFL', '119'),
('Posters: Posters: Wall Posters: Sports: NHL', '120'),
('Posters: Posters: Wall Posters: Sports: Soccer', '121'),
('Posters: Posters: Wall Posters: Television', '123'),
('Posters: Posters: Wall Posters: Television: American Horror Story', '0'),
('Posters: Posters: Wall Posters: Television: Arrow', '0'),
('Posters: Posters: Wall Posters: Television: Once Upon a Time', '0'),
('Posters: Posters: Wall Posters: Television: The Walking Dead', '0'),
('Posters: Posters: Wall Posters: Video Games', '124'),
('Posters: Posters: Wall Posters: Video Games: Call of Duty', '0'),
('Posters: Posters: Wall Posters: Video Games: Halo 5', '0'),
('Posters: Posters: Wall Posters: WWE', '125'),
('Art Zone', '81'),
('Art Zone: Coloring Books', '272'),
('Art Zone: Coloring Pads', '273'),
('Art Zone: Coloring Posters: 18'' x 20'' Coloring Posters', '275'),
('Art Zone: Coloring Pads', '274'),
('Gift Bags & Wrap: Gift Bags', '83'),
('Gift Bags & Wrap: Gift Wrap', '82'),
('Stickers & Tattoos', '286'),
('Stickers & Tattoos: Decals', '285'),
('Stickers & Tattoos: Decals', '269'),
('Stickers & Tattoos: Decals', '134'),
('Stickers & Tattoos: Decals', '135'),
('Stickers & Tattoos: Decals', '136'),
('Stickers & Tattoos: Decals', '137'),
('Stickers & Tattoos: Decals: 18" x 24" Poster Decals', '270'),
('Stickers & Tattoos: Decals', '0'),
('Stickers & Tattoos: Decals: One Color Decals', '138'),
('Stickers & Tattoos: Decals', '139'),
('Stickers & Tattoos: Decals', '0'),
('Stickers & Tattoos: Decals', '141'),
('Stickers & Tattoos: Decals', '140'),
('Stickers & Tattoos: Decals', '142'),
('Stickers & Tattoos: Displays', '205'),
('Stickers & Tattoos: Office & Educational', '287'),
('Stickers & Tattoos: Office & Educational: Name Badges', '143'),
('Stickers & Tattoos: Office & Educational: Labels', '0'),
('Stickers & Tattoos: Office & Educational: Labels', '144'),
('Stickers & Tattoos: Office & Educational: Labels', '145'),
('Stickers & Tattoos: Office & Educational: Iron-On Labels', '249'),
('Stickers & Tattoos: Office & Educational: Writable Peel & Stick Labels', '254'),
('Stickers & Tattoos: Office & Educational: Reward Stickers', '146'),
('Stickers & Tattoos: Office & Educational: Reward Stickers', '0'),
('Stickers & Tattoos: Office & Educational: Reward Stickers', '260'),
('Stickers & Tattoos: Office & Educational: Reward Stickers', '230'),
('Stickers & Tattoos: Office & Educational: Reward Stickers', '0'),
('Stickers & Tattoos: Stickers', '289'),
('Stickers & Tattoos: Stickers', '300'),
('Stickers & Tattoos: Stickers', '0'),
('Stickers & Tattoos: Stickers', '154'),
('Stickers & Tattoos: Stickers', '155'),
('Stickers & Tattoos: Stickers: Stickerland Pads: 4-Page Pad', '195'),
('Stickers & Tattoos: Stickers', '0'),
('Stickers & Tattoos: Stickers', '0'),
('Stickers & Tattoos: Stickers', '0'),
('Stickers & Tattoos: Stickers: Travel Books', '197'),
('Stickers & Tattoos: Stickers', '0'),
('Stickers & Tattoos: Stickers:  My Big Box of Stickers', '173'),
('Stickers & Tattoos: Stickers:  My Sticker Activity Kit', '174'),
('Stickers & Tattoos: Stickers', '271'),
('Stickers & Tattoos: Stickers', '198'),
('Stickers & Tattoos: Stickers: Foldover', '0'),
('Stickers & Tattoos: Stickers: Foldover: Mini Foldover', '171'),
('Stickers & Tattoos: Stickers:  Grab & Go', '169'),
('Stickers & Tattoos: Stickers', '0'),
('Stickers & Tattoos: Stickers: Flip Packs', '187'),
('Stickers & Tattoos: Stickers:  Fun Packs', '189'),
('Stickers & Tattoos: Stickers:  Party Pack', '192'),
('Stickers & Tattoos: Stickers: Play Pack', '193'),
('Stickers & Tattoos: Stickers:  Pop-Up Stickers', '308'),
('Stickers & Tattoos: Stickers', '0'),
('Stickers & Tattoos: Stickers:  Stickers by the Roll', '172'),
('Stickers & Tattoos: Stickers:  Stickers by the Roll', '0'),
('Stickers & Tattoos: Stickers:  Dimensional', '265'),
('Stickers & Tattoos: Stickers: My Bands', '275'),
('Stickers & Tattoos: Stickers: Sticker Matchbooks', '236'),
('Stickers & Tattoos: Stickers: Sticker Sheets', '0'),
('Stickers & Tattoos: Stickers: Sticker Sheets', '189'),
('Stickers & Tattoos: Stickers: Sticker Sheets: Glow Stickers', '186'),
('Stickers & Tattoos: Stickers: Sticker Sheets: Scented Stickers', '175'),
('Stickers & Tattoos: Stickers: Sticker Sheets: Slim Stickers', '304'),
('Stickers & Tattoos: Stickers: Stickerland Pads', '243'),
('Stickers & Tattoos: Tattoos: Glow Tattoos', '310'),
('Paper Craft: Tape', ''),
('Paper Craft: Tape', '268'),
('Paper Craft: Tape', '246'),
('Paper Craft: Tape', '247'),
('Paper Craft: Tape', '248'),
('Paper Craft: Tape', '249'),
('Paper Craft: Tape: 1/2" Washi Tape', '231'),
('Paper Craft: Tape: Die-Cut Tape', '228'),
('Paper Craft: Tape: Foil & Metallic Tape', '253'),
('Paper Craft: Tape: Glitter Tape', '229'),
('Paper Craft: Tape', '254'),
('Paper Craft: Tape: 1/2" Tape: Washi Tape', '269'),
('Paper Craft: Tape: 3 Pack Paper Tape', '274'),
('Stickers & Tattoos: Tattoos', '286'),
('Stickers & Tattoos: Tattoos', '210'),
('Stickers & Tattoos: Tattoos: Glitter Tattoos', '259'),
('Stickers & Tattoos: Tattoos: Henna Tattoos', '257'),
('Stickers & Tattoos: Tattoos: Metallic Tattoos', '258'),
('Stickers & Tattoos: Tattoos', '213'),
('Stickers & Tattoos: Tattoos: 25ct Tattoos', '212'),
('Stickers & Tattoos: Tattoos: 75ct Tattoos', '213'),
('Writing', '287'),
('Writing: Ballpoint Pens', '0'),
('Writing', '215'),
('Writing: Ballpoint Pens: Premium Pens', '244'),
('Writing Instruments: 2-pack Gel Pens', '0'),
('Writing: Gel Pens: 5-pack Colored Gel Pens', '233'),
('Writing: Gel Pens: Gel Pen + Bookmark Packs', '219'),
('Writing: Gel Pens: Mini Gel Pens', '221'),
('Writing', '220'),
('Writing: Ballpoint Pens: Projector Pens', '222'),
('Writing: Ballpoint Pens: 4-pack Stick Pens', '224'),
('Writing: Ballpoint Pens: Stylus Pens', '225'),
('Stickers & Tattoos: Tattoos: Glow Tattoos', '310')

