SET ANSI_NULLS ON
GO

DROP TABLE Odin_WebCategories

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO
CREATE TABLE Odin_WebCategories(
	ID int IDENTITY(1,1) PRIMARY KEY,
    CATEGORY varchar(MAX) NOT NULL
)

GO

SET ANSI_PADDING OFF
GO

/*
SELECT * FROM Odin_WebCategories
*/
INSERT INTO Odin_WebCategories(CATEGORY)
VALUES 
('Calendars: Art Calendar: Art'),
('Calendars: Art Calendar: Premium Art'),
('Calendars: Collectors Edition'),
('Calendars: Day-At-A-Time Box'),
('Calendars: Day-At-A-Time Mini Box'),
('Calendars: Delux'),
('Calendars: DVD Wall'),
('Calendars: Engagement Planner'),
('Calendars: Family Calendar'),
('Calendars: Family Planner - 12" x 12"'),
('Calendars: Linen Wall'),
('Calendars: Mini'),
('Calendars: Oversized'),
('Calendars: Pocket Planner'),
('Calendars: Pocket Planner & Pen'),
('Calendars: Standee'),
('Calendars: Wall: Wall'),
('Calendars: Wall: Premium Wall'),
('Calendars: Weekly Calendar & Pen'),
('Calendars: Weekly Desk'),
('Calendars: Display: Corrugate'),
('Calendars: Display: Wire'),
('Paper Craft: Album & Album Kits: 12" x 12" Albums'),
('Paper Craft: Album & Album Kits: 12" x 12" Three Post Albums'),
('Paper Craft: Album & Album Kits: All-in-One Album Kit'),
('Paper Craft: Album & Album Kits: Boxed Album Kit'),
('Paper Craft: Album & Album Kits: Page Protectors'),
('Paper Craft: Chipboard Medley'),
('Paper Craft: Decoration Medley'),
('Paper Craft: Essentials Embellished Stickers: 4th of July'),
('Paper Craft: Essentials Embellished Stickers: Alphabets'),
('Paper Craft: Essentials Embellished Stickers: Animals'),
('Paper Craft: Essentials Embellished Stickers: Baby'),
('Paper Craft: Essentials Embellished Stickers: Celebrations'),
('Paper Craft: Essentials Embellished Stickers: Christmas'),
('Paper Craft: Essentials Embellished Stickers: Destinations'),
('Paper Craft: Essentials Embellished Stickers: Easter'),
('Paper Craft: Essentials Embellished Stickers: Expression'),
('Paper Craft: Essentials Embellished Stickers: Fall'),
('Paper Craft: Essentials Embellished Stickers: Family/Home'),
('Paper Craft: Essentials Embellished Stickers: Flowers'),
('Paper Craft: Essentials Embellished Stickers: Food'),
('Paper Craft: Essentials Embellished Stickers: Formal/Graduation'),
('Paper Craft: Essentials Embellished Stickers: Friends'),
('Paper Craft: Essentials Embellished Stickers: Halloween'),
('Paper Craft: Essentials Embellished Stickers: Hanukkah'),
('Paper Craft: Essentials Embellished Stickers: Inspirational'),
('Paper Craft: Essentials Embellished Stickers: Kids/Toddlers'),
('Paper Craft: Essentials Embellished Stickers: Licensed Collections'),
('Paper Craft: Essentials Embellished Stickers: Military'),
('Paper Craft: Essentials Embellished Stickers: Monogram'),
('Paper Craft: Essentials Embellished Stickers: New Year'),
('Paper Craft: Essentials Embellished Stickers: Religion'),
('Paper Craft: Essentials Embellished Stickers: School'),
('Paper Craft: Essentials Embellished Stickers: Sports/Hobbies'),
('Paper Craft: Essentials Embellished Stickers: St. Patricks Day'),
('Paper Craft: Essentials Embellished Stickers: Thanksgiving'),
('Paper Craft: Essentials Embellished Stickers: Travel'),
('Paper Craft: Essentials Embellished Stickers: Vacation'),
('Paper Craft: Essentials Embellished Stickers: Valentines'),
('Paper Craft: Papers: 12" x 12" Papers: Clear Varnish'),
('Paper Craft: Papers: 12" x 12" Papers: Double Sided Cardstock'),
('Paper Craft: Papers: 12" x 12" Papers: Embossing'),
('Paper Craft: Papers: 12" x 12" Papers: Foil'),
('Paper Craft: Papers: 12" x 12" Papers: Glitter'),
('Paper Craft: Papers: 12" x 12" Papers: Non Embellished'),
('Paper Craft: Papers: Mega Paper Pad'),
('Paper Craft: Papers: Paper Packs'),
('Paper Craft: Papers: Page Kits'),
('Paper Craft: Papers: Theme Packs'),
('Paper Craft: Stickers: All-in-One Cardstock Stickers'),
('Paper Craft: Stickers: Craft Sticker Flip Packs'),
('Paper Craft: Stickers: Dimensional Stickers'),
('Paper Craft: Stickers: Tall Stickers: Chipboard w/ Foil'),
('Paper Craft: Stickers: Tall Stickers: Clear'),
('Paper Craft: Stickers: Tall Stickers: Paper'),
('Paper Craft: Stickers: Tall Stickers: Clear w/ Glitter & Rhinestones'),
('Paper Craft: Stickers: Tall Stickers: Layered Glitter'),
('Paper Craft: Stickers: Tall Stickers: Gem'),
('Paper Craft: Stickers: Tall Dimensional Stickers'),
('Paper Craft: Stickers: Tall Dimensional Stickers: Foam'),
('Paper Craft: Stickers: Tall Dimensional Stickers: Foam'),
('Paper Craft: Stickers: Tall Dimensional Stickers: Gems'),
('Paper Craft: Stickers: Tall Dimensional Stickers: Paper Tote'),
('Paper Craft: Displays'),
('Gift Wrap: Rolled (2.5 ft x 1.6 yards)'),
('Gift Wrap: Rolled (2.5 ft x 2.6 yards)'),
('Gift Wrap: Folded (9" x 13")'),
('Gift Wrap: Gift Bags'),
('Gift Wrap: Display'),
('Posters: Posters: 12 x 36 Prints'),
('Posters: Posters: 24 x 36 Prints'),
('Posters: 3-D Prints: 16x20 Premium Frame'),
('Posters: Accessories'),
('Posters: Posters: Black Light'),
('Posters: Posters: Collector''s Edition'),
('Posters: Displays'),
('Posters: Posters: Door-Sized'),
('Posters: Fan Packs'),
('Posters: Fluorescent'),
('Posters: Posters: Glow-In-The-Dark'),
('Posters: Growth Charts'),
('Posters: Mounted Prints'),
('Posters: Posters: Murals'),
('Posters: Pre-Packs'),
('Posters: Posters: Premium Edition'),
('Posters: Tin Signs'),
('Posters: What''s New'),
('Posters: Posters: Wall Posters: Animal'),
('Posters: Posters: Wall Posters: Art Trends'),
('Posters: Posters: Wall Posters: Auto'),
('Posters: Posters: Wall Posters: Educational'),
('Posters: Posters: Wall Posters: Humor'),
('Posters: Posters: Wall Posters: Inspirational'),
('Posters: Posters: Wall Posters: Kids Stuff'),
('Posters: Posters: Wall Posters: Movie'),
('Posters: Posters: Wall Posters: Music'),
('Posters: Posters: Wall Posters: Patriotic'),
('Posters: Posters: Wall Posters: Pinups'),
('Posters: Posters: Wall Posters: Rolling Stone Magazine'),
('Posters: Posters: Wall Posters: Scenic'),
('Posters: Posters: Wall Posters: Sports: MLB'),
('Posters: Posters: Wall Posters: Sports: NBA'),
('Posters: Posters: Wall Posters: Sports: NCAA'),
('Posters: Posters: Wall Posters: Sports: NFL'),
('Posters: Posters: Wall Posters: Sports: NHL'),
('Posters: Posters: Wall Posters: Sports: Soccer'),
('Posters: Posters: Wall Posters: Super Heroes'),
('Posters: Posters: Wall Posters: Television'),
('Posters: Posters: Wall Posters: Video Games'),
('Posters: Posters: Wall Posters: WWE'),
('Social Stationery: 3-D Bookmarks'),
('Social Stationery: Bling Bookmark'),
('Social Stationery: Collectors Beaded Bookmark'),
('Social Stationery: Page Clips'),
('Social Stationery: Premier Bookmarks'),
('Social Stationery: ShapeMarks'),
('Social Stationery: Standard Bookmarks'),
('Social Stationery: Display'),
('Stickers & Decals: Decals: Decals - 4" x 5.25"'),
('Stickers & Decals: Decals: Decals - 4" x 8.5"'),
('Stickers & Decals: Decals: Decals-6" x 14.25"'),
('Stickers & Decals: Decals: Drink Markers'),
('Stickers & Decals: Decals: One Color Decals'),
('Stickers & Decals: Decals: RoomScapes Decal Book'),
('Stickers & Decals: Decals: RoomScapes Mini Wall Accents'),
('Stickers & Decals: Decals: RoomScapes Wall Accents'),
('Stickers & Decals: Decals: Window Decals'),
('Stickers & Decals: Office & Educational: Badges - 6 Sheet'),
('Stickers & Decals: Office & Educational: Binder Labels'),
('Stickers & Decals: Office & Educational: Designer Labels'),
('Stickers & Decals: Office & Educational: Reward Stickers'),
('Stickers & Decals: Stickers: Albums: Lil Sticker Collections'),
('Stickers & Decals: Stickers: Albums: Sticker Albums'),
('Stickers & Decals: Stickers: Big Bits'),
('Stickers & Decals: Stickers: Bitty Bits'),
('Stickers & Decals: Stickers: Custom Sized'),
('Stickers & Decals: Stickers: Dimensional: Bubbled'),
('Stickers & Decals: Stickers: Dimensional: Canvas'),
('Stickers & Decals: Stickers: Dimensional: Foam'),
('Stickers & Decals: Stickers: Dimensional: Foam Embossed'),
('Stickers & Decals: Stickers: Dimensional: Gem'),
('Stickers & Decals: Stickers: Dimensional: Metal'),
('Stickers & Decals: Stickers: Dimensional: Puffy Fuzzy'),
('Stickers & Decals: Stickers: Dimensional: Stacked'),
('Stickers & Decals: Stickers: Foam'),
('Stickers & Decals: Stickers: Foam Boxed'),
('Stickers & Decals: Stickers: Foldover'),
('Stickers & Decals: Stickers: Glow Stickers'),
('Stickers & Decals: Stickers: Grab and Go'),
('Stickers & Decals: Stickers: Grab and Go Delux'),
('Stickers & Decals: Stickers: Mini Foldover'),
('Stickers & Decals: Stickers: Mini Stickers by the Roll'),
('Stickers & Decals: Stickers: My Big Box of Stickers'),
('Stickers & Decals: Stickers: My Sticker Activity Kit'),
('Stickers & Decals: Stickers: Scented Stickers'),
('Stickers & Decals: Stickers: Seasonal Stickers: Christmas/Hanukkah'),
('Stickers & Decals: Stickers: Seasonal Stickers: Easter'),
('Stickers & Decals: Stickers: Seasonal Stickers: Halloween'),
('Stickers & Decals: Stickers: Seasonal Stickers: Valentines Day'),
('Stickers & Decals: Stickers: Slim Stickers: Clear'),
('Stickers & Decals: Stickers: Slim Stickers: Foam'),
('Stickers & Decals: Stickers: Slim Stickers: Fuzzy'),
('Stickers & Decals: Stickers: Slim Stickers: Gems'),
('Stickers & Decals: Stickers: Slim Stickers: Paper'),
('Stickers & Decals: Stickers: Slim Stickers: Pop-up'),
('Stickers & Decals: Stickers: Slim Stickers: Prismatic'),
('Stickers & Decals: Stickers: Slim Stickers: Puffy Fuzzy'),
('Stickers & Decals: Stickers: Slim Stickers: Shimmer'),
('Stickers & Decals: Stickers: Standard Sticker - 4 Sheet'),
('Stickers & Decals: Stickers: Sticker Activity Book'),
('Stickers & Decals: Stickers: Sticker Flip Packs'),
('Stickers & Decals: Stickers: Sticker Party Pack'),
('Stickers & Decals: Stickers: Sticker Play Pack'),
('Stickers & Decals: Stickers: Sticker Storage Box'),
('Stickers & Decals: Stickers: Sticker Tote'),
('Stickers & Decals: Stickers: Sticker Travel Bag'),
('Stickers & Decals: Stickers: Sticker Travel Book'),
('Stickers & Decals: Stickers: Sticker Treasure Box'),
('Stickers & Decals: Stickerland Pads: 4 Pages'),
('Stickers & Decals: Stickerland Pads: 4 Pages Foam'),
('Stickers & Decals: Stickerland Pads: Mini Stickerland Pads - 6 Pages'),
('Stickers & Decals: Stickerland Pads: 6 Pages Die Cut'),
('Stickers & Decals: Stickerland Pads: 8 Pages'),
('Stickers & Decals: Stickerland Pads: 16 Page Activity Pads'),
('Stickers & Decals: Stickerland Pads: Stickerland Play Scenes'),
('Stickers & Decals: Stickerland Pads: Stickers by the Roll'),
('Stickers & Decals: Stickerland Pads: Sticker Matchbook'),
('Stickers & Decals: Stickerland Pads: Mini Sticker Books'),
('Stickers & Decals: Display'),
('Temporary Tattoos: 1-Sheet Tattoos'),
('Temporary Tattoos: 2-Sheet Tattoos'),
('Temporary Tattoos: Mini Tattoo Bag - 25ct'),
('Temporary Tattoos: Standard Tattoo Bag - 75ct'),
('Temporary Tattoos: Displays'),
('Writing Instruments: Ballpoint Pen + Notepad Pack'),
('Writing Instruments: Combo - 2pk'),
('Writing Instruments: Gel Pen - 2pk'),
('Writing Instruments: Gel Pen & Mechanical Pencil Combo - 2pk'),
('Writing Instruments: Gel Pen + Bookmark Packs'),
('Writing Instruments: Mechanical Pencils - 2pk'),
('Writing Instruments: Mini Gel Pens - 3pk'),
('Writing Instruments: Projector Pen'),
('Writing Instruments: Secret Scribbler - 2pk'),
('Writing Instruments: Stick Pens - 4pk'),
('Writing Instruments: Stylus Pen - 1pk'),
('Writing Instruments: Displays'),
('Tape Works: 3" Accent Tape'),
('Tape Works: 1/2" Tape: DieCut Tape'),
('Tape Works: 1/2" Tape: Glitter Tape'),
('Tape Works: Tape 4 Ct Box'),
('Tape Works: 1/2" Tape'),
('Tape Works: Display'),
('Writing Instruments: Colored Gel Pens - 5pk'),
('Stickers & Decals: Office & Educational: Stickerland Reward Pads - 12 Page'),
('Social Stationery: Magnetic Page Clips'),
('Stickers & Decals: Stickers: Sticker Matchbook'),
('Stickers & Decals: Stickers: Stickers Party Pad'),
('Stickers & Decals: Stickers: Fashion Stickers'),
('Paper Craft: Stickers: Tall Stickers: Foam'),
('Stickers & Decals: Display: Corrugate'),
('Social Stationery: Display: Corrugate'),
('Social Stationery: NoteMarks'),
('Stickers & Decals: Stickers: Stickerland Pads: Giant Stickerland Pads'),
('Writing Instruments: Premium Ballpoint Pen'),
('Posters: Poster Books'),
('Tape Works: 1" Tape: Bundle Tape'),
('Tape Works: 1" Tape: Decorative Tape'),
('Tape Works: 1" Tape: Marking Tape'),
('Tape Works: 1" Tape: Utility Tape'),
('Calendars: Die-Cut Calendar Pad'),
('Calendars: Mini Poster Calendar'),
('Calendars: Chalkboard Calendars'),
('Tape Works: 1/2" Tape: Foil Tape'),
('Tape Works: 1/2" Tape: Lace Tape'),
('Writing Instruments: Colored Mechanical Pencils - 5pk'),
('Stickers & Decals: Office & Educational: Iron-On Labels'),
('Temporary Tattoos: Henna Tattoos'),
('Temporary Tattoos: Metallic Tattoos'),
('Temporary Tattoos: Glitter Tattoos'),
('Stickers & Decals: Office & Education: Mega Stickerland Reward Pads '),
('Stickers & Decals: Office & Educational: Peel & Stick Labels'),
('Stickers & Decals: Decals: RoomScapes Poster Decal - 18" x 24"'),
('Temporary Tattoos: Metallic Tattoos - 55ct'),
('Paper Craft: Album & Album Kits: 8" x 8" Scrapbook Album'),
('Stickers & Decals: Stickerland Pads: Mini Activity Pad'),
('Temporary Tattoos: Glitter Tattoos - 55ct'),
('Temporary Tattoos: Metallic + 4c Tattoos - 55ct'),
('Tape Works: 1" Tape'),
('Tape Works: 1/2" Tape: Washi Tape'),
('Stickers & Decals: Stickerland Pads: Sticker+Tattoo - 4 pages'),
('Stickers & Decals: Stickers: Sticker Boxes - 8pk'),
('Stickers & Decals: Stickers: Standard Value Dimensional'),
('Temporary Tattoos: Tattoo Kit'),
('Tape Works: 3 Pack Paper Tape'),
('Stickers & Decals: Stickers: My Bands - Sticker Bracelets'),
('Stickers & Decals: Decals: 4 Color Decals'),
('Stickers & Decals: Decals: Poster Decals - 24" x 36"')

