
/****** Object:  Table [dbo].[PS_INV_ITEMS]    Script Date: 11/25/2013 2:16:58 PM ******/
/*
DROP TABLE Odin_LicenseStats
SELECT * FROM Odin_LicenseStats ORDER BY STATS_CODE ASC
*/
DROP TABLE Odin_LicenseStats

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE Odin_LicenseStats(
	STATS_CODE varchar(MAX) NULL,
	LICENSE varchar(MAX) NULL,
	PROPERTY varchar(MAX) NULL
)
INSERT INTO Odin_LicenseStats(STATS_CODE, LICENSE, PROPERTY) 
VALUES 
('STRWAL', 'Amc', 'Amc: THE WALKING DEAD'),
('ACTBLA', 'Activision', 'Activision: CALL OF DUTY'),
('ACTBO2', 'Activision', 'Activision: CALL OF DUTY'),
('ACTCAL', 'Activision', 'Activision: CALL OF DUTY'),
('ACTDES', 'Activision', 'Activision: DESTINY'),
('ACTGHO', 'Activision', 'Activision: CALL OF DUTY'),
('ACTMW3', 'Activision', 'Activision: CALL OF DUTY'),
('ACTSKY', 'Activision', 'Activision: SKYLANDERS'),
('ACTWAR', 'Activision', 'Activision: CALL OF DUTY'),
('SKYSTI', 'Activision', 'Activision: SKYLANDERS SUPERCHARGERS'),
('CARADV', 'Cartoon Network', 'Cartoon Network: ADVENTURE TIME'),
('CARAMA', 'Cartoon Network', 'Cartoon Network: THE AMAZING WORLD OF GUMBALL'),
('CARLEG', 'Cartoon Network', 'Cartoon Network: LEGO MIXELS'),
('CARREG', 'Cartoon Network', 'Cartoon Network: REGULAR SHOW'),
('CARTAN', 'Cartoon Network', 'Cartoon Network: MISS CARIBBEAN TAN'),
('DIS101', 'Disney', 'Disney: 101 DALMATIANS'),
('DISACC', 'Disney', 'Disney: A CHRISTMAS CAROL'),
('DISALI', 'Disney', 'Disney: ALICE'),
('DISANT', 'Disney', 'Disney: A.N.T. FARM'),
('DISATL', 'Disney', 'Disney: ALICE IN WONDERLAND'),
('DISAUS', 'Disney', 'Disney: AUSTIN & ALLY'),
('DISBAM', 'Disney', 'Disney: BAMBI'),
('DISBH6', 'Disney', 'Disney: BIG HERO 6'),
('DISBOL', 'Disney', 'Disney: BOLT'),
('DISBRA', 'Disney', 'Disney: BRAVE'),
('DISCAR', 'Disney', 'Disney: CARS'),
('DISCHE', 'Disney', 'Disney: BMCOL'),
('DISCHI', 'Disney', 'Disney: CHICKEN LITTLE'),
('DISCHR', 'Disney', 'Disney: NARNIA'),
('DISCIN', 'Disney', 'Disney: PRINCESS'),
('DISCLA', 'Disney', 'Disney: CINDERELLA'),
('DISCOR', 'Disney', 'Disney: CORY IN THE HOUSE'),        
('DISDAR', 'Disney', 'Disney: STAR DARLINGS'),
('DISDES', 'Disney', 'Disney: DESCENDANTS'),
('DISDIS', 'Disney', 'Disney: WALT Disney'),
('DISDOR', 'Disney', 'Disney: FINDING DORY'),
('DISDUM', 'Disney', 'Disney: DUMBO'),
('DISEIN', 'Disney', 'Disney: LITTLE EINSTEINS'),    
('DISENC', 'Disney', 'Disney: PRINCESS - ENCHANTED'),
('DISEPI', 'Disney', 'Disney: EPIC MICKEY'),
('DISFAI', 'Disney', 'Disney: TINKER BELL'),
('DISFRA', 'Disney', 'Disney: FRANKENWEENIE'),    
('DISFRO', 'Disney', 'Disney: FROZEN'),
('DISGFO', 'Disney', 'Disney: G-FORCE'),
('DISGRA', 'Disney', 'Disney: GRAVITY FALLS'),
('DISHAN', 'Disney', 'Disney: HANNAH MONTANA'),
('DISHER', 'Disney', 'Disney: HERBIE FULLY LOADED'),
('DISHS3', 'Disney', 'Disney: HIGH SCHOOL MUSICAL'),
('DISHSM', 'Disney', 'Disney: HIGH SCHOOL MUSICAL'),
('DISINC', 'Disney', 'Disney: INCREDIBLES'),
('DISINF', 'Disney', 'Disney: Disney INFINITY'),
('DISINS', 'Disney', 'Disney: INSIDE OUT'),
('DISJAK', 'Disney', 'Disney: CAPTAIN JAKE + NLP'),
('DISJES', 'Disney', 'Disney: Jessie - New York'),            
('DISJLA', 'Disney', 'Disney: THE JUNGLE BOOK'),
('DISJTV', 'Disney', 'Disney: JONAS BROTHERS'),
('DISJUM', 'Disney', 'Disney: JUMP IN'),
('DISKCU', 'Disney', 'Disney: KC UNDERCOVER'),               
('DISKIM', 'Disney', 'Disney: KIM POSSIBLE'),
('DISKIN', 'Disney', 'Disney: KINGDOM HEARTS'),
('DISLAD', 'Disney', 'Disney: LADY AND THE TRAMP'),
('DISLIG', 'Disney', 'Disney: FROZEN'),
('DISLIO', 'Disney', 'Disney: LION KING'),
('DISLIV', 'Disney', 'Disney: LIV AND MADDIE'),
('DISMAD', 'Disney', 'Disney: MADISON HIGH'),
('DISMAL', 'Disney', 'Disney: MALEFICENT'),
('DISMAN', 'Disney', 'Disney: DM WALL HANDY MANNY'),
('DISMIL', 'Disney', 'Disney: TOMMORROW LAND'),
('DISMON', 'Disney', 'Disney: MONSTERS UNIVERSITY'),
('DISMUP', 'Disney', 'Disney: MUPPETS'),
('DISNBC', 'Disney', 'Disney: NIGHTMARE BEFORE CHRISTMAS'),
('DISNEM', 'Disney', 'Disney: FINDING NEMO'),
('Disney', 'Disney', ''),
('DISLIG', 'Disney', 'Disney: FROZEN'),
('DISOZZ', 'Disney', 'Disney: OZ'),
('DISPAL', 'Disney', 'Disney: PRINCESS PALACE PETS'),
('DISPAN', 'Disney', 'Disney: PURE MAGIC'),
('DISPEN', 'Disney', 'Disney: CLUB PENGUIN'),
('DISPER', 'Disney', 'Disney: PRINCE OF PERSIA'),
('DISPHI', 'Disney', 'Disney: PHINEAS & FERB'),
('DISPIR', 'Disney', 'Disney: PIRATES OF THE CARRIBEAN'),          
('DISPIX', 'Disney', 'Disney: PIXAR'),
('DISPLA', 'Disney', 'Disney: PLANES'),
('DISPOW', 'Disney', 'Disney: POWER RANGERS'),
('DISPPP', 'Disney', 'Disney: PPP'),
('DISRAL', 'Disney', 'Disney: WRECK IT RALPH'),
('DISRAP', 'Disney', 'Disney: TANGLED'),
('DISRAT', 'Disney', 'Disney: RATATOUILLE'),
('DISROC', 'Disney', 'Disney: CAMP ROCK'),
('DISSHE', 'Disney', 'Disney: SHERIFF CALLIE'),
('DISSIU', 'Disney', 'Disney: SHAKE IT UP'),
('DISSNW', 'Disney', 'Disney: MIRROR MIRROR'),
('DISSOF', 'Disney', 'Disney: SOFIA THE FIRST'),
('DISSON', 'Disney', 'Disney: REAL PRINCESSES'),
('DISSTC', 'Disney', 'Disney: MICKEY CLUB HOUSE'),
('DISSTI', 'Disney', 'Disney: CARS'),
('DISTBM', 'Disney', 'Disney: TEEN BEACH MOVIE'),
('DISTGD', 'Disney', 'Disney: THE GOOD DINOSAUR'),
('DISTLR', 'Disney', 'Disney: THE LONE RANGER'),
('DISTOM', 'Disney', 'Disney: TOMORROWLAND'),
('DISTOY', 'Disney', 'Disney: TOY STORY'),
('DISTRO', 'Disney', 'Disney: TRON LEGACY'),
('DISTSU', 'Disney', 'Disney: TSUM TSUM'),
('DISVIL', 'Disney', 'Disney: VILLAINS'),
('DISWAL', 'Disney', 'Disney: WALL E'),
('DISWAT', 'Disney', 'Disney: WHERE''S MY WATER?'),
('DISWEE', 'Disney', 'Disney: FRANKENWEENIE'),
('DISWIZ', 'Disney', 'Disney: WIZARDS OF WAVERLY'),
('DISWTP', 'Disney', 'Disney: POOH'),
('DISARI', 'Disney', 'Disney: THE ARISTOCATS'),
('DAZDIS', 'Disney', 'Disney: POOH'),
('DISEMO', 'Disney', 'Disney: EMOJI LAND'),
('DISFAR', 'Disney', 'Disney: PLANES & FIRE RESCUE'),
('DISDOC', 'Disney', 'Disney: DOC MCSTUFFINS'),
('DISJOH', 'Disney', 'Disney: JOHN CARTER'),
('DISMOA', 'Disney', 'Disney: MOANA'),
('DISTLG', 'Disney', 'Disney: THE LION GUARD'),
('DRMCRO', 'Dreamworks', 'Dreamworks: THE CROODS'),
('DRMDRA', 'Dreamworks', 'Dreamworks: HOW TO TRAIN YOUR DRAGON'),
('DRMKF2', 'Dreamworks', 'Dreamworks: KUNG FU PANDA'),
('DRMMA3', 'Dreamworks', 'Dreamworks: MADAGASCAR'),
('DRMMEG', 'Dreamworks', 'Dreamworks: MEGAMIND'),
('DRMNEE', 'Dreamworks', 'Dreamworks: NEED FOR SPEED'),
('DRMPEA', 'Dreamworks', 'Dreamworks: MR. PEABODY & SHERMAN'),
('DRMPUS', 'Dreamworks', 'Dreamworks: PUSS IN BOOTS'),
('DRMRIS', 'Dreamworks', 'Dreamworks: RISE OF THE GUARDIANS'),
('DRMROS', 'Dreamworks', 'Dreamworks: DINOTRUX'),
('DRMSH4', 'Dreamworks', 'Dreamworks: SHREK'),
('DRMTUR', 'Dreamworks', 'Dreamworks: TURBO'),
('DRMWAL', 'Dreamworks', 'Dreamworks: WHERE''S WALDO'),
('EAGALI', 'EA', 'EA: ALICE'),
('EAGBA4', 'EA', 'EA: BATTLEFIELD'),
('EAGBAT', 'EA', 'EA: BATTLEFIELD'),
('EAGDR2', 'EA', 'EA: DRAGON AGE'),
('EAGMAS', 'EA', 'EA: MASS EFFECT'),
('EAGMED', 'EA', 'EA: MEDAL OF HONOR'),
('EAGTIT', 'EA', 'EA: TITANFALL'),
('FOXFOS', '20th Century Fox', '20th Century Fox: THE FAULT IN OUR STARS'),
('FOXPAP', '20th Century Fox', '20th Century Fox: PAPER TOWNS'),
('FOXLOT', '20th Century Fox', '20th Century Fox: SANDLOT'),
('FOXAHS', '20th Century Fox', '20th Century Fox: AMERICAN HORROR STORY'),
('FOXARR', '20th Century Fox', '20th Century Fox: ARRESTED DEVELOPMENT'),
('FOXRIO', '20th Century Fox', '20th Century Fox: RIO 2'),
('FOXSLE', '20th Century Fox', '20th Century Fox: SLEEPY HOLLOW'),
('HARLEY', 'Harley-Davidson', ''), 
('HASCLA', 'Hasbro', 'Hasbro: TRANSFORMERS CLASSIC'),
('HASLIT', 'Hasbro', 'Hasbro: LITTLEST PET SHOP'),
('HASPON', 'Hasbro', 'Hasbro: MY LITTLE PONY'),
('HASSTI', 'Hasbro', 'Hasbro: MY LITTLE PONY'),
('HASTR2', 'Hasbro', 'Hasbro: TRANSFORMERS'),
('HASTR3', 'Hasbro', 'Hasbro: TRANSFORMERS'),
('HASTR4', 'Hasbro', 'Hasbro: TRANSFORMERS'),
('LUCEP3', 'Star Wars', 'Star Wars: EPISODE I - VI'),
('LUCEP7', 'Star Wars', 'Star Wars: Star Wars THE FORCE AWAKENS'),
('LUCREB', 'Star Wars', 'Star Wars: Star Wars REBELS'),
('LUCROG', 'Star Wars', 'Star Wars: Star Wars: ROGUE ONE'),
('LUCROV', 'Star Wars', 'Star Wars: ANGRY BIRDS STAR WAR'),
('LUCSTI', 'Star Wars', ''),
('MARANT', 'Marvel', 'Marvel: ANTMAN'),              
('MARAOS', 'Marvel', 'Marvel: AGENTS OF SHIELD'),       
('MARAV2', 'Marvel', 'Marvel: AVENGERS 2'),    
('MARAVE', 'Marvel', 'Marvel: AVENGERS'),
('MARAVV', 'Marvel', 'Marvel: AVENGERS'), 
('MARCA3', 'Marvel', 'Marvel: CAPTAIN AMERICA 3'),
('MARCAL', 'Marvel', 'Marvel: AVENGERS'),           
('MARCAP', 'Marvel', 'Marvel: CAPTAIN AMERICA'),
('MARDRS', 'Marvel', 'Marvel: DOCTOR STRANGE'),
('MARGAL', 'Marvel', 'Marvel: GUARDIANS OF THE GALAXY'),
('MARIM2', 'Marvel', 'Marvel: IRON MAN'),
('MARIM3', 'Marvel', 'Marvel: IRON MAN'),
('MARINF', 'Marvel', 'Marvel: Disney INFINITY'),
('MARMV2', 'Marvel', 'Marvel: X-MEN'),
('MARPEN', 'Marvel', 'Marvel: AVENGERS'),
('MARSPI', 'Marvel', 'Marvel: SPIDER-MAN'),
('MARSTI', 'Marvel', 'Marvel: SPIDER-MAN'),
('MARTHO', 'Marvel', 'Marvel: THOR'),
('MARUNI', 'Marvel', ''),
('MARX1C', 'Marvel', 'Marvel: X-MEN'),
('MARXMN', 'Marvel', 'Marvel: X-MEN'),
('MATBAR', 'Mattel', 'Mattel: BARBIE'),
('MATEVE', 'Mattel', 'Mattel: EVER AFTER HIGH'),
('MATHOT', 'Mattel', 'Mattel: HOT WHEELS'),
('MATMON', 'Mattel', 'Mattel: MONSTER HIGH'),
('MTVDOR', 'Nickelodeon', 'Nickelodeon: DORA THE EXPLORER'),
('MTVPAW', 'Nickelodeon', 'Nickelodeon: PAW PATROL'),
('SESAME', 'Sesame Street',''),
('MTVBOB', 'Nickelodeon', 'Nickelodeon: SPONGEBOB'),
('SMMSM4', 'Marvel', 'Marvel: SPIDER-MAN'),
('SMMSM5', 'Marvel', 'Marvel: SPIDER-MAN'),
('SIPOST', 'Sports Illustrated', ''),
('TIMESI', 'Sports Illustrated',''),
('WWFCAL', 'WWE',''),
('WWFWWF', 'WWE',''),
('ABCNAS', 'ABC','ABC: NASHVILLE'),
('ABCOUT', 'ABC', 'ABC: ONCE UPON A TIME'),
('DJETER', 'MLB', ''),
('MLBPLA', 'MLB', ''),
('MLBPRO', 'MLB', ''),
('MLBMLB', 'MLB', ''),
('MLBVIN', 'MLB', ''),
('MEANBA',' NBA', ''),
('NBANBA', 'NBA', ''),
('NBAPLA', 'NBA', ''),
('MEANBA', 'NBA', ''),    
('NFLNFL', 'NFL', ''),
('NFLLIB', 'NFL', ''),
('NFLPLA', 'NFL', ''),
('NFLPRE', 'NFL', ''),
('NFLSUP', 'NFL', ''),
('NHLNHL', 'NHL', ''),
('NHLPLA', 'NHL', ''),
('MTVSTI', 'Nickelodeon', ''),
('SONBCS', 'Sony', 'Sony: BETTER CALL SAUL'),
('SONKIL', 'Sony', 'Sony: KILLZONE'),
('SONLIT', 'Sony', 'Sony: LITTLE BIG PLANET'),
('SONTWI', 'Sony', 'Sony: TWISTED METAL'),
('SONUNC', 'Sony', 'Sony: UNCHARTED'),
('SMURFS', 'Sony', 'Sony: SMURFS'),
('SONBLA', 'Sony', 'Sony: THE BLACKLIST'),
('SONBRE', 'Sony', 'Sony: BREAKING BAD'),
('SONGOO', 'Sony', 'Sony: GOOSEBUMP'),
('SON5TH', 'Sony', 'Sony: KISS'),
('SMURF2', 'Sony', 'Sony: SMURFS'),
('SONMOR', 'Sony', 'Sony: THE MORTAL INSTRUMENT'),
('SONRAT', 'Sony', 'Sony: RATCHET & CLANK'),
('SONHOT', 'Sony', 'Sony: HOTEL TRANSYLVANIA'),
('UNIDES', 'Universal', 'Universal: DESPICABLE ME'),
('UNIJUR', 'Universal', 'Universal: JURASSIC WORLD'),
('UNIOFF', 'Universal', 'Universal: THE OFFICE'),
('UNIPAR', 'Universal', 'Universal: PARKS & RECREATION'),
('UNISC2', 'Universal', 'Universal: SCARFACE'),
('UNISCA', 'Universal', 'Universal: SCARFACE'),
('UNISCO', 'Universal', 'Universal: SCOTT PILGRIM'),
('UNISEC', 'Universal', 'Universal: SHOPKINS'),
('UNISNO', 'Universal', 'Universal: SNOW WHITE'),
('WARARR', 'DC', 'DC: ARROW'),
('WARENT', 'Warner Bros', 'Warner Bros: ENTOURAGE'),
('WARHOR', 'Warner Bros', 'Warner Bros: A NIGHTMARE ON ELM STREET'),
('WARJUP', 'Warner Bros', 'Warner Bros: JUPITER ASCENDING '),
('WARMAD', 'Warner Bros', 'Warner Bros: MAD'),
('WARMOR', 'Warner Bros', 'Warner Bros: MORTAL KOMBAT'),
('WARMOS', 'DC', 'DC: MAN OF STEEL'),
('WARNAT', 'Warner Bros', 'Warner Bros: SUPERNATURAL'),
('WARPAN', 'Warner Bros', 'Warner Bros: PAN'),
('WARPEN', 'DC', 'DC: BATMAN'),
('WARSHA', 'Warner Bros', 'Warner Bros: DARK SHADOWS'),
('WARSHG', 'DC', 'DC: DC SUPER HERO GIRLS'),
('WARSPG', 'DC', 'DC: SUPERGIRL'),
('WARSSQ', 'DC', 'DC: SUICIDE SQUAD'),
('WARSUC', 'Warner Bros', 'Warner Bros: SUCKER PUNCH'),
('WAR100', 'Warner Bros', 'Warner Bros: THE 100'),
('WAR300', 'Warner Bros', 'Warner Bros: 300: RISE OF AN EMPIRE'),
('WARBAT', 'DC', 'DC: BATMAN'),
('WARBIG', 'Warner Bros', 'Warner Bros: THE BIG BANG '),
('WARCAT', 'Warner Bros', 'Warner Bros: CATWOMAN'),
('WARDCC', 'Warner Bros', 'Warner Bros: SUPER FRIENDS'),
('WARDKR', 'DC', 'DC: DARK KNIGHT RISES'),
('WARDOH', 'Warner Bros', 'Warner Bros: DUKES OF HAZARD'),
('WARDOJ', 'DC', 'DC: BATMAN V SUPERMAN'),
('WARFAN', 'Warner Bros', 'Warner Bros: FANTASTIC BEASTS AND WHERE TO FIND THEM'),
('WARFLA', 'DC', 'DC: THE FLASH'),
('WARGOS', 'Warner Bros', 'Warner Bros: GOSSIP GIRL'),
('WARGOT', 'DC', 'DC: GOTHAM'),
('WARGRE', 'DC', 'DC: GREEN LANTERN'),
('WARHF2', 'Warner Bros', 'Warner Bros: HAPPY FEET'),
('WARHOB', 'Warner Bros', 'Warner Bros: THE HOBBIT'),
('WARHP5', 'Warner Bros', 'Warner Bros: HARRY POTTER'),
('WARJUS', 'DC', 'DC: JUSTICE LEAGUE'),
('WARLON', 'Warner Bros', 'Warner Bros: LOONY TUNES'),
('WAROVR', 'Warner Bros', 'Warner Bros: THE HANGOVER'),
('WARPLL', 'Warner Bros', 'Warner Bros: PRETTY LITTLE LIARS'),
('WARRED', 'Warner Bros', 'Warner Bros: RED RIDING HOOD'),
('WARSCO', 'Warner Bros', 'Warner Bros: SCOOBY'),
('WARSUP', 'DC', 'DC: SUPERMAN'),
('WARVAM', 'Warner Bros', 'Warner Bros: VAMPIRE DIARIES'),
('WARWON', 'DC', 'DC: WONDER WOMAN'),
('WARWOO', 'Warner Bros', 'Warner Bros: WIZARD OF OZ'),
('WARZIL', 'Warner Bros', 'Warner Bros: GODZILLA'),
('WARZOM', 'Warner Bros', 'Warner Bros: IZOMBIE'),
('WBLOTR', 'Warner Bros', 'Warner Bros: THE LORD OF THE RINGS'),
('FOXWIM', '20th Century Fox', 'DIARY OF A WIMPY KID'),
('LOCCAF', 'Keith Kimberlin','')
GO

SET ANSI_PADDING OFF
GO

/*
SELECT * FROM Odin_LicenseStats
*/
