SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE ODIN_EXCEL_LAYOUT_IDS
(  
    [LAYOUT_ID] int IDENTITY(1,1),
    [LAYOUT_NAME] VARCHAR(255),	
    [CUSTOMER] VARCHAR(255),
	[PRODUCT_TYPE] VARCHAR(255),
    PRIMARY KEY (LAYOUT_ID)
)
GO

SET ANSI_PADDING OFF
GO

GRANT SELECT, INSERT, UPDATE, DELETE ON ODIN_EXCEL_LAYOUT_IDS TO Odin
/*
ALTER TABLE [dbo].[ODIN_EXCEL_LAYOUT_IDS] ADD [PRODUCT_TYPE] VARCHAR(255) 
sp_help ODIN_EXCEL_LAYOUT_IDS
DROP TABLE ODIN_EXCEL_LAYOUT_IDS
SELECT * FROM ODIN_EXCEL_LAYOUT_IDS

INSERT INTO [ODIN_EXCEL_LAYOUT_IDS] VALUES (1, 'All Posters / Art.com', 'ALL POSTERS')
INSERT INTO [ODIN_EXCEL_LAYOUT_IDS] VALUES (2, 'Amazon Posters', 'AMAZON')
INSERT INTO [ODIN_EXCEL_LAYOUT_IDS] VALUES (3, 'Amazon Stickers & Stationery', 'AMAZON')
INSERT INTO [ODIN_EXCEL_LAYOUT_IDS] VALUES (4, 'Target Posters', 'TARGET')
INSERT INTO [ODIN_EXCEL_LAYOUT_IDS] VALUES (5, 'Walmart Calendars', 'WALMART')
INSERT INTO [ODIN_EXCEL_LAYOUT_IDS] VALUES (6, 'Walmart Posters', 'WALMART')
INSERT INTO [ODIN_EXCEL_LAYOUT_IDS] VALUES (7, 'TEST','','')

*/