
/****** Object:  Table [dbo].[ODIN_USER_OPTIONS]    Script Date: 11/25/2013 2:16:58 PM ******/
/*
DROP TABLE ODIN_USER_EXCEPTIONS
*/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE ODIN_USER_EXCEPTIONS(
	USERNAME varchar(18) NULL,
	EXCEPTION varchar(18) NULL,
)
GO

SET ANSI_PADDING OFF
GO

GRANT SELECT, INSERT, UPDATE, DELETE ON ODIN_USER_EXCEPTIONS TO Odin
/*
SELECT * FROM ODIN_USER_EXCEPTIONS
*/
