
/****** Object:  Table [dbo].[PS_INV_ITEMS]    Script Date: 11/25/2013 2:16:58 PM ******/
/*
DROP TABLE Odin_Web_Copyright
SELECT * FROM Odin_Web_Copyright
*/
DROP TABLE Odin_Web_Copyright
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE Odin_Web_Copyright(
	COPYRIGHT varchar(MAX) NULL,
	VALUE varchar(MAX) NULL
)
INSERT INTO Odin_Web_Copyright(COPYRIGHT, VALUE) 
VALUES 
		('A&E: Duck Dynasty','© 2015 A&E Television Networks, LLC. All rights reserved. Duck Dynasty, A&E and their associated logos are the trademarks of A&E Television Networks, LLC.  IF CAMO IS USED, ADD THIS AT END: Duck Camouflage Pattern design © 2015 A&E Television Networks, L'),
		('Abi Hall','© Abi Hall represted by Pink Light Studio'),
		('Activision: Call of Duty: Black Ops','© 2015 Activision Publishing, Inc. ACTIVISION, CALL OF DUTY, CALL OF DUTY BLACK OPS and stylized roman numeral II are trademarks of Activision Publishing, Inc.'),
		('Activision: Call of Duty: Ghosts','© 2015 Activision Publishing, Inc. ACTIVISION, CALL OF DUTY, and CALL OF DUTY GHOSTS are trademarks of Activision Publishing, Inc.'),
		('Activision: Call of Duty: Modern Warfare 3','© 2015 Activision Publishing, Inc. Activision and Modern Warfare are registered trademarks of Activision Publishing, Inc. All rights reserved.'),
		('Activision: Destiny','© 2015 Bungie, Inc. All rights reserved. Destiny, the Destiny logo, Bungie, and the Bungie Logo are trademarks of Bungie, Inc.  Activision is a registered trademark of Activision Publishing, Inc. '),
		('Activision: Skylanders','© 2015 Activision Publishing, Inc. SKYLANDERS and ACTIVISION are registered trademarks of Activision Publishing, Inc. '),
		('Activision: Skylanders Giants: Activision','SKYLANDERS GIANTS is a trademark, and ACTIVISION is a registered trademark of Activision Publishing, Inc. '),
		('Activision: Skylanders Swap Force: Activision','© 2015 Activision Publishing, Inc. SKYLANDERS SWAP FORCE is a trademark, and ACTIVISION is a registered trademark of Activision Publishing, Inc.'),
		('AMC: Breaking Bad','TM & © 2015 Sony Pictures Television Inc. All rights reserved.'),
		('Alan Hopfensperger','© 2011 Alan Hopfensperger Licensed by Out of the Blue'),
		('AMC: Walking Dead','The Walking Dead © 2015 AMC Film Holdings LLC.  All Rights Reserved. For more information about The Walking Dead, visit www.AMC.com/TheWalkingDead'),
		('Amylee Weeks','© Amylee Weeks. Courtesy of MHS Licensing.'),
		('Angry Birds: Rovio/Striker Entertainment','Angry Birds™ & © 2009 – 2015 Rovio Entertainment Ltd.  All Rights Reserved.'),
		('Arrolynn Weiderhold','© Arrolynn Weiderhold represented by Pink Light Studio'),
		('Attack on Titan','© Hajime Isayama, Kodansha/ATTACK ON TITAN." Licensed by/Autorisé par/Con licencia de Kodansha through/par/a través FUNimation® Productions'),
		('BBC: Planet Earth','BBC Earth and Planet Earth are trademarks of the BBC and are used under license. Planet Earth logo TM & © BBC 2006. BBC Logo © BBC 1996.'),
		('BCREATIVE INC.: Snorg Tees','© Snorgtees.com. License courtesy of bCreative.com.  '),
		('Beatles: General','© 2015 Apple Corps Ltd.  All rights reserved. A Beatles™ Product licensed by Apple Corps Ltd. “Beatles” is a trademark of Apple Corps Ltd. “Apple” and the Apple logo are exclusively licensed to Apple Corps Ltd.'),
		('Beatles: Yellow Submarine','© 2015 Subafilms Ltd.  A Yellow Submarine™ Product, ™ Trademark of Subafilms Ltd. © 1968, Authorized BEATLES™ Merchandise.'),
		('Bob Marley','BOB MARLEY® © Fifty-Six Hope Road Music Ltd, 2015 Right of Publicity and Persona Rights - Fifty-Six Hope Road Music Ltd. ALL PHOTOS © FIFTY-SIX HOPE ROAD MUSIC, LTD.  Published and marketed by Trends International, LLC under license. '),
		('Boo','Boo: Life of the World’s Cutest Dog. Photographs © 2014 by Gretchen LeMaistre. All rights reserved. First published by Chronicle Books LLC. www.chroniclebooks.com/Boo'),
		('Brandi Powell','© Brandi Powell represented by Pink Light Studio/représenté par Pink Light Studio/representada por Pink Light Studio'),
		('Buck Wear','© Buck Wear, Inc. Courtesy of MHS Licensing.'),
		('Candy Crush: STRIKER ENTERTAINMENT','© 2015 King.com Ltd.'),
		('Cartoon Network','TM © Cartoon Network'),
		('Cartoon Network: Adventure Time','TM & © Cartoon Network'),
		('Chris Vest','© 2013 Chris Vest. Licensed by Out of the Blue'),
		('Christian Riese Lassen','© Christian Riese Lassen'),
		('Classic Media Distribution Limited','© Classic Media Distribution Limited'),
		('Classic Tattoos','Artwork Copyright © 2013 Flash2xs.com, LLC (TattooFinder.com) and/or its Licensors. All Rights Reserved.'),
		('Connie Haley','© Connie Haley, Haley Art and Design 2015'),
		('DC Comics','TM & © DC Comics. (s15)'),
		('DC: Superman','SUPERMAN and all related characters and elements are trademarks of and © DC Comics.WB SHIELD: TM & © Warner Bros. Entertainment Inc.'),
		('DC: Wonder Woman','Wonder Woman and all related characters and elements are trademarks of and © DC Comics'),
		('Disney','© Disney disney.com'),
		('Disney Junior','© Disney www.DisneyJunior.com'),
		('Disney: Brave','© Disney/Pixar Pixar.com'),
		('Disney: Cars','© Disney/Pixar disney.com/cars'),
		('Disney: Fairies','© Disney  disneyfairies.com'),
		('Disney: Frozen','© Disney  Disney.com/Frozen'),
		('Disney: Mickey Mouse and Friends','© Mickey Mouse and Friends: DisneyDisney ney.com'),
		('Disney: Monsters University','© Disney/Pixar Pixar.com'),
		('Disney: Nightmare Before Christmas','© Disney disney.com'),
		('Disney: Palace Pets','© Disney  Visit DisneyPrincessPalacePets.com'),
		('Disney: Phineas & Ferb','© Disney disney.com/disneyxd'),
		('Disney: Pirates of the Caribbean','© Disney disney.com'),
		('Disney: Pixar','© Disney/Pixar'),
		('Disney: Pixar Calendar','© Disney/Pixar Pixar.com'),
		('Disney: Planes','© Disney Visit disney.com/planes.'),
		('Disney: Princess','© Disney www.disneyprincess.com'),
		('Disney: The Muppets','© Disney  disney.com/muppets'),
		('Disney: Toy Story','© Disney/Pixar www.toystory.com'),
		('Disney: Winnie the Pooh','© Disney. Based on the "Winnie the Pooh" works by A.A. Milne and E.H. Shepard. www.disney.com'),
		('Disney: Wizards of Waverly Place','© Disney  disneychannel.com'),
		('Dissero Brands Limited','© Dissero Brands Limited '),
		('Dreamworks','TM & © DWA'),
		('DreamWorks: How to Train Your Dragon','DreamWorks How To Train Your Dragon 2  © 2015 DreamWorks Animation L.L.C.'),
		('Evelia','© Evelia'),
		('Fault in our Stars','The Fault in Our Stars © 2014 Twentieth Century Fox Film Corporation. All Rights Reserved.'),
		('Flash2xs.com','Artwork Copyright © 2013 Flash2xs.com, LLC (TattooFinder.com) and/or its Licensors. All Rights Reserved.'),
		('Grumpy Cat','© ™ Grumpy Cat Limited'),
		('Harley-Davidson','Harley, Harley-Davidson and the Bar & Shield Logo are among the trademarks of H-D USA, LLC. © 2015. All Rights Reserved.  Produced by Trends International LLC under license from Harley-Davidson Motor Co.'),
		('Hasbro','© 2013 Hasbro'),
		('Hasbro: My Little Pony','HASBRO and its logo, MY LITTLE PONY and all related characters are trademarks of Hasbro and are used with permission. © 2014 Hasbro. All rights reserved.'),
		('Hasbro: Transformers','HASBRO and its logo, TRANSFORMERS, and all related characters are trademarks of Hasbro and are used with permission. © 2014 Hasbro. All Rights Reserved.'),
		('Hello Kitty: Sanrio','© 1976, 2015 SANRIO CO., LTD. Used Under License. www.sanrio.com'),
		('Hobbit','© WBEI™ Middle-earth Ent. Lic. to NLP '),
		('Hockey Canada','TM/MC © NHLPA/AJLNH TM/MC © ® Hockey Canada 2013 TM/MC © 2005-2013'),
		('Indiana University','The above trademarks are owned by the Trustees of Indiana University.'),
		('Jennifer Ellory','© Jennifer Ellory represented by Pink Light Studio'),
		('Jim Benton','© Jim Benton www.jimbenton.com'),
		('Jimi Hendrix: Authentic Hendrix','© Authentic Hendrix, LLC'),
		('John Block/Getty Images','© John Block/Getty Images'),
		('John Deere','© 1996–2014 Deere & Company. All Rights Reserved.'),
		('Joy Hall','© Joy Hall'),
		('Keith Kimberlin: Lo Coco Licensing','© 2015 Keith Kimberlin/Licensed by LoCocoLicensing.com'),
		('King.com','© 2015 King.com Ltd.'),
		('KingsIsle Entertainment','© 2014 KingsIsle Entertainment, Inc. All Rights Reserved. Tous droits réservés./Todos los derechos reservados.'),
		('LFL','© LFL'),
		('Louise Allen','© Louise Allen represented by Pink Light Studio'),
		('Louise Carey','© Louise Carey. Courtesy of MHS Licensing.'),
		('Marilyn Monroe: Authentic Brands Group','Marilyn Monroe™ and the Marilyn Monroe signature are trademarks of The Estate of Marilyn Monroe, LLC. Rights of Publicity and Persona Rights are used with permission of The Estate of Marilyn Monroe, LLC.'),
		('Marvel Entertainment','© MARVEL'),
		('Marvel: Spider-Man','MARVEL, Spider-Sense Spider-Man: TM & © 2011 Marvel Entertainment, LLC and its subsidiaries. Licensed by Marvel Characters B.V. All rights reserved. www.marvel.com'),
		('Mattel','© 2015 Mattel'),
		('Mattel: Barbie','BARBIE and associated trademarks and trade dress are owned by, and used under license from, Mattel. © 2013 Mattel. All Rights Reserved.'),
		('Mattel: Hot Wheels','HOT WHEELS and associated trademarks and trade dress are owned by, and used under license from, Mattel. © 2014 Mattel. All Rights Reserved.'),
		('Minecraft','© Notch. All Rights Reserved.'),
		('Mixels','MIXELS is a trademark of the LEGO Group, used here with permission. TM & © Cartoon Network.'),
		('MLB Logos & Stadiums','Trends International/MLBP'),
		('MLB Players','Trends International/MLBP © MLBPA. Official Licensee - Major League Baseball Players Association'),
		('MLB Players Only','TM/© MLBP © MLBPA. Official Licensee - Major League Baseball Players Association '),
		('Monster Jam: 4KIDS Entertainment','© 2015 Live Nation Motor Sports, Inc.'),
		('Muhammad Ali','The name, image, and likeness of Muhammad Ali are used with permission of Muhammad Ali Enterprises LLC. MUHAMMAD ALI and associated marks are trademarks of Muhammad Ali Enterprises LLC. © MAE LLC. George Kalinsky photographs. All rights reserved. '),
		('NBA: Calendars','The NBA and individual NBA member team identifications reproduced on this product are trademarks and copyrighted designs, and/or other forms of intellectual property, that are the exclusive property of NBA Properties, Inc. and the respective NBA member teams'),
		('NBA: Properties, Inc.','NBA.com © 2015 NBA Properties, Inc.'),
		('NFL: NFL League Logos','© 2015 NFL Properties LLC. Team names/logos are trademarks of the teams indicated. All other NFL-related trademarks are trademarks of the National Football League.'),
		('NFL: NFL Players Inc.','© 2015 NFLPI'),
		('NHL: Box Calendar','NHL, the NHL Shield, the word mark and image of the Stanley Cup and the NHL Winter Classic word mark are registered trademarks and Original Six is a trademark of the National Hockey League. All NHL logos and marks and NHL team logos and marks depicted here'),
		('NHL: Calendars: Hockey With Full NHLPA (Players)','NHL and the NHL Shield are registered trademarks of the National Hockey League. All NHL logos and marks and NHL team logos and marks depicted herein are the property of the NHL and the respective teams and may not be reproduced without the prior written consent.'),
		('NHL: Calendars: NHL Stoppers','NHL and the NHL Shield are registered trademarks and NHL Stoppers is a trademark of the National Hockey League. All NHL logos and marks and NHL team logos and marks depicted  herein are the property of the NHL and the respective teams and may not be repr'),
		('NHL: Players Association: Posters: Hockey Players','NHL and the NHL Shield are registered trademarks of the National Hockey League. NHL and NHL team marks are the property of the NHL and its teams. © NHL 2015. All Rights Reserved. © NHLPA/© AJLNH'),
		('NHL: Posters: Hockey Logos','NHL and the NHL Shield are registered trademarks of the National Hockey League. NHL and NHL team marks are the property of the NHL and its teams. © NHL 2015. All Rights Reserved.'),
		('NHL: Posters: Stanley Cup','NHL, the NHL Shield, and the word mark and image of the Stanley Cup are registered trademarks of the National Hockey League. NHL and NHL team marks are the property of the NHL and its teams. © NHL 2015. All Rights Reserved.'),
		('Nickelodeon: Dora the Explorer','© 2011 Viacom International Inc. All Rights Reserved. Nickelodeon, Dora the Explorer, and all related titles, logos and characters are trademarks of Viacom International Inc. www.NickJr.com'),
		('Nickelodeon: Go Diego Go','© 2012 Viacom International Inc. All Rights Reserved. Nickelodeon, Go Diego Go, and all related titles, logos and characters are trademarks of Viacom International Inc. © 2011 Viacom International Inc. All Rights Reserved. Nickelodeon, Dora the Explorer, '),
		('Nickelodeon: SpongeBob','© 2015 Viacom International Inc. All Rights Reserved. Nickelodeon, SpongeBob SquarePants, and all related titles, logos and characters are trademarks of Viacom International Inc. Created by Stephen Hillenburg.'),
		('Nickelodeon: TMNT','© 2015 Viacom Overseas Holdings C.V. All Rights Reserved. TEENAGE MUTANT NINJA TURTLES and all related titles, logos and characters are trademarks of Viacom Overseas Holding C.V.'),
		('Nina Seven','© Nina Seven represented by Pink Light Studio'),
		('Nintendo','TM & © 2015 Nintendo'),
		('None',''),
		('NRA','All National Rifle Association/NRA images and logos are trademarks of the National Rifle Association of America used under license. '),
		('One Direction: Global Merchandising','© 2015 1D Media Ltd Under License to Global Merchandising Services Ltd.'),
		('Orange is the New Black: Striker Entertainment','Series Artwork © 2015 Lions Gate Entertainment Inc. and Netflix Inc. Orange is the New Black is a trademark of Lions Gate Entertainment Inc. All Rights Reserved.'),
		('Pac-Man','PAC-MAN™ and the Ghostly Adventures & ©BANDAI NAMCO Games Inc.'),
		('Paw Patrol','TM Spin Master Ltd. All rights reserved./Tous droits réservés./Todos los derechos reservados.  © 2015 Spin Master PAW Productions Inc. Nickelodeon and all related titles, logos and characters are trademarks of Viacom International Inc'),
		('Peppa','Pig © Astley Baker Davies Ltd/Entertainment One UK Ltd 2003.'),
		('Pet Classics','© Pet Classics, Licensed by Creatif'),
		('Photo 24/Getty Images','© Photo 24/Getty Images'),
		('Pink Pueblo/TulipWorks','© Pink Pueblo/TulipWorks, LLC. Visit TulipWorks.com'),
		('Rachael Hale: Dissero Brands','© Dissero Brands Limited (New Zealand) 2015. All worldwide rights reserved. www.rachaelhale.com'),
		('Randalls Honey Badger','@Randall''s Honey Badger'),
		('Robin Pickens','© Robin Pickens 2010'),
		('Rolling Stone','All Rolling Stone posters come with a 12 issue subscription to Rolling Stone. Claim your Rolling Stone subscription(s) (one per poster) via the redemption certificate included with each poster ordered. Existing subscribers will be extended by 12 issues'),
		('Rouge','© Rouge'),
		('Sandra Vargas','© Sandra Vargas www.sandravargas-art.com'),
		('Scarface','Scarface is a trademark and copyright of Universal Studios. Licensed by Universal Studios Licensing LLC. All Rights Reserved.  A Note to Parents: Scarface is rated R. Consult http://www.filmratings.com for further information.'),
		('Scholastic: Goosebumps','GOOSEBUMPS and associated logos are trademarks of Scholastic Inc. Goosebumps, the Movie © 2015 Columbia Pictures Industries, Inc. All Rights Reserved.'),
		('Shopkins','© 2013 Moose. Shopkins™ logos, names and characters are licensed trademarks of Moose Enterprise Pty Ltd.'),
		('Smay Design','© 2013 Smay Design, Inc. Designed by Phil Yarnall / www.smaydesign.com'),
		('Smileyworld','© 1971-2015 The Smiley Company OR © SW'),
		('Smurfs','SMURFS ™ & © Peyo 2013. Licensed through Lafig Belgium/IMPS. The Smurfs 2, the Movie © 2013 Sony Pictures Animation Inc.and Columbia Pictures Industries, Inc. All Rights Reserved.'),
		('Sports Illustrated: Time Inc','Sports Illustrated® is a registered trademark of Time Inc. © 2015 Time Inc. All rights reserved.'),
		('Star Wars: Lucas Film','© & ™ Lucasfilm Ltd.'),
		('Stephen Fishwick - Albert Einstein Get Down Art','© Stephen Fishwick “It’s All Relative” Artist Interpretation. All Rights Reserved. www.stephenfishwick.com'),
		('SW','©SW'),
		('Terraria','TM & © 2011/2015 Re-Logic. '),
		('Thomas The Tank: Hit Entertainment','Based on the Railway Series by The Reverend W Awdry. © 2015 Gullane (Thomas) Limited. Thomas the Tank Engine & Friends and Thomas & Friends are trademarks of Gullane (Thomas) Limited. © HIT Entertainment Limited. HIT and the HIT logo are trademarks of HIT'),
		('Tim Coffey','© Tim Coffey'),
		('Tony Moore','© 2013 Tony Moore'),
		('Trends','© Trends'),
		('Turner Entertainment','TM & © Turner Entertainment Co.'),
		('Twisted Whiskers','Twisted Whiskers™ and related trademarks © 2014 Cloudco, Inc. Used under license by Trends International, LLC. American Greetings with rose logo is a trademark of AGC, LLC.'),
		('Ubisoft: Rabbids','© 2014 Ubisoft Entertainment. All Rights Reserved. Rabbids, Ubisoft, and the Ubisoft logo are trademarks of Ubisoft Entertainment in the U.S. and/or other countries.'),
		('Universal','TM & © Uni'),
		('Universal: Despicable Me','Despicable Me, Minion Made and all related marks and characters are trademarks and copyrights of Universal Studios. Licensed by Universal Studios Licensing LLC. All Rights Reserved.'),
		('Universal: Minions','Minions is a trademark and copyright of Universal Studios. Licensed by Universal Studios Licensing LLC. All rights reserved. '),
		('Valerie Foster','© Valerie Foster represented by Pink Light Studio/représenté par Pink Light Studio/representada por Pink Light Studio'),
		('Warner Bros','TM & © Warner Bros. Entertainment Inc.'),
		('Warner Bros: Big Bang Theory Star Trek','TM & © Warner Bros. Entertainment Inc. (s15)  TM & © 2015 CBS. ARR. '),
		('Warner Bros: Big Bang Theory','TM & © Warner Bros. Entertainment Inc. (s15)'),
		('Warner Bros: Batman','BATMAN and all related characters and elements are trademarks of and © DC Comics. WB SHIELD: TM & © Warner Bros. Entertainment Inc. (s15)   POSTERS ONLY: BATMAN: TM & © DC Comics. (s15) '),
		('Warner Bros: Batman The Brave And the Bold','BATMAN and all related characters and elements are trademarks of and © DC Comics. WB SHIELD: TM & © Warner Bros. Entertainment Inc. (s15)   POSTERS ONLY: BATMAN: TM & © DC Comics. (s15)'),
		('Warner Bros: Godzilla','TM & © Toho Co., Ltd. © Warner Bros. Entertainment Inc.WB SHIELD: TM & © Warner Bros. Entertainment Inc.'),
		('Warner Bros: Harry Potter','TM & © Warner Bros. Entertainment Inc. (s15)'),
		('Warner Bros: Superman','SUPERMAN and all related characters and elements are trademarks of and © DC Comics. WB SHIELD: TM & © Warner Bros. Entertainment Inc. (s15) '),
		('WWE','™ & © 2015 WWE. All Rights Reserved.')
GO

SET ANSI_PADDING OFF
GO