/*
SELECT * FROM Odin_UserRoles
drop table ODIN_USER_ROLES
ALTER TABLE Odin_UserRoles
ADD NOTIFICATION_NUM INT
UPDATE Odin_UserRoles SET NOTIFICATION_NUM = 0

*/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ODIN_USER_ROLES](
	[USER_NAME] [varchar](255) NOT NULL,
	[ROLE] [varchar](255) NOT NULL,
	[NOTIFICATION_NUMBER] [int]
)

GO

SET ANSI_PADDING OFF
GO

/*
INSERT INTO Odin_UserRoles
Values('BLEDBETTER','ADMIN')
DROP TABLE Odin_UserRoles
SELECT * FROM Odin_UserRoles
*/
/*
INSERT INTO ODIN_USER_ROLES
Values('BLEDBETTER','ADMIN',0)
INSERT INTO ODIN_USER_ROLES
Values('TSWEARINGIN','OPERATIONS')
INSERT INTO ODIN_USER_ROLES
Values('CSCOTT','MARKETING')
INSERT INTO ODIN_USER_ROLES
Values('AHOST','MARKETING')*/