SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ODIN_ITEM_TYPE_SUFFIXES]
(  
    [FIELD_VALUE] VARCHAR(24),
	[TYPE] VARCHAR(6)
)
GO

SET ANSI_PADDING OFF
GO

/*
SELECT * FROM ODIN_ITEM_TYPE_SUFFIXES
INSERT INTO [ODIN_ITEM_TYPE_SUFFIXES] VALUES ('BLK22X34', 'SUF')
INSERT INTO [ODIN_ITEM_TYPE_SUFFIXES] VALUES ('SIL22X34', 'SUF')
INSERT INTO [ODIN_ITEM_TYPE_SUFFIXES] VALUES ('POD', 'PRE')
*/
GRANT SELECT, INSERT, UPDATE, DELETE ON ODIN_ITEM_TYPE_SUFFIXES TO Odin
