SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PS_BU_ITEM_UTIL_CD](
	[BUSINESS_UNIT] [char](5) NOT NULL,
	[INV_ITEM_ID] [char](18) NOT NULL,
	[UTILIZ_GROUP] [char](4) NOT NULL,
	[UTILIZ_CD] [char](4) NOT NULL,
	[PLANNING_FLG] [char](1) NOT NULL
)

GO

SET ANSI_PADDING OFF
GO

