SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PS_BU_ITEMS_CONFIG](
	[BUSINESS_UNIT] [char](5) NOT NULL,
	[INV_ITEM_ID] [char](18) NOT NULL,
	[RULE_BASED_COMP] [char](1) NOT NULL,
	[RULE_BASED_OPER] [char](1) NOT NULL,
	[REF_BOM_ITEM] [char](18) NOT NULL,
	[CFG_LEAD_TIME] [decimal](11, 2) NOT NULL,
	[SHIP_TYPE_ID] [char](10) NOT NULL,
	[BUSINESS_UNIT_CP] [char](5) NOT NULL,
	[LASTUPDDTTM] [dbo].[PSDATETIME] NULL
)

GO

SET ANSI_PADDING OFF
GO

