/*
ALTER TABLE PS_CUSTOMER_PRODUCT_ATTRIBUTES ADD [IS_EXCLUSIVE] VARCHAR(1) DEFAULT 'N'
SELECT * FROM PS_CUSTOMER_PRODUCT_ATTRIBUTES
*/
sp_help PS_CUSTOMER_PRODUCT_ATTRIBUTES
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PS_CUSTOMER_PRODUCT_ATTRIBUTES]
(
	[SETID] VARCHAR(5) NOT NULL,
	[PRODUCT_ID] VARCHAR(18) NOT NULL,
	[CUST_ID] VARCHAR(15) NOT NULL,
	[INNERPACK_QTY] INT CONSTRAINT DEFAULT_INNERPACK_QTY DEFAULT 0,
	[CASEPACK_QTY] INT CONSTRAINT DEFAULT_CASEPACK_QTY DEFAULT 0,
	[SEND_INVENTORY] VARCHAR(1) CONSTRAINT DEFAULT_SEND_INVENTORY DEFAULT 'N'
	[IS_EXCLUSIVE] VARCHAR(1) CONSTRAINT DEFAULT_IS_EXCLUSIVE DEFAULT 'N'
	PRIMARY KEY CLUSTERED
	(
		[SETID],
		[PRODUCT_ID],
		[CUST_ID]
	)
)
GO

SET ANSI_PADDING OFF
GO

GRANT SELECT, INSERT, UPDATE ON PS_CUSTOMER_PRODUCT_ATTRIBUTES TO Odin