SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PS_COUNTRY_TBL](
	[COUNTRY] [char](3) NOT NULL,
	[DESCR] [char](30) NOT NULL,
	[DESCRSHORT] [char](10) NOT NULL,
	[COUNTRY_2CHAR] [char](2) NOT NULL,
	[EU_MEMBER_STATE] [char](1) NOT NULL,
	[ADDR1_LBL] [char](15) NOT NULL,
	[ADDR1_AVAIL] [char](1) NOT NULL,
	[ADDR2_LBL] [char](15) NOT NULL,
	[ADDR2_AVAIL] [char](1) NOT NULL,
	[ADDR3_LBL] [char](15) NOT NULL,
	[ADDR3_AVAIL] [char](1) NOT NULL,
	[ADDR4_LBL] [char](15) NOT NULL,
	[ADDR4_AVAIL] [char](1) NOT NULL,
	[CITY_LBL] [char](15) NOT NULL,
	[CITY_AVAIL] [char](1) NOT NULL,
	[NUM1_LBL] [char](15) NOT NULL,
	[NUM1_AVAIL] [char](1) NOT NULL,
	[NUM2_LBL] [char](15) NOT NULL,
	[NUM2_AVAIL] [char](1) NOT NULL,
	[HOUSE_TYPE_LBL] [char](15) NOT NULL,
	[HOUSE_TYPE_AVAIL] [char](1) NOT NULL,
	[ADDR_FIELD1_LBL] [char](15) NOT NULL,
	[ADDR_FIELD1_AVAIL] [char](1) NOT NULL,
	[ADDR_FIELD2_LBL] [char](15) NOT NULL,
	[ADDR_FIELD2_AVAIL] [char](1) NOT NULL,
	[ADDR_FIELD3_LBL] [char](15) NOT NULL,
	[ADDR_FIELD3_AVAIL] [char](1) NOT NULL,
	[COUNTY_LBL] [char](15) NOT NULL,
	[COUNTY_AVAIL] [char](1) NOT NULL,
	[STATE_LBL] [char](15) NOT NULL,
	[STATE_AVAIL] [char](1) NOT NULL,
	[POSTAL_LBL] [char](15) NOT NULL,
	[POSTAL_AVAIL] [char](1) NOT NULL,
	[IN_CITY_LIM_AVAIL] [char](1) NOT NULL,
	[IN_CITY_LIM_LBL] [char](15) NOT NULL,
	[GEO_CODE_AVAIL] [char](1) NOT NULL,
	[GEO_CODE_LBL] [char](15) NOT NULL,
	[POST_SRCH_AVAIL] [char](1) NOT NULL,
	[GBSYS_NRPATH_UK] [char](254) NOT NULL,
	[GBSYS_CFGPATH_UK] [char](254) NOT NULL,
	[SYNCID] [int] NULL,
	[SYNCDTTM] [dbo].[PSDATETIME] NULL
)

GO

SET ANSI_PADDING OFF
GO

