/****** Object:  Table [dbo].[PS_EN_BOM_OUTPUTS]    Script Date: 8/21/2018 7:41:10 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PS_EN_BOM_OUTPUTS](
	[BUSINESS_UNIT] [char](5) NOT NULL,
	[INV_ITEM_ID] [char](18) NOT NULL,
	[BOM_STATE] [char](2) NOT NULL,
	[BOM_TYPE] [char](2) NOT NULL,
	[BOM_CODE] [smallint] NOT NULL,
	[MG_OUTPUT_TYPE] [char](2) NOT NULL,
	[MG_OUTPUT_ITEM] [char](18) NOT NULL,
	[OP_SEQUENCE] [smallint] NOT NULL,
	[DATE_IN_EFFECT] [dbo].[PSDATE] NOT NULL,
	[DATE_OBSOLETE] [dbo].[PSDATE] NOT NULL,
	[MG_OUTPUT_QTY] [decimal](11, 4) NOT NULL,
	[MG_OUTPUT_QTY_CODE] [char](3) NOT NULL,
	[MG_OUTPUT_RES_PCT] [smallint] NOT NULL,
	[MG_OUTPUT_COST_PCT] [smallint] NOT NULL,
	[INCR_REL_TYPE] [char](1) NOT NULL,
	[INCR_REL_OFFSET] [decimal](15, 4) NOT NULL
)

GO

SET ANSI_PADDING OFF
GO


