SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PS_HRMN_TARIFF_CD](
	[SETID] [char](5) NOT NULL,
	[HARMONIZED_CD] [char](14) NOT NULL,
	[EFFDT] [dbo].[PSDATE] NOT NULL,
	[EFF_STATUS] [char](1) NOT NULL,
	[DESCR] [char](30) NOT NULL,
	[DESCRSHORT] [char](10) NOT NULL
)

GO

SET ANSI_PADDING OFF
GO

