
/****** Object:  Table [dbo].[PS_ITEM_WEB_INFO]    Script Date: 4/5/2017 1:51:17 PM ******/

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PS_ITEM_WEB_INFO](
	[INV_ITEM_ID] [varchar](18) NOT NULL,
	[IN_STOCK_DATE] [dbo].[PSDATETIME] NULL,
	[ITEM_KEYWORDS] [varchar](max) NOT NULL,
	[CATEGORY] [varchar](max) NULL,
	[COPYRIGHT] [varchar](max) NULL,
	[MSRP] [varchar](10) NULL,
	[TITLE] [varchar](266) NULL,
	[ACTIVE] [int] NULL,
	[LICENSE] [varchar](255) NULL,
	[ATTRIBUTE_SET] [varchar](255) NULL,
	[SHORT_DESC] [varchar](max) NULL,
	[NEWCATEGORY] [varchar](255) NULL,
	[META_DESCRIPTION] [varchar](255) NULL,
	[NEW_DATE] [varchar](25) NULL,
	[WARRANTY] [varchar](max) NULL,
	[WARRANTY_CHECK] VARCHAR(1) 
)
SET ANSI_PADDING OFF
/*
ALTER TABLE [dbo].[PS_ITEM_WEB_INFO] ADD [WARRANTY] [varchar](max) NULL
ALTER TABLE [dbo].[PS_ITEM_WEB_INFO] ADD [WARRANTY_CHECK] VARCHAR(1) 
ALTER TABLE [dbo].[PS_ITEM_WEB_INFO] ADD [PROPERTY] [varchar](max) NULL
SET ANSI_PADDING ON
ALTER TABLE [dbo].[PS_ITEM_WEB_INFO] ADD [SIZE] [varchar](266) NULL
ALTER TABLE [dbo].[PS_ITEM_WEB_INFO] ADD [PROD_QTY] [varchar](266) NULL
ALTER TABLE [dbo].[PS_ITEM_WEB_INFO] ADD [IMAGE_PATH] VARCHAR(254) 

ALTER TABLE [dbo].[PS_ITEM_WEB_INFO] ADD [ON_SITE] VARCHAR(1) 
ALTER TABLE [dbo].[PS_ITEM_WEB_INFO] ADD CONSTRAINT DF_WebInfoOnSite DEFAULT 'N' FOR ON_SITE
*/
GO

SET ANSI_PADDING OFF
GO
/*
SELECT * FROM [PS_ITEM_WEB_INFO]
*/
/*
ALTER TABLE PS_ITEM_WEB_INFO DROP COLUMN [LANGUAGE]
ALTER TABLE PS_ITEM_WEB_INFO DROP COLUMN TERRITORY
ALTER TABLE PS_ITEM_WEB_INFO DROP COLUMN RELATED_PRODUCTS
*/