
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PS_INV_ITEM_GROUP](
	[SETID] [char](5) NOT NULL,
	[INV_ITEM_GROUP] [char](15) NOT NULL,
	[EFFDT] [dbo].[PSDATE] NOT NULL,
	[EFF_STATUS] [char](1) NOT NULL,
	[DESCR] [char](30) NOT NULL,
	[DESCRSHORT] [char](10) NOT NULL
)

GO
CREATE UNIQUE CLUSTERED INDEX IDX_INV_ITEM_GROUP
	on PS_INV_ITEM_GROUP(SETID, INV_ITEM_GROUP, EFFDT);

SET ANSI_PADDING OFF
GO

