SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PS_INV_ITEM_UOM](
	[SETID] [char](5) NOT NULL,
	[INV_ITEM_ID] [char](18) NOT NULL,
	[UNIT_OF_MEASURE] [char](3) NOT NULL,
	[CONVERSION_RATE] [decimal](15, 8) NOT NULL,
	[QTY_PRECISION] [char](1) NOT NULL,
	[ROUND_RULE] [char](1) NOT NULL,
	[DFLT_UOM_STOCK] [char](1) NOT NULL,
	[LAST_DTTM_UPDATE] [dbo].[PSDATETIME] NULL,
	[LAST_MAINT_OPRID] [char](30) NOT NULL,
	[PACKING_WEIGHT] [decimal](15, 4) NOT NULL,
	[PACKING_VOLUME] [decimal](15, 4) NOT NULL,
	[SHIPPING_WEIGHT] [decimal](15, 4) NOT NULL,
	[SHIPPING_VOLUME] [decimal](15, 4) NOT NULL,
	[UNIT_MEASURE_WT] [char](3) NOT NULL,
	[UNIT_MEASURE_VOL] [char](3) NOT NULL,
	[PACKING_CD] [char](4) NOT NULL,
	[PACKAGING_CD] [char](4) NOT NULL,
	[CONTAINER_TYPE] [char](4) NOT NULL
)

GO

SET ANSI_PADDING OFF
GO

