
/*
SELECT TOP 10 * FROM [PS_ITEM_ATTRIB_EX]
 ALTER TABLE [PS_ITEM_ATTRIB_EX] ADD [SELL_ON_TARGET] VARCHAR(1)
 ALTER TABLE [PS_ITEM_ATTRIB_EX] ADD [SELL_ON_ECOM] VARCHAR(1)

*/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [Odin].[dbo].[PS_ITEM_ATTRIB_EX](
	[SETID] [char](5) NOT NULL,
	[INV_ITEM_ID] [char](18) NOT NULL,
	[PROD_GROUP] [varchar](30) NOT NULL CONSTRAINT [DF_PROD_GROUP]  DEFAULT (''),
	[PROD_LINE] [varchar](30) NOT NULL CONSTRAINT [DF_PROD_LINE]  DEFAULT (''),
	[PROD_FORMAT] [varchar](60) NOT NULL CONSTRAINT [DF_PROD_FORMAT]  DEFAULT (''),
	[CASEPACK_HEIGHT] [decimal](5, 2) NOT NULL,
	[CASEPACK_LENGTH] [decimal](5, 2) NOT NULL,
	[CASEPACK_WIDTH] [decimal](5, 2) NOT NULL,
	[CASEPACK_WEIGHT] [decimal](7, 2) NOT NULL,
	[CASEPACK_QTY] [smallint] NOT NULL,
	[CASEPACK_UPC] [varchar](12) NOT NULL CONSTRAINT [DF_CASEPACK_UPC]  DEFAULT (''),
	[INNERPACK_HEIGHT] [decimal](5, 2) NOT NULL,
	[INNERPACK_LENGTH] [decimal](5, 2) NOT NULL,
	[INNERPACK_WIDTH] [decimal](5, 2) NOT NULL,
	[INNERPACK_WEIGHT] [decimal](7, 2) NOT NULL,
	[INNERPACK_QTY] [smallint] NOT NULL,
	[INNERPACK_UPC] [varchar](12) NOT NULL CONSTRAINT [DF_INNERPACK_UPC]  DEFAULT (''),
	[BOX_ITEM_GROUP] [varchar](15) NOT NULL CONSTRAINT [DF_BOX_ITEM_GROUP]  DEFAULT (''),
	[DIRECT_IMPORT] [char](1) NOT NULL CONSTRAINT [DF_DIRECT_IMPORT]  DEFAULT ('N'),
	[LICENSE_BEGIN_DATE] [dbo].[PSDATE] NULL,
	[GTIN] [varchar](14) NOT NULL CONSTRAINT [DF_GTIN]  DEFAULT (''),
	[DUTY] [varchar](30) NOT NULL CONSTRAINT [DF_DUTY]  DEFAULT (''),
	[PRINT_ON_DEMAND] [char](1) NOT NULL CONSTRAINT [DF_PRINT_ON_DEMAND_1]  DEFAULT ('N'),
	[SELL_ON_AMAZON] [char](1) NOT NULL CONSTRAINT [DF_SELL_ON_AMAZON]  DEFAULT ('N'),
	[SELL_ON_FANATICS] [char](1) NOT NULL CONSTRAINT [DF_SELL_ON_FANATICS]  DEFAULT ('N'),
	[SELL_ON_JET] [char](1) NOT NULL CONSTRAINT [DF_SELL_ON_JET]  DEFAULT ('N'),
	[SELL_ON_TARGET] [char](1) NOT NULL CONSTRAINT [DF_SELL_ON_TARGET]  DEFAULT ('N'),
	[SELL_ON_WEB] [char](1) NOT NULL CONSTRAINT [DF_SELL_ON_WEB]  DEFAULT ('N'),
	[SELL_ON_WALMART] [char](1) NOT NULL CONSTRAINT [DF_SELL_ON_WALMART]  DEFAULT ('N'),
	[TRANSLATE_EDI_PROD] [char](1) NOT NULL CONSTRAINT [DF_TRANSLATE_EDI_PROD]  DEFAULT ('N')
)

GO

SET ANSI_PADDING OFF
GO
/*
SELECT * FROM PS_ITEM_ATTRIB_EX

ALTER TABLE PS_ITEM_ATTRIB_EX
ADD CONSTRAINT WebsitePrice_Default
DEFAULT 0.00 FOR WEBSITE_PRICE

*/

