
/****** Object:  Table [dbo].[PS_INV_ITEMS]    Script Date: 11/25/2013 2:16:58 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PS_INV_ITEMS](
	[SETID] [char](5) NOT NULL,
	[INV_ITEM_ID] [char](18) NOT NULL,
	[EFFDT] [dbo].[PSDATE] NOT NULL,
	[UPC_ID] [char](18) NOT NULL,
	[POTENCY_RATING] [char](4) NOT NULL,
	[INV_ITEM_TEMPLATE] [char](5) NOT NULL,
	[INV_ITEM_TYPE] [char](5) NOT NULL,
	[RECYCLE_FLAG] [char](1) NOT NULL,
	[REUSABLE_FLAG] [char](1) NOT NULL,
	[DISPOSABLE_FLAG] [char](1) NOT NULL,
	[INV_STOCK_TYPE] [char](4) NOT NULL,
	[PACKING_CD] [char](4) NOT NULL,
	[STOR_RULES_ID] [char](4) NOT NULL,
	[SHIP_TYPE_ID] [char](10) NOT NULL,
	[RECOM_STOR_TEMP] [decimal](5, 2) NOT NULL,
	[RECOM_HUMIDITY_PCT] [decimal](5, 2) NOT NULL,
	[INV_PROD_GRADE] [char](4) NOT NULL,
	[MAX_CAPACITY] [decimal](15, 4) NOT NULL,
	[HAZ_CLASS_CD] [char](4) NOT NULL,
	[INTL_HAZARD_ID] [char](15) NOT NULL,
	[CHARGE_CODE] [char](20) NOT NULL,
	[SHELF_LIFE] [smallint] NOT NULL,
	[AVAIL_STATUS] [char](1) NOT NULL,
	[INV_ITEM_HEIGHT] [decimal](15, 4) NOT NULL,
	[INV_ITEM_LENGTH] [decimal](15, 4) NOT NULL,
	[INV_ITEM_WIDTH] [decimal](15, 4) NOT NULL,
	[INV_ITEM_WEIGHT] [decimal](15, 4) NOT NULL,
	[INV_ITEM_VOLUME] [decimal](15, 4) NOT NULL,
	[INV_ITEM_SIZE] [char](5) NOT NULL,
	[INV_ITEM_COLOR] [char](10) NOT NULL,
	[UNIT_MEASURE_DIM] [char](3) NOT NULL,
	[UNIT_MEASURE_WT] [char](3) NOT NULL,
	[UNIT_MEASURE_TEMP] [char](3) NOT NULL,
	[UNIT_MEASURE_VOL] [char](3) NOT NULL,
	[COMMODITY_CD] [char](10) NOT NULL,
	[HARMONIZED_CD] [char](14) NOT NULL,
	[MSDS_ID] [char](10) NOT NULL,
	[LAST_MAINT_OPRID] [char](30) NOT NULL,
	[LAST_DTTM_UPDATE] [dbo].[PSDATETIME] NULL,
	[DESCR254] [char](254) NOT NULL,
	[COMMODITY_CD_EU] [char](9) NOT NULL,
	[AVAIL_LEAD_TIME] [smallint] NOT NULL,
	[RETEST_LEAD_TIME] [smallint] NOT NULL,
	[CHARGE_MARKUP_PCNT] [decimal](14, 2) NOT NULL,
	[CHARGE_MARKUP_AMT] [decimal](15, 4) NOT NULL,
	[CONSUMABLE_FLG] [char](1) NOT NULL,
	[RETURNABLE_FLG] [char](1) NOT NULL,
	[SERVICEABLE_FLG] [char](1) NOT NULL,
	[SERVICE_PRICE] [decimal](20, 5) NOT NULL,
	[SERVICE_EXCH_AMT] [decimal](20, 5) NOT NULL,
	[CURRENCY_CD] [char](3) NOT NULL
)

GO
CREATE UNIQUE CLUSTERED INDEX IDX_INV_ITEMS
	on PS_INV_ITEMS(SETID, INV_ITEM_ID, EFFDT);

SET ANSI_PADDING OFF
GO

