/*
SELECT * FROM PS_PRODUCT_ATTRIBUTES
sp_help PS_PRODUCT_ATTRIBUTES
*/

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [PS_PRODUCT_ATTRIBUTES]
(
    [SETID] VARCHAR(5) NOT NULL,
    [PRODUCT_ID] VARCHAR(18) NOT NULL,
    [ATTRIBUTE_TYPE] VARCHAR(50) NOT NULL,
    [ATTRIBUTE_VALUE] VARCHAR(100) NOT NULL,
    [USER_ID] VARCHAR(50) NOT NULL,
    [TIMESTAMP] DATETIME NOT NULL,
    PRIMARY KEY ([SETID], [PRODUCT_ID], [ATTRIBUTE_TYPE])
)

GO

SET ANSI_PADDING OFF
GO

GRANT SELECT, INSERT, UPDATE ON [PS_PRODUCT_ATTRIBUTES] TO [Odin]
GO