SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PS_PL_ITEM_ATTRIB](
	[BUSINESS_UNIT] [char](5) NOT NULL,
	[INV_ITEM_ID] [char](18) NOT NULL,
	[RESCH_OUT_FACTOR] [decimal](7, 2) NOT NULL,
	[RESCH_IN_FACTOR] [decimal](7, 2) NOT NULL,
	[DEMAND_FENCE_OF] [decimal](7, 2) NOT NULL,
	[PLAN_FENCE_OFF] [decimal](7, 2) NOT NULL,
	[PLAN_HORIZON] [decimal](7, 2) NOT NULL,
	[TRANSFER_MIN_ORDER] [decimal](11, 4) NOT NULL,
	[TRANSFER_MAX_ORDER] [decimal](11, 4) NOT NULL,
	[TRANS_ORD_MULTIPLE] [decimal](11, 4) NOT NULL,
	[TRANSFER_ORD_MOD] [char](1) NOT NULL,
	[PUR_MIN_ORDER] [decimal](11, 4) NOT NULL,
	[PUR_MAX_ORDER] [decimal](11, 4) NOT NULL,
	[PUR_ORDER_MULTIPLE] [decimal](11, 4) NOT NULL,
	[PUR_ORDER_MOD] [char](1) NOT NULL,
	[MFG_MOD_UNIT] [char](4) NOT NULL,
	[MFG_MIN_ORDER] [decimal](11, 4) NOT NULL,
	[MFG_MAX_ORDER] [decimal](11, 4) NOT NULL,
	[MFG_ORDER_MULTIPLE] [decimal](11, 4) NOT NULL,
	[MFG_ORDER_MOD] [char](1) NOT NULL,
	[MFG_LEAD_TIME_FLAG] [char](1) NOT NULL,
	[SAFETY_LEVEL] [decimal](15, 4) NOT NULL,
	[EXCESS_LEVEL] [decimal](15, 4) NOT NULL,
	[AUTO_APPROVE_MSG] [char](1) NOT NULL,
	[PLANNER_CD] [char](12) NOT NULL,
	[PURCHASE_YIELD] [decimal](4, 1) NOT NULL,
	[TRANSFER_YIELD] [decimal](4, 1) NOT NULL,
	[SALES_CONSUMP] [char](1) NOT NULL,
	[PROD_CONSUMP] [char](1) NOT NULL,
	[TRANS_CONSUMP] [char](1) NOT NULL,
	[MSR_CONSUMP] [char](1) NOT NULL,
	[EXTRA_CONSUMP] [char](1) NOT NULL,
	[PL_AGG_DMD_FLAG] [char](1) NOT NULL,
	[RELEASED_ORDER] [smallint] NOT NULL,
	[FIRMED_ORDER] [smallint] NOT NULL,
	[PL_PRIO_FAMILY] [char](10) NOT NULL,
	[USE_SHIPTO_LOC] [char](1) NOT NULL,
	[PL_FIXED_PERIOD] [smallint] NOT NULL,
	[PL_ITEM_EXPL] [char](1) NOT NULL,
	[PL_PROJ_USE_DT] [dbo].[PSDATE] NULL,
	[PLANNED_BY] [char](1) NOT NULL,
	[CAP_FENCE_OFF] [int] NOT NULL,
	[FCST_FULFILL_SIZE] [decimal](11, 4) NOT NULL,
	[FCST_ADJ_ACTION] [char](1) NOT NULL,
	[EARLY_FENCE] [int] NOT NULL,
	[GBL_EARLY_FENCE] [char](1) NOT NULL,
	[PL_SEARCH_DEPTH] [smallint] NOT NULL,
	[SPOT_BUY_FLG] [char](1) NOT NULL
)

GO

SET ANSI_PADDING OFF
GO

