SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PS_PROD_GROUP_TBL](
	[SETID] [char](5) NOT NULL,
	[PROD_GRP_TYPE] [char](4) NOT NULL,
	[PRODUCT_GROUP] [char](10) NOT NULL,
	[EFFDT] [dbo].[PSDATE] NOT NULL,
	[DESCR] [char](30) NOT NULL,
	[EFF_STATUS] [char](1) NOT NULL,
	[WEB_OE_PROD_CAT] [char](4) NOT NULL,
	[DESCRSHORT] [char](10) NOT NULL,
	[GLOBAL_FLAG] [char](1) NOT NULL,
	[DATETIME_ADDED] [dbo].[PSDATETIME] NULL,
	[LASTUPDDTTM] [dbo].[PSDATETIME] NULL,
	[LAST_MAINT_OPRID] [char](30) NOT NULL
)

GO

SET ANSI_PADDING OFF
GO

