SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PS_PROD_ITEM](
	[SETID] [char](5) NOT NULL,
	[PRODUCT_ID] [char](18) NOT NULL,
	[DESCR] [char](30) NOT NULL,
	[PRODUCT_USE] [char](1) NOT NULL,
	[MODEL_NBR] [char](18) NOT NULL,
	[CATALOG_NBR] [char](18) NOT NULL,
	[TAX_PRODUCT_NBR] [char](18) NOT NULL,
	[TAX_TRANS_TYPE] [char](1) NOT NULL,
	[TAX_TRANS_SUB_TYPE] [char](1) NOT NULL,
	[PRODUCT_KIT_FLAG] [char](1) NOT NULL,
	[EFF_STATUS] [char](1) NOT NULL,
	[INV_ITEM_ID] [char](18) NOT NULL,
	[DROP_SHIP_FLAG] [char](1) NOT NULL,
	[COMM_FLAG] [char](1) NOT NULL,
	[COMM_PCT] [decimal](5, 2) NOT NULL,
	[UPPER_MARGIN_PCT] [decimal](5, 2) NOT NULL,
	[LOWER_MARGIN_PCT] [decimal](5, 2) NOT NULL,
	[HOLD_UPDATE_SW] [char](1) NOT NULL,
	[BUSINESS_UNIT_PC] [char](5) NOT NULL,
	[PROJECT_ID] [char](15) NOT NULL,
	[ACTIVITY_ID] [char](15) NOT NULL,
	[COST_ELEMENT] [char](4) NOT NULL,
	[EXPORT_LIC_REQ] [char](3) NOT NULL,
	[FORECAST_ITEM_FLAG] [char](1) NOT NULL,
	[RETURN_FLAG] [char](1) NOT NULL,
	[DESCR254] [char](254) NOT NULL,
	[CFG_KIT_FLAG] [char](1) NOT NULL,
	[CFG_CODE_OPT] [char](1) NOT NULL,
	[CP_TEMPLATE_ID] [char](10) NOT NULL,
	[CP_TREE_DIST] [char](18) NOT NULL,
	[PHYSICAL_NATURE] [char](1) NOT NULL,
	[PRICE_KIT_FLAG] [char](1) NOT NULL,
	[PROD_BRAND] [char](15) NOT NULL,
	[PROD_CATEGORY] [char](15) NOT NULL,
	[THIRD_PARTY_FLG] [char](1) NOT NULL,
	[RENEWABLE] [char](1) NOT NULL,
	[PRICING_STRUCTURE] [char](4) NOT NULL,
	[PERCENTAGE] [decimal](5, 2) NOT NULL,
	[APPLIES_TO] [char](4) NOT NULL,
	[REV_RECOG_METHOD] [char](4) NOT NULL,
	[CA_BP_TMPL_ID] [char](10) NOT NULL,
	[BP_DTL_TMPL_ID] [char](10) NOT NULL,
	[RNW_TEMPLATE_ID] [char](10) NOT NULL,
	[CA_AP_TMPL_ID] [char](10) NOT NULL,
	[PROD_FIELD_C1_A] [char](1) NOT NULL,
	[PROD_FIELD_C1_B] [char](1) NOT NULL,
	[PROD_FIELD_C1_C] [char](1) NOT NULL,
	[PROD_FIELD_C1_D] [char](1) NOT NULL,
	[PROD_FIELD_C10_A] [char](10) NOT NULL,
	[PROD_FIELD_C10_B] [char](10) NOT NULL,
	[PROD_FIELD_C10_C] [char](10) NOT NULL,
	[PROD_FIELD_C10_D] [char](10) NOT NULL,
	[PROD_FIELD_C2] [char](2) NOT NULL,
	[PROD_FIELD_C30_A] [char](30) NOT NULL,
	[PROD_FIELD_C30_B] [char](30) NOT NULL,
	[PROD_FIELD_C30_C] [char](30) NOT NULL,
	[PROD_FIELD_C30_D] [char](30) NOT NULL,
	[PROD_FIELD_C4] [char](4) NOT NULL,
	[PROD_FIELD_C6] [char](6) NOT NULL,
	[PROD_FIELD_C8] [char](8) NOT NULL,
	[PROD_FIELD_N12_A] [decimal](15, 3) NOT NULL,
	[PROD_FIELD_N12_B] [decimal](15, 3) NOT NULL,
	[PROD_FIELD_N12_C] [decimal](15, 3) NOT NULL,
	[PROD_FIELD_N12_D] [decimal](15, 3) NOT NULL,
	[PROD_FIELD_N15_A] [decimal](15, 0) NOT NULL,
	[PROD_FIELD_N15_B] [decimal](15, 0) NOT NULL,
	[PROD_FIELD_N15_C] [decimal](15, 0) NOT NULL,
	[PROD_FIELD_N15_D] [decimal](15, 0) NOT NULL,
	[VAT_SVC_PERFRM_FLG] [char](1) NOT NULL,
	[DATETIME_ADDED] [dbo].[PSDATETIME] NULL,
	[LASTUPDDTTM] [dbo].[PSDATETIME] NULL,
	[LAST_MAINT_OPRID] [char](30) NOT NULL
)

GO

SET ANSI_PADDING OFF
GO

