SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PS_PROD_CATGRY_TBL](
	[SETID] [char](5) NOT NULL,
	[PROD_CATEGORY] [char](15) NOT NULL,
	[EFFDT] [dbo].[PSDATE] NOT NULL,
	[EFF_STATUS] [char](1) NOT NULL,
	[DESCR] [char](30) NOT NULL,
	[DESCRSHORT] [char](10) NOT NULL
)

GO

SET ANSI_PADDING OFF
GO

