/*
SELECT * FROM PS_ITEM_WEB_INFO
DROP TABLE PS_ITEM_WEB_INFO

SELECT * FROM PS_ITEM_WEB_INFO

ALTER TABLE PS_ITEM_WEB_INFO
ADD MSRP varchar(10)

ALTER TABLE PS_ITEM_WEB_INFO
ADD TITLE varchar(266)

UPDATE PS_ITEM_WEB_INFO
SET MSRP=''

*/

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PS_ITEM_WEB_INFO](
	[INV_ITEM_ID] [varchar](18) NOT NULL,
	[LANGUAGE] [varchar](18) NOT NULL,
	[IN_STOCK_DATE] [dbo].[PSDATETIME] NULL,
	[ITEM_KEYWORDS] [varchar](MAX) NOT NULL,
	[TERRITORY] [varchar](18) NULL,
	[CATEGORY] [varchar](MAX) NULL,
	[COPYRIGHT] [varchar](MAX) NULL,
	MSRP [varchar](10) NULL
)

GO

SET ANSI_PADDING OFF
GO
