USE [Odin]
DROP PROCEDURE Odin_ClearDb
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE Odin_ClearDb

AS
BEGIN

	SET NOCOUNT ON;
	
	DELETE FROM PS_ASSET_ITEM_ATTR
	DELETE FROM PS_BU_ITEM_UTIL_CD
	DELETE FROM PS_BU_ITEMS_CONFIG
	DELETE FROM PS_BU_ITEMS_INV
	DELETE FROM PS_CM_GROUP_DEFN
	DELETE FROM PS_CM_ITEM_METHOD
	DELETE FROM PS_COUNTRY_TBL
	DELETE FROM PS_DEFAULT_LOC_INV
	DELETE FROM PS_FXD_BIN_LOC_INV
    DELETE FROM PS_HRMN_TARIFF_CD
	DELETE FROM PS_INV_ITEM_FAM
	DELETE FROM PS_INV_ITEM_GROUP
	DELETE FROM PS_INV_ITEM_UOM
	DELETE FROM PS_INV_ITEMS
	DELETE FROM PS_ITEM_ATTRIB_EX
	DELETE FROM PS_MASTER_ITEM_TBL
	DELETE FROM PS_ORD_LINE
	DELETE FROM PS_PL_ITEM_ATTRIB
	DELETE FROM PS_PROD_PGRP_LNK
	DELETE FROM PS_PROD_GROUP_TBL
	DELETE FROM PS_PROD_CATGRY_TBL
	DELETE FROM PS_PROD_ITEM
	DELETE FROM PS_PROD_PGRP_LNK
	DELETE FROM PS_PROD_PRICE
	DELETE FROM PS_PROD_UOM
	DELETE FROM PS_PRODUCT_FORMATS
    DELETE FROM PS_PRODUCT_GROUPS
    DELETE FROM PS_PRODUCT_LINES
	DELETE FROM PS_PURCH_ITEM_ATTR
	DELETE FROM PS_PURCH_ITEM_BU
	DELETE FROM PS_PURCH_ITEM_ATTR
	DELETE FROM PS_PV_ITM_CATEGORY
	DELETE FROM PS_UOM_TYPE_INV

END
GO