//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdinServices.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OdinServices.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must have a value greater than 0..
        /// </summary>
        internal static string Error_0 {
            get {
                return ResourceManager.GetString("Error_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to already exists in peoplesoft..
        /// </summary>
        internal static string Error_AlreadyExists {
            get {
                return ResourceManager.GetString("Error_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to validation could not make contact with the database..
        /// </summary>
        internal static string Error_DbConnection {
            get {
                return ResourceManager.GetString("Error_DbConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is too long. Value length must be less than .
        /// </summary>
        internal static string Error_LengthMax {
            get {
                return ResourceManager.GetString("Error_LengthMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is too short. Value length must be more than.
        /// </summary>
        internal static string Error_LengthMin {
            get {
                return ResourceManager.GetString("Error_LengthMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to does not match any of the preset values in the database..
        /// </summary>
        internal static string Error_NoMatch {
            get {
                return ResourceManager.GetString("Error_NoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contains a non-numeric value. (Field must contain a numeric value). .
        /// </summary>
        internal static string Error_NonNumeric {
            get {
                return ResourceManager.GetString("Error_NonNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is a required field and cannot be left empty..
        /// </summary>
        internal static string Error_Required {
            get {
                return ResourceManager.GetString("Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is a required value when any ecommerce flag = &apos;Y&apos; or other any ecommerce fields exists..
        /// </summary>
        internal static string Error_RequiredAmazon {
            get {
                return ResourceManager.GetString("Error_RequiredAmazon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is a required value..
        /// </summary>
        internal static string Error_RequiredValue {
            get {
                return ResourceManager.GetString("Error_RequiredValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is a required field for items being set up for our website and cannot be left empty..
        /// </summary>
        internal static string Error_RequiredWeb {
            get {
                return ResourceManager.GetString("Error_RequiredWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot contain special characters..
        /// </summary>
        internal static string Error_SpecialChars {
            get {
                return ResourceManager.GetString("Error_SpecialChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has an invalid value. (Field must be set to &apos;Y&apos; or &apos;N&apos;).
        /// </summary>
        internal static string Error_YorN {
            get {
                return ResourceManager.GetString("Error_YorN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jTp\Zkqw:rQ@@x7m.
        /// </summary>
        internal static string ftpPassword {
            get {
                return ResourceManager.GetString("ftpPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftp@trendsinternational.com.
        /// </summary>
        internal static string ftpUserName {
            get {
                return ResourceManager.GetString("ftpUserName", resourceCulture);
            }
        }
    }
}
